export interface AccountParameter {
  ID: number
  ACCOUNTPARAMETER_CORP_ID: number
  ACCOUNTPARAMETER_LEDGERLENGTH: number
  ACCOUNTPARAMETER_GROUP1LENGTH: number
  ACCOUNTPARAMETER_GROUP2LENGTH: number
  ACCOUNTPARAMETER_GROUP3LENGTH: number
  ACCOUNTPARAMETER_GROUP4LENGTH: number
  ACCOUNTPARAMETER_GROUP5LENGTH: number
  ACCOUNTPARAMETER_REGUSER_ID: number
  ACCOUNTPARAMETER_REGDATE: Date
  ACCOUNTPARAMETER_REGIP: string
}
