export interface AccountingSequence {
  ID: number
  ACCOUNTINGSEQUENCE_CORP_ID: number
  ACCOUNTINGSEQUENCE_SECTION_ID: number
  ACCOUNTINGSEQUENCE_DATE: Date
  ACCOUNTINGSEQUENCE_TYPE_ID: number
  ACCOUNTINGSEQUENCE_NUMBER: number
  ACCOUNTINGSEQUENCE_REGUSER_ID: number
  ACCOUNTINGSEQUENCE_REGDATE: Date
  ACCOUNTINGSEQUENCE_REGIP: string
}
