import { AccountPlan } from '../db/AccountPlan'
import { AccountingMaster } from '../db/AccountingMaster'

export interface AccountingDetail {
  ID: number
  ACCOUNTINGDETAIL_MASTER_ID: number
  ACCOUNTINGDETAIL_ACCOUNT_ID: number
  ACCOUNTINGDETAIL_DEBITCREDIT: string
  ACCOUNTINGDETAIL_AMOUNT: number
  ACCOUNTINGDETAIL_DESCRIPTION?: string
  ACCOUNTINGDETAIL_DOCUMENTNUMBER: string
  ACCOUNTINGDETAIL_DOCUMENTDATE: Date
  ACCOUNTINGDETAIL_DOCUMENTSERIAL: string
  ACCOUNTINGDETAIL_CURRENCY_ID?: number
  ACCOUNTINGDETAIL_CURRENCYAMOUNT: number
  ACCOUNTINGDETAIL_CURRENCYRATE: number
  ACCOUNTINGDETAIL_PAYMENTDATE?: Date
  ACCOUNTINGDETAIL_QUANTITY: number
  ACCOUNTINGDETAIL_DOCUMENTTYPE_ID: number
  ACCOUNTINGDETAIL_DOCUMENTEXPLAIN?: string
  ACCOUNTINGDETAIL_LINK?: string
  ACCOUNTINGDETAIL_REF_ID?: number
  ACCOUNTINGDETAIL_REGUSER_ID: number
  ACCOUNTINGDETAIL_REGDATE: Date
  ACCOUNTINGDETAIL_REGIP: string
  ACCOUNTINGDETAIL_TAXNO?: string
  ACCOUNTINGDETAIL_TITLE?: string
  ACCOUNTINGDETAIL_ACCOUNT?: AccountPlan
  ACCOUNTINGDETAIL_MASTER?: AccountingMaster
}
