export interface BalanceAccMaster {
  ID: number
  BALANCEACCMASTER_CORP_ID?: number
  BALANCEACCMASTER_TYPE_ID?: number
  BALANCEACCMASTER_SECTION_ID?: number
  BALANCEACCMASTER_VOUCHERDATE?: Date
  BALANCEACCMASTER_VOUCHERTYPE_ID?: number
  BALANCEACCMASTER_VOUCHERNUMBER?: number
  BALANCEACCMASTER_REGUSER_ID?: number
  BALANCEACCMASTER_REGDATE?: Date
  BALANCEACCMASTER_REGIP?: string
}
