export interface BalanceCurSequence {
  ID: number
  BALANCECURSEQUENCE_CORP_ID?: number
  BALANCECURSEQUENCE_SECTION_ID?: number
  BALANCECURSEQUENCE_DATE: Date
  BALANCECURSEQUENCE_TYPE_ID?: number
  BALANCECURSEQUENCE_NUMBER: number
  BALANCECURSEQUENCE_REGUSER_ID?: number
  BALANCECURSEQUENCE_REGDATE?: Date
  BALANCECURSEQUENCE_REGIP?: string
}
