export interface BalanceAccBalance {
  ID: number
  BALANCEACCBALANCE_TYPE?: number
  BALANCEACCBALANCE_ACCOUNT_ID?: number
  BALANCEACCBALANCE_ACCOUNTNUMBER?: string
  BALANCEACCBALANCE_ACCOUNTTEMPNUMBER?: string
  BALANCEACCBALANCE_ACCOUNTNAME?: string
  BALANCEACCBALANCE_UPPERACCOUNT_ID?: number
  BALANCEACCBALANCE_DEBITTOTAL?: number
  BALANCEACCBALANCE_CREDITTOTAL?: number
  BALANCEACCBALANCE_DEBITBALANCE?: number
  BALANCEACCBALANCE_CREDITBALANCE?: number
  BALANCEACCBALANCE_KNT?: number
  BALANCEACCBALANCE_REGUSER_ID?: number
  BALANCEACCBALANCE_REGDATE?: Date
  BALANCEACCBALANCE_REGIP?: string
}
