export interface BalanceAccDetail {
  ID: number
  BALANCEACCDETAIL_MASTER_ID?: number
  BALANCEACCDETAIL_ACCOUNTPLAN_ID?: number
  BALANCEACCDETAIL_DEBITCREDIT?: string
  BALANCEACCDETAIL_AMOUNT?: number
  BALANCEACCDETAIL_DESCRIPTION?: string
  BALANCEACCDETAIL_REGUSER_ID?: number
  BALANCEACCDETAIL_REGDATE?: Date
  BALANCEACCDETAIL_REGIP?: string
}
