export interface BalanceAccSequence {
  ID: number
  BALANCEACCSEQUENCE_CORP_ID?: number
  BALANCEACCSEQUENCE_SECTION_ID?: number
  BALANCEACCSEQUENCE_DATE: Date
  BALANCEACCSEQUENCE_TYPE_ID?: number
  BALANCEACCSEQUENCE_NUMBER: number
  BALANCEACCSEQUENCE_REGUSER_ID?: number
  BALANCEACCSEQUENCE_REGDATE?: Date
  BALANCEACCSEQUENCE_REGIP?: string
}
