export interface BalanceCurBalance {
  ID: number
  BALANCECURBALANCE_ACCOUNT_ID?: number
  BALANCECURBALANCE_ACCOUNTNUMBER?: string
  BALANCECURBALANCE_ACCOUNTTEMPNUMBER?: string
  BALANCECURBALANCE_ACCOUNTNAME?: string
  BALANCECURBALANCE_UPPERACCOUNT_ID?: number
  BALANCECURBALANCE_DEBITTOTAL?: number
  BALANCECURBALANCE_CREDITTOTAL?: number
  BALANCECURBALANCE_DEBITBALANCE?: number
  BALANCECURBALANCE_CREDITBALANCE?: number
  BALANCECURBALANCE_KNT?: number
  BALANCECURBALANCE_REGUSER_ID?: number
  BALANCECURBALANCE_REGDATE?: Date
  BALANCECURBALANCE_REGIP?: string
  BALANCECURBALANCE_TYPE?: number
}
