export interface BalanceCurMaster {
  ID: number
  BALANCECURMASTER_CORP_ID?: number
  BALANCECURMASTER_TYPE_ID?: number
  BALANCECURMASTER_SECTION_ID?: number
  BALANCECURMASTER_VOUCHERDATE?: Date
  BALANCECURMASTER_VOUCHERTYPE_ID?: number
  BALANCECURMASTER_VOUCHERNUMBER?: number
  BALANCECURMASTER_REGUSER_ID?: number
  BALANCECURMASTER_REGDATE?: Date
  BALANCECURMASTER_REGIP?: string
}
