export interface BalanceCurTerm {
  ID: number
  BALANCECURTERM_CORP_ID?: number
  BALANCECURTERM_TYPE_ID?: number
  BALANCECURTERM_TERM?: number
  BALANCECURTERM_BALANCE_ID?: number
  BALANCECURTERM_AMOUNT?: number
  BALANCECURTERM_REGUSER_ID?: number
  BALANCECURTERM_REGDATE?: Date
  BALANCECURTERM_REGIP?: string
}
