export interface BankProjectMaster {
  ID: number
  BANKPROJECTMASTER_CORP_ID?: number
  BANKPROJECTMASTER_SECTION_ID?: number
  BANKPROJECTMASTER_YEAR?: number
  BANKPROJECTMASTER_SERIAL_ID?: number
  BANKPROJECTMASTER_NUMBER?: number
  BANKPROJECTMASTER_DATE?: Date
  BANKPROJECTMASTER_PROJECTNUMBER?: string
  BANKPROJECTMASTER_TYPE_ID?: number
  BANKPROJECTMASTER_CURRENTACCOUNTPLAN_ID?: number
  BANKPROJECTMASTER_REGUSER_ID?: number
  BANKPROJECTMASTER_REGDATE?: Date
  BANKPROJECTMASTER_REGIP?: string
  BANKPROJECTMASTER_KIND_ID?: number
  BANKPROJECTMASTER_GROUPCURRENTACCOUNTPLAN_ID?: number
}
