export interface BomAction {
  ID: number
  BOMACTION_REGUSER_ID?: number
  BOMACTION_MAINITEM_ID?: number
  BOMACTION_SUBITEM_ID?: number
  BOMACTION_DOUGHITEM_ID?: number
  BOMACTION_ITEM_ID?: number
  BOMACTION_TYPE_ID?: number
  BOMACTION_STATION_ID?: number
  BOMACTION_KNIFECYLINDER_ID?: number
  BOMACTION_SEQUENCE?: number
  BOMACTION_QUANTITY?: number
  BOMACTION_QUANTITY2?: number
  BOMACTION_DIMENSION01_ID?: number
  BOMACTION_DIMENSION02_ID?: number
  BOMACTION_BOMMASTER_ID?: number
  BOMACTION_BOMDETAIL_ID?: number
}
