export interface BomDetail {
  ID: number
  BOMDETAIL_MASTER_ID: number
  BOMDETAIL_ITEM_ID: number
  BOMDETAIL_UNIT_ID: number
  BOMDETAIL_QUANTITY: number
  BOMDETAIL_REGUSER_ID?: number
  BOMDETAIL_REGDATE?: Date
  BOMDETAIL_REGIP?: string
  BOMDETAIL_LEGALLIMIT?: string
  BOMDETAIL_DESCRIPTION?: string
  BOMDETAIL_CONTROL?: string
  BOMDETAIL_TYPE_ID?: number
  BOMDETAIL_RATE?: number
  BOMDETAIL_STATION_ID?: number
  BOMDETAIL_SEQUENCE?: number
  BOMDETAIL_QUANTITYDEF?: number
  BOMDETAIL_DRYQUANTITY?: number
  BOMDETAIL_DRYQUANTITYDEF?: number
  BOMDETAIL_EQUIPMENT_ID?: number
  BOMDETAIL_KNIFECYLINDER_ID?: number
  BOMDETAIL_SPEED?: number
  BOMDETAIL_DOUGHRATE?: string
  BOMDETAIL_STATIONREPEAT?: boolean
  BOMDETAIL_HEAT?: number
  BOMDETAIL_PRESSURE?: number
}
