export interface BomSpecDetail {
  ID: number
  BOMSPECDETAIL_MASTER_ID?: number
  BOMSPECDETAIL_GROUP_ID?: number
  BOMSPECDETAIL_TYPE_ID?: number
  BOMSPECDETAIL_KIND?: number
  BOMSPECDETAIL_REGUSER_ID?: number
  BOMSPECDETAIL_REGDATE?: Date
  BOMSPECDETAIL_REGIP?: string
  BOMSPECDETAIL_RATE?: number
  BOMSPECDETAIL_DESCRIPTION?: string
  BOMSPECDETAIL_STANDARTVALUE?: string
  BOMSPECDETAIL_MINVALUE?: number
  BOMSPECDETAIL_MAXVALUE?: number
  BOMSPECDETAIL_DOCUMENTTYPE_ID?: number
  BOMSPECDETAIL_USUALANSWER?: boolean
  BOMSPECDETAIL_ALLERGENANSWERBOM?: boolean
  BOMSPECDETAIL_ALLERGENANSWERPROD?: boolean
  BOMSPECDETAIL_ALLERGENANSWERFACT?: boolean
  BOMSPECDETAIL_ANALYSIS_ID?: number
  BOMSPECDETAIL_DESCRIPTIONENGLISH?: string
}
