export interface BudgetExpenseDetailSub {
  ID: number
  BUDGETEXPENSEDETAILSUB_DETAIL_ID: number
  BUDGETEXPENSEDETAILSUB_MASTER_ID?: number
  BUDGETEXPENSEDETAILSUB_TYPE_ID?: number
  BUDGETEXPENSEDETAILSUB_DEFINITION_ID?: number
  BUDGETEXPENSEDETAILSUB_REGUSER_ID?: number
  BUDGETEXPENSEDETAILSUB_REGDATE?: Date
  BUDGETEXPENSEDETAILSUB_REGIP?: string
}
