export interface BudgetExchange {
  ID: number
  BUDGETEXCHANGE_CORP_ID?: number
  BUDGETEXCHANGE_YEAR: number
  BUDGETEXCHANGE_JANUARY?: number
  BUDGETEXCHANGE_FEBRUARY?: number
  BUDGETEXCHANGE_MARCH?: number
  BUDGETEXCHANGE_APRIL?: number
  BUDGETEXCHANGE_MAY?: number
  BUDGETEXCHANGE_JUNE?: number
  BUDGETEXCHANGE_JULY?: number
  BUDGETEXCHANGE_AUGUST?: number
  BUDGETEXCHANGE_SEPTEMBER?: number
  BUDGETEXCHANGE_OCTOBER?: number
  BUDGETEXCHANGE_NOVEMBER?: number
  BUDGETEXCHANGE_DECEMBER?: number
  BUDGETEXCHANGE_CURRENCY_ID?: number
  BUDGETEXCHANGE_REGUSER_ID?: number
  BUDGETEXCHANGE_REGDATE?: Date
  BUDGETEXCHANGE_REGIP?: string
}
