export interface BudgetRevision {
  ID: number
  BUDGETREVISION_CORP_ID?: number
  BUDGETREVISION_YEAR?: number
  BUDGETREVISION_NUMBER?: number
  BUDGETREVISION_MONTH?: number
  BUDGETREVISION_CLOSED?: boolean
  BUDGETREVISION_REFREVISION_ID?: number
  BUDGETREVISION_REGUSER_ID?: number
  BUDGETREVISION_REGDATE?: Date
  BUDGETREVISION_REGIP?: string
}
