export interface BudgetMasterAlternative {
  ID: number
  BUDGETMASTERALTERNATIVE_CORP_ID?: number
  BUDGETMASTERALTERNATIVE_SECTION_ID?: number
  BUDGETMASTERALTERNATIVE_TYPE?: number
  BUDGETMASTERALTERNATIVE_YEAR: number
  BUDGETMASTERALTERNATIVE_REVISED?: number
  BUDGETMASTERALTERNATIVE_ALTERNATIVE?: number
  BUDGETMASTERALTERNATIVE_COMPANY_ID?: number
  BUDGETMASTERALTERNATIVE_CURRENCY_ID?: number
  BUDGETMASTERALTERNATIVE_DESCRIPTION?: string
  BUDGETMASTERALTERNATIVE_LIMIT?: number
  BUDGETMASTERALTERNATIVE_REGUSER_ID?: number
  BUDGETMASTERALTERNATIVE_REGDATE?: Date
  BUDGETMASTERALTERNATIVE_REGIP?: string
}
