export interface BudgetMaster {
  ID: number
  BUDGETMASTER_CORP_ID?: number
  BUDGETMASTER_SECTION_ID?: number
  BUDGETMASTER_YEAR: number
  BUDGETMASTER_COMPANY_ID?: number
  BUDGETMASTER_CURRENCY_ID?: number
  BUDGETMASTER_REVISED?: number
  BUDGETMASTER_TYPE?: number
  BUDGETMASTER_DESCRIPTION?: string
  BUDGETMASTER_LIMIT?: number
  BUDGETMASTER_REGUSER_ID?: number
  BUDGETMASTER_REGDATE?: Date
  BUDGETMASTER_REGIP?: string
}
