export interface BudgetRevisionAlternative {
  ID: number
  BUDGETREVISIONALTERNATIVE_CORP_ID?: number
  BUDGETREVISIONALTERNATIVE_YEAR?: number
  BUDGETREVISIONALTERNATIVE_REVNUMBER?: number
  BUDGETREVISIONALTERNATIVE_NUMBER?: number
  BUDGETREVISIONALTERNATIVE_CLOSED?: boolean
  BUDGETREVISIONALTERNATIVE_LINK?: string
  BUDGETREVISIONALTERNATIVE_REF_ID?: number
  BUDGETREVISIONALTERNATIVE_DESCRIPTION?: string
  BUDGETREVISIONALTERNATIVE_REGUSER_ID?: number
  BUDGETREVISIONALTERNATIVE_REGDATE?: Date
  BUDGETREVISIONALTERNATIVE_REGIP?: string
}
