export interface BudgetExpenseRevision {
  ID: number
  BUDGETEXPENSEREVISION_CORP_ID?: number
  BUDGETEXPENSEREVISION_YEAR?: number
  BUDGETEXPENSEREVISION_NUMBER?: number
  BUDGETEXPENSEREVISION_MONTH?: number
  BUDGETEXPENSEREVISION_CLOSED?: boolean
  BUDGETEXPENSEREVISION_REFREVISION_ID?: number
  BUDGETEXPENSEREVISION_REGUSER_ID?: number
  BUDGETEXPENSEREVISION_REGDATE?: Date
  BUDGETEXPENSEREVISION_REGIP?: string
}
