export interface BudgetCapacityMasterAlternative {
  ID: number
  BUDGETCAPACITYMASTERALTERNATIVE_CORP_ID?: number
  BUDGETCAPACITYMASTERALTERNATIVE_SECTION_ID?: number
  BUDGETCAPACITYMASTERALTERNATIVE_YEAR: number
  BUDGETCAPACITYMASTERALTERNATIVE_NUMBER?: number
  BUDGETCAPACITYMASTERALTERNATIVE_REVISED?: number
  BUDGETCAPACITYMASTERALTERNATIVE_DESCRIPTION?: string
  BUDGETCAPACITYMASTERALTERNATIVE_REGUSER_ID?: number
  BUDGETCAPACITYMASTERALTERNATIVE_REGDATE?: Date
  BUDGETCAPACITYMASTERALTERNATIVE_REGIP?: string
}
