import { CurrentAccountPlan } from '../db/CurrentAccountPlan'
import { ExpensePlan } from '../db/ExpensePlan'
import { CashBankMaster } from '../db/CashBankMaster'

export interface CashBankDetail {
  ID: number
  CASHBANKDETAIL_MASTER_ID: number
  CASHBANKDETAIL_CURRENTACCOUNT_ID: number
  CASHBANKDETAIL_SUBACCOUNT_ID: number
  CASHBANKDETAIL_DESCRIPTION?: string
  CASHBANKDETAIL_DEBITCREDIT: string
  CASHBANKDETAIL_AMOUNT: number
  CASHBANKDETAIL_CURRENCY_ID?: number
  CASHBANKDETAIL_CURRENCYAMOUNT: number
  CASHBANKDETAIL_CURRENCYRATE: number
  CASHBANKDETAIL_VATRATE: number
  CASHBANKDETAIL_VATAMOUNT: number
  CASHBANKDETAIL_DOCUMENTSERIAL: string
  CASHBANKDETAIL_DOCUMENTNUMBER: string
  CASHBANKDETAIL_DOCUMENTDATE: Date
  CASHBANKDETAIL_OPRCURRENCY_ID?: number
  CASHBANKDETAIL_OPRAMOUNT: number
  CASHBANKDETAIL_LINK?: string
  CASHBANKDETAIL_REF_ID?: number
  CASHBANKDETAIL_REGUSER_ID: number
  CASHBANKDETAIL_REGDATE: Date
  CASHBANKDETAIL_REGIP: string
  CASHBANKDETAIL_DEPARTMENT_ID?: number
  CASHBANKDETAIL_DENIALAMOUNT: number
  CASHBANKDETAIL_DENIALVATAMOUNT: number
  CASHBANKDETAIL_NOTDENIALAMOUNT?: number
  CASHBANKDETAIL_NOTDENIALRATE?: number
  CASHBANKDETAIL_EXPENSE_ID?: number
  CASHBANKDETAIL_OPRCURRENCYRATE: number
  CASHBANKDETAIL_TITLE?: string
  CASHBANKDETAIL_TAXNO?: string
  CASHBANKDETAIL_PARAM1_ID?: number
  CASHBANKDETAIL_PARAM2_ID?: number
  CASHBANKDETAIL_PARAM3_ID?: number
  CASHBANKDETAIL_PARAM4_ID?: number
  CASHBANKDETAIL_CURRENTACCOUNT?: CurrentAccountPlan
  CASHBANKDETAIL_EXPENSE?: ExpensePlan
  CASHBANKDETAIL_MASTER?: CashBankMaster
}
