export interface CollectionDetail {
  ID: number
  COLLECTIONDETAIL_MASTER_ID?: number
  COLLECTIONDETAIL_CURRENTACCOUNT_ID?: number
  COLLECTIONDETAIL_SUBACCOUNT_ID?: number
  COLLECTIONDETAIL_TYPE_ID?: number
  COLLECTIONDETAIL_DESCRIPTION?: string
  COLLECTIONDETAIL_AMOUNT?: number
  COLLECTIONDETAIL_CURRENCY_ID?: number
  COLLECTIONDETAIL_CURRECYAMOUNT?: number
  COLLECTIONDETAIL_CURRENCYRATE?: number
  COLLECTIONDETAIL_CREDITAMOUNT?: number
  COLLECTIONDETAIL_DOCUMENTDATE?: Date
  COLLECTIONDETAIL_PAYMENTDATE?: Date
  COLLECTIONDETAIL_CONFIRM?: boolean
  COLLECTIONDETAIL_LINK?: string
  COLLECTIONDETAIL_REF_ID?: number
  COLLECTIONDETAIL_REGUSER_ID?: number
  COLLECTIONDETAIL_REGDATE?: Date
  COLLECTIONDETAIL_REGIP?: string
}
