export interface CollectionMaster {
  ID: number
  COLLECTIONMASTER_CORP_ID?: number
  COLLECTIONMASTER_SECTION_ID?: number
  COLLECTIONMASTER_YEAR: number
  COLLECTIONMASTER_SERIAL_ID?: number
  COLLECTIONMASTER_NUMBER: number
  COLLECTIONMASTER_DATE: Date
  COLLECTIONMASTER_CLOSED?: boolean
  COLLECTIONMASTER_REGUSER_ID?: number
  COLLECTIONMASTER_REGDATE?: Date
  COLLECTIONMASTER_REGIP?: string
  COLLECTIONMASTER_BANKACCOUNT_ID?: number
  COLLECTIONMASTER_CURRENTCONFIRM?: boolean
  COLLECTIONMASTER_FORCASHFLOW?: boolean
}
