export interface CompanyDocument {
  ID: number
  COMPANYDOCUMENT_COMPANY_ID?: number
  COMPANYDOCUMENT_TYPE_ID?: number
  COMPANYDOCUMENT_URL?: string
  COMPANYDOCUMENT_DESCRIPTION?: string
  COMPANYDOCUMENT_VALIDDATE?: Date
  COMPANYDOCUMENT_SUPPLIEREVALANSWER_ID?: number
  COMPANYDOCUMENT_REGUSER_ID?: number
  COMPANYDOCUMENT_REGDATE?: Date
  COMPANYDOCUMENT_REGIP?: string
}
