import { Company } from '../db/Company'

export interface CompanyRepresentative {
  ID: number
  COMPANYREPRESENTATIVE_COMPANY_ID: number
  COMPANYREPRESENTATIVE_REPRESENTATIVE_ID: number
  COMPANYREPRESENTATIVE_REGDATE: Date
  COMPANYREPRESENTATIVE_REGIP: string
  COMPANYREPRESENTATIVE_REGUSER_ID: number
  COMPANYREPRESENTATIVE_CORP_ID: number
  COMPANYREPRESENTATIVE_COMPANY?: Company
}
