export interface CompanySalesDetail {
  ID: number
  COMPANYSALESDETAIL_MASTER_ID: number
  COMPANYSALESDETAIL_ITEM_ID?: number
  COMPANYSALESDETAIL_QUANTITY?: number
  COMPANYSALESDETAIL_UNIT_ID?: number
  COMPANYSALESDETAIL_PRICE?: number
  COMPANYSALESDETAIL_AMOUNT?: number
  COMPANYSALESDETAIL_DESCRIPTION?: string
  COMPANYSALESDETAIL_REGUSER_ID?: number
  COMPANYSALESDETAIL_REGDATE?: Date
  COMPANYSALESDETAIL_REGIP?: string
}
