export interface CompanyContractMaster {
  ID: number
  COMPANYCONTRACTMASTER_CORP_ID?: number
  COMPANYCONTRACTMASTER_YEAR?: number
  COMPANYCONTRACTMASTER_SECTION_ID?: number
  COMPANYCONTRACTMASTER_NUMBER?: number
  COMPANYCONTRACTMASTER_DATE?: Date
  COMPANYCONTRACTMASTER_TYPE_ID?: number
  COMPANYCONTRACTMASTER_COMPANY_ID?: number
  COMPANYCONTRACTMASTER_ENDDATE?: Date
  COMPANYCONTRACTMASTER_SUBJECT?: string
  COMPANYCONTRACTMASTER_DESCRIPTION?: string
  COMPANYCONTRACTMASTER_REGUSER_ID?: number
  COMPANYCONTRACTMASTER_REGDATE?: Date
  COMPANYCONTRACTMASTER_REGIP?: string
}
