export interface CompanySalesMaster {
  ID: number
  COMPANYSALESMASTER_CORP_ID: number
  COMPANYSALESMASTER_SECTION_ID: number
  COMPANYSALESMASTER_YEAR: number
  COMPANYSALESMASTER_NUMBER: number
  COMPANYSALESMASTER_DATE: Date
  COMPANYSALESMASTER_COMPANY_ID: number
  COMPANYSALESMASTER_TYPE: number
  COMPANYSALESMASTER_REGUSER_ID: number
  COMPANYSALESMASTER_REGDATE: Date
  COMPANYSALESMASTER_REGIP: string
}
