export interface CompanySurvey {
  ID: number
  COMPANYSURVEY_CORP_ID?: number
  COMPANYSURVEY_MASTER_ID?: number
  COMPANYSURVEY_DESCRIPTION?: string
  COMPANYSURVEY_GROUPNAME?: string
  COMPANYSURVEY_POINT?: number
  COMPANYSURVEY_PASSIVE?: boolean
  COMPANYSURVEY_TYPE?: number
  COMPANYSURVEY_REGUSER_ID?: number
  COMPANYSURVEY_REGDATE?: Date
  COMPANYSURVEY_REGIP?: string
}
