export interface CompanyNoteUser {
  ID: number
  COMPANYNOTEUSER_COMPANY_ID: number
  COMPANYNOTEUSER_COMPANYNOTE_ID: number
  COMPANYNOTEUSER_USER_ID: number
  COMPANYNOTEUSER_REGDATE?: Date
  COMPANYNOTEUSER_REGUSER_ID?: number
  COMPANYNOTEUSER_REGIP?: string
}
