export interface CompanyGroup {
  ID: number
  COMPANYGROUP_MASTER_ID?: number
  COMPANYGROUP_GROUPMASTER_ID?: number
  COMPANYGROUP_GROUPDETAIL_ID?: number
  COMPANYGROUP_GROUPDEFINITION_ID?: number
  COMPANYGROUP_REGUSER_ID?: number
  COMPANYGROUP_REGDATE?: Date
  COMPANYGROUP_REGIP?: string
}
