export interface ConfirmSupplier {
  ID: number
  CONFIRMSUPPLIER_ITEM_ID?: number
  CONFIRMSUPPLIER_COMPANY_ID?: number
  CONFIRMSUPPLIER_COUNTRY_ID?: number
  CONFIRMSUPPLIER_MANUFACTURER?: string
  CONFIRMSUPPLIER_SUPPLIERITEM?: string
  CONFIRMSUPPLIER_USEDFACTORY?: string
  CONFIRMSUPPLIER_USEGROUPITEM?: string
  CONFIRMSUPPLIER_REGUSER_ID?: number
  CONFIRMSUPPLIER_REGDATE?: Date
  CONFIRMSUPPLIER_REGIP?: string
  CONFIRMSUPPLIER_CORP_ID?: number
}
