export interface ConfirmControl {
  ID: number
  CONFIRMCONTROL_CORP_ID?: number
  CONFIRMCONTROL_LINK?: string
  CONFIRMCONTROL_REF_ID?: number
  CONFIRMCONTROL_TITLE_ID?: number
  CONFIRMCONTROL_SCENARIO_ID?: number
  CONFIRMCONTROL_TIME?: Date
  CONFIRMCONTROL_CONFIRM?: boolean
  CONFIRMCONTROL_CONFIRMTIME?: Date
  CONFIRMCONTROL_PERSON_ID?: number
  CONFIRMCONTROL_REGUSER_ID?: number
  CONFIRMCONTROL_REGDATE?: Date
  CONFIRMCONTROL_REGIP?: string
}
