export interface ContractBomDetail {
  ID: number
  CONTRACTBOMDETAIL_REGUSER_ID?: number
  CONTRACTBOMDETAIL_REGDATE?: Date
  CONTRACTBOMDETAIL_REGIP?: string
  CONTRACTBOMDETAIL_MASTER_ID: number
  CONTRACTBOMDETAIL_ITEM_ID: number
  CONTRACTBOMDETAIL_UNIT_ID: number
  CONTRACTBOMDETAIL_QUANTITY: number
  CONTRACTBOMDETAIL_DESCRIPTION: string
}
