export interface ContractBomMaster {
  ID: number
  CONTRACTBOMMASTER_REGUSER_ID?: number
  CONTRACTBOMMASTER_REGDATE?: Date
  CONTRACTBOMMASTER_REGIP?: string
  CONTRACTBOMMASTER_CORP_ID: number
  CONTRACTBOMMASTER_REVISIONNO?: number
  CONTRACTBOMMASTER_REVISIONDATE?: Date
  CONTRACTBOMMASTER_ITEM_ID: number
  CONTRACTBOMMASTER_UNIT_ID: number
  CONTRACTBOMMASTER_QUANTITY: number
  CONTRACTBOMMASTER_ACTIVE?: boolean
  CONTRACTBOMMASTER_ALTERNATIVE?: boolean
  CONTRACTBOMMASTER_DESCRIPTION?: string
  CONTRACTBOMMASTER_COMPANY_ID?: number
  CONTRACTBOMMASTER_PRICE?: number
  CONTRACTBOMMASTER_CURRENCY_ID?: number
}
