export interface CorporationParameter {
  ID: number
  CORPORATIONPARAMETER_CORP_ID: number
  CORPORATIONPARAMETER_TYPE_ID: number
  CORPORATIONPARAMETER_RATE_ID?: number
  CORPORATIONPARAMETER_CURRENTACCOUNT_ID?: number
  CORPORATIONPARAMETER_ACCOUNT_ID?: number
  CORPORATIONPARAMETER_REGUSER_ID: number
  CORPORATIONPARAMETER_REGDATE: Date
  CORPORATIONPARAMETER_REGIP: string
}
