export interface CostPrice {
  ID: number
  COSTPRICE_YEAR?: number
  COSTPRICE_MONTH?: number
  COSTPRICE_ITEM_ID?: number
  COSTPRICE_AVGPRICE?: number
  COSTPRICE_LASTPRICE?: number
  COSTPRICE_AVGPRICE_CUR?: number
  COSTPRICE_LASTPRICE_CUR?: number
  COSTPRICE_REGUSER_ID?: number
  COSTPRICE_REGDATE?: Date
  COSTPRICE_REGIP?: string
  COSTPRICE_AVGCURRATE?: number
  COSTPRICE_AVGPRICE_EXPCUR?: number
  COSTPRICE_LASTPRICE_EXPCUR?: number
  COSTPRICE_INPRICECURRENCY_ID?: number
  COSTPRICE_INPRICE?: number
  COSTPRICE_INPRICEDOCDATE?: Date
  COSTPRICE_OUTPRICECURRENCY_ID?: number
  COSTPRICE_OUTPRICE?: number
  COSTPRICE_OUTPRICEDOCUMENTDATE?: Date
  COSTPRICE_AVGCURRATE_USD?: number
  COSTPRICE_AVGCURRATE_EUR?: number
  COSTPRICE_DESCRIPTION?: string
  COSTPRICE_CORP_ID?: number
}
