export interface CostValue {
  ID?: number
  COSTVALUE_YEAR?: number
  COSTVALUE_MONTH?: number
  COSTVALUE_PRODUCTIONDETAIL_ID?: number
  COSTVALUE_PRODUCTIONORDERDETAIL_ID?: number
  COSTVALUE_STATION_ID?: number
  COSTVALUE_SEQUENCE?: number
  COSTVALUE_ITEM_ID?: number
  COSTVALUE_DIMENSION01_ID?: number
  COSTVALUE_QUANTITY?: number
  COSTVALUE_AMOUNT?: number
  COSTVALUE_CURAMOUNT?: number
  COSTVALUE_REGUSER_ID?: number
  COSTVALUE_REGDATE?: Date
  COSTVALUE_REGIP?: string
  COSTVALUE_GENEXPENSE?: number
  COSTVALUE_CURGENEXPENSE?: number
}
