export interface CostVariantMaster {
  ID: number
  COSTVARIANTMASTER_CORP_ID?: number
  COSTVARIANTMASTER_SECTION_ID?: number
  COSTVARIANTMASTER_YEAR?: number
  COSTVARIANTMASTER_SERIAL_ID?: number
  COSTVARIANTMASTER_NUMBER?: number
  COSTVARIANTMASTER_DATE?: Date
  COSTVARIANTMASTER_TYPE?: number
  COSTVARIANTMASTER_DESCRIPTION?: string
  COSTVARIANTMASTER_REGUSER_ID?: number
  COSTVARIANTMASTER_REGDATE?: Date
  COSTVARIANTMASTER_REGIP?: string
}
