import { CountMaster } from '../db/CountMaster'

export interface CountAnalysis {
  ID: number
  COUNTANALYSIS_TYPE: number
  COUNTANALYSIS_MASTER_ID: number
  COUNTANALYSIS_QUANTITY: number
  COUNTANALYSIS_STOCKQUANTITY: number
  COUNTANALYSIS_BALANCEQUANTITY: number
  COUNTANALYSIS_BARCODE_ID: number
  COUNTANALYSIS_RACK_ID: number
  COUNTANALYSIS_REGUSER_ID: number
  COUNTANALYSIS_REGDATE: Date
  COUNTANALYSIS_REGIP: string
  COUNTANALYSIS_PIECE: number
  COUNTANALYSIS_STOCKPIECE: number
  COUNTANALYSIS_BALANCEPIECE: number
  COUNTANALYSIS_MASTER?: CountMaster
}
