import { Corporation } from '../db/Corporation'
import { CurrentAccountDetail } from '../db/CurrentAccountDetail'

export interface CurrentAccountMaster {
  ID: number
  CURRENTACCOUNTMASTER_CORP_ID: number
  CURRENTACCOUNTMASTER_SECTION_ID: number
  CURRENTACCOUNTMASTER_YEAR: number
  CURRENTACCOUNTMASTER_SERIAL_ID: number
  CURRENTACCOUNTMASTER_NUMBER: number
  CURRENTACCOUNTMASTER_DATE: Date
  CURRENTACCOUNTMASTER_OPERATION_ID: number
  CURRENTACCOUNTMASTER_LINK?: string
  CURRENTACCOUNTMASTER_REF_ID?: number
  CURRENTACCOUNTMASTER_REGUSER_ID: number
  CURRENTACCOUNTMASTER_REGDATE: Date
  CURRENTACCOUNTMASTER_REGIP: string
  CURRENTACCOUNTMASTER_ACCOUNTING: boolean
  CURRENTACCOUNTMASTER_CONFIRM: boolean
  CURRENTACCOUNTMASTER_CORP?: Corporation
  CurrentAccountDetail: CurrentAccountDetail[]
}
