export interface CurrentAccountDue {
  ID: number
  CURRENTACCOUNTDUE_TYPE?: number
  CURRENTACCOUNTDUE_CORP_ID?: number
  CURRENTACCOUNTDUE_ACCOUNT_ID?: number
  CURRENTACCOUNTDUE_SUBACCOUNT_ID?: number
  CURRENTACCOUNTDUE_OPERATIONDATE?: Date
  CURRENTACCOUNTDUE_REPORTDATE?: Date
  CURRENTACCOUNTDUE_PAYMENTDATE?: Date
  CURRENTACCOUNTDUE_DAY?: number
  CURRENTACCOUNTDUE_AMOUNT?: number
  CURRENTACCOUNTDUE_CURRENCY_ID?: number
  CURRENTACCOUNTDUE_CURRENCYAMOUNT?: number
  CURRENTACCOUNTDUE_DESCRIPTION?: string
  CURRENTACCOUNTDUE_BALANCE?: number
  CURRENTACCOUNTDUE_LINK?: string
  CURRENTACCOUNTDUE_REF_ID?: number
  CURRENTACCOUNTDUE_REGUSER_ID?: number
  CURRENTACCOUNTDUE_REGDATE?: Date
  CURRENTACCOUNTDUE_REGIP?: string
}
