import { CurrentAccountPlan } from '../db/CurrentAccountPlan'
import { CurrentAccountMaster } from '../db/CurrentAccountMaster'

export interface CurrentAccountDetail {
  ID: number
  CURRENTACCOUNTDETAIL_MASTER_ID: number
  CURRENTACCOUNTDETAIL_CURRENTACCOUNT_ID: number
  CURRENTACCOUNTDETAIL_SUBACCOUNT_ID?: number
  CURRENTACCOUNTDETAIL_DOCUMENTSERIAL: string
  CURRENTACCOUNTDETAIL_DOCUMENTNUMBER: string
  CURRENTACCOUNTDETAIL_DOCUMENTDATE: Date
  CURRENTACCOUNTDETAIL_DEBITCREDIT: string
  CURRENTACCOUNTDETAIL_AMOUNT: number
  CURRENTACCOUNTDETAIL_CURRENCY_ID?: number
  CURRENTACCOUNTDETAIL_CURRENCYAMOUNT: number
  CURRENTACCOUNTDETAIL_CURRENCYRATE: number
  CURRENTACCOUNTDETAIL_DESCRIPTION?: string
  CURRENTACCOUNTDETAIL_PAYMENTDATE?: Date
  CURRENTACCOUNTDETAIL_EXPENSE_ID?: number
  CURRENTACCOUNTDETAIL_QUANTITY: number
  CURRENTACCOUNTDETAIL_LINK?: string
  CURRENTACCOUNTDETAIL_REF_ID?: number
  CURRENTACCOUNTDETAIL_REGUSER_ID: number
  CURRENTACCOUNTDETAIL_REGDATE: Date
  CURRENTACCOUNTDETAIL_REGIP: string
  CURRENTACCOUNTDETAIL_DEPARTMENT_ID?: number
  CURRENTACCOUNTDETAIL_TAXNO?: string
  CURRENTACCOUNTDETAIL_TITLE?: string
  CURRENTACCOUNTDETAIL_CURRENTACCOUNT?: CurrentAccountPlan
  CURRENTACCOUNTDETAIL_MASTER?: CurrentAccountMaster
}
