export interface CurrentAccount {
  ID: number
  CURRENTACCOUNT_CURRENTMASTER_ID?: number
  CURRENTACCOUNT_ACCOUNTPLANNUMBER?: string
  CURRENTACCOUNT_REGUSER_ID?: number
  CURRENTACCOUNT_REGDATE?: Date
  CURRENTACCOUNT_REGIP?: string
}
