export interface CurrentAccountParameter {
  ID: number
  CURRENTACCOUNTPARAMETER_CORP_ID: number
  CURRENTACCOUNTPARAMETER_LEDGERLENGTH: number
  CURRENTACCOUNTPARAMETER_GROUP1LENGTH: number
  CURRENTACCOUNTPARAMETER_GROUP2LENGTH: number
  CURRENTACCOUNTPARAMETER_GROUP3LENGTH: number
  CURRENTACCOUNTPARAMETER_GROUP4LENGTH: number
  CURRENTACCOUNTPARAMETER_GROUP5LENGTH: number
  CURRENTACCOUNTPARAMETER_REGUSER_ID: number
  CURRENTACCOUNTPARAMETER_REGDATE: Date
  CURRENTACCOUNTPARAMETER_REGIP: string
}
