export interface CustomExitDeclaration {
  ID: number
  CUSTOMEXITDECLARATION_CORP_ID?: number
  CUSTOMEXITDECLARATION_NUMBER: string
  CUSTOMEXITDECLARATION_DATE: Date
  CUSTOMEXITDECLARATION_IMPORTINVOICENUMBER?: string
  CUSTOMEXITDECLARATION_IMPORTINVOICEDATE?: Date
  CUSTOMEXITDECLARATION_QUANTITY?: number
  CUSTOMEXITDECLARATION_DESCRIPTION?: string
  CUSTOMEXITDECLARATION_REGUSER_ID?: number
  CUSTOMEXITDECLARATION_REGDATE?: Date
  CUSTOMEXITDECLARATION_REGIP?: string
}
