export interface DimensionParameter {
  ID: number
  DIMENSIONPARAMETER_REGUSER_ID?: number
  DIMENSIONPARAMETER_REGDATE?: Date
  DIMENSIONPARAMETER_REGIP?: string
  DIMENSIONPARAMETER_CORP_ID?: number
  DIMENSIONPARAMETER_TYPE_ID?: number
  DIMENSIONPARAMETER_DIMENSIONMASTER_ID?: number
}
