export interface DimensionDetail {
  ID: number
  DIMENSIONDETAIL_REGUSER_ID?: number
  DIMENSIONDETAIL_REGDATE?: Date
  DIMENSIONDETAIL_REGIP?: string
  DIMENSIONDETAIL_CORP_ID?: number
  DIMENSIONDETAIL_MASTER_ID?: number
  DIMENSIONDETAIL_CODE?: string
  DIMENSIONDETAIL_NAME?: string
  DIMENSIONDETAIL_DEFAULT?: boolean
  DIMENSIONDETAIL_TYPE_ID?: number
  DIMENSIONDETAIL_PRIVATECODE1?: string
  DIMENSIONDETAIL_PRIVATECODE2?: string
  DIMENSIONDETAIL_PRIVATECODE3?: string
  DIMENSIONDETAIL_PRIVATECODE4?: string
  DIMENSIONDETAIL_PRIVATECODE5?: string
  DIMENSIONDETAIL_CODENAME?: string
}
