import { DxReport } from '../db/DxReport'

export interface DxReportParameter {
  ID: number
  DXREPORTPARAMETER_SOURCE: string
  DXREPORTPARAMETER_REPORT_ID: number
  DXREPORTPARAMETER_SETMENUDETAIL_ID: number
  DXREPORTPARAMETER_REGDATE: Date
  DXREPORTPARAMETER_REGUSER_ID: number
  DXREPORTPARAMETER_REGIP: string
  DXREPORTPARAMETER_TYPE: string
  DXREPORTPARAMETER_TARGETFIELD: string
  DXREPORTPARAMETER_SOURCEFIELD?: string
  DXREPORTPARAMETER_REPORT?: DxReport
}
