export interface ExchangeParameter {
  ID: number
  EXCHANGEPARAMETER_REGUSER_ID: number
  EXCHANGEPARAMETER_REGDATE: Date
  EXCHANGEPARAMETER_REGIP: string
  EXCHANGEPARAMETER_CORP_ID: number
  EXCHANGEPARAMETER_TYPE: number
  EXCHANGEPARAMETER_EXCHANGETYPE: number
}
