export interface ExpenseDetailPeriod {
  ID: number
  EXPENSEDETAILPERIOD_REGUSER_ID?: number
  EXPENSEDETAILPERIOD_REGDATE?: Date
  EXPENSEDETAILPERIOD_REGIP?: string
  EXPENSEDETAILPERIOD_MASTER_ID: number
  EXPENSEDETAILPERIOD_DETAIL_ID?: number
  EXPENSEDETAILPERIOD_STARTDATE?: Date
  EXPENSEDETAILPERIOD_ENDDATE?: Date
  EXPENSEDETAILPERIOD_DAY?: number
  EXPENSEDETAILPERIOD_AMOUNT?: number
  EXPENSEDETAILPERIOD_ACCEPTEDAMOUNT?: number
  EXPENSEDETAILPERIOD_UNACCEPTEDAMOUNT?: number
  EXPENSEDETAILPERIOD_CURRENTACCOUNT_ID?: number
  EXPENSEDETAILPERIOD_ACCOUNT_ID?: number
  EXPENSEDETAILPERIOD_PERIOD?: number
  EXPENSEDETAILPERIOD_UNACCEPTEDCURRENTACCOUNT_ID?: number
  EXPENSEDETAILPERIOD_UNACCEPTEDACCOUNT_ID?: number
}
