import { ExpenseDemandDetail } from '../db/ExpenseDemandDetail'

export interface ExpenseDemandMaster {
  ID: number
  EXPENSEDEMANDMASTER_CORP_ID: number
  EXPENSEDEMANDMASTER_SECTION_ID: number
  EXPENSEDEMANDMASTER_SERIAL_ID: number
  EXPENSEDEMANDMASTER_YEAR: number
  EXPENSEDEMANDMASTER_NUMBER: number
  EXPENSEDEMANDMASTER_DATE: Date
  EXPENSEDEMANDMASTER_DESCRIPTION?: string
  EXPENSEDEMANDMASTER_DEPARTMENT_ID: number
  EXPENSEDEMANDMASTER_CONFIRM: boolean
  EXPENSEDEMANDMASTER_REGUSER_ID: number
  EXPENSEDEMANDMASTER_REGDATE: Date
  EXPENSEDEMANDMASTER_REGIP: string
  EXPENSEDEMANDMASTER_MANAGERCONFIRM: number
  ExpenseDemandDetail: ExpenseDemandDetail[]
}
