import { ExpenseDemandDetail } from '../db/ExpenseDemandDetail'
import { ExpensePlan } from '../db/ExpensePlan'
import { ExpenseMaster } from '../db/ExpenseMaster'

export interface ExpenseDetail {
  ID: number
  EXPENSEDETAIL_MASTER_ID: number
  EXPENSEDETAIL_EXPENSE_ID: number
  EXPENSEDETAIL_QUANTITY: number
  EXPENSEDETAIL_UNIT_ID: number
  EXPENSEDETAIL_CURRENCY_ID?: number
  EXPENSEDETAIL_CURRENCYPRICE: number
  EXPENSEDETAIL_CURRENCYRATE: number
  EXPENSEDETAIL_CURRENCYAMOUNT: number
  EXPENSEDETAIL_PRICE: number
  EXPENSEDETAIL_AMOUNT: number
  EXPENSEDETAIL_DISCOUNTAMOUNT: number
  EXPENSEDETAIL_VATRATE: number
  EXPENSEDETAIL_VATAMOUNT: number
  EXPENSEDETAIL_WITHHOLDINGAMOUNT: number
  EXPENSEDETAIL_WITHHOLDINGRATE: number
  EXPENSEDETAIL_SCTAMOUNT: number
  EXPENSEDETAIL_SCTRATE: number
  EXPENSEDETAIL_DESCRIPTION?: string
  EXPENSEDETAIL_REALCURRENT_ID?: number
  EXPENSEDETAIL_REALDOCUMENTSERIAL?: string
  EXPENSEDETAIL_REALDOCUMENTNUMBER?: string
  EXPENSEDETAIL_REALDOCUMENTDATE?: Date
  EXPENSEDETAIL_LINK?: string
  EXPENSEDETAIL_REF_ID?: number
  EXPENSEDETAIL_REGUSER_ID: number
  EXPENSEDETAIL_REGDATE: Date
  EXPENSEDETAIL_REGIP: string
  EXPENSEDETAIL_DENIALAMOUNT: number
  EXPENSEDETAIL_DENIALVATAMOUNT: number
  EXPENSEDETAIL_NOTDENIALAMOUNT?: number
  EXPENSEDETAIL_NOTDENIALRATE?: number
  EXPENSEDETAIL_DEPARTMENT_ID: number
  EXPENSEDETAIL_DEMANDDETAIL_ID?: number
  EXPENSEDETAIL_PARAM1_ID?: number
  EXPENSEDETAIL_PARAM2_ID?: number
  EXPENSEDETAIL_PARAM3_ID?: number
  EXPENSEDETAIL_PARAM4_ID?: number
  EXPENSEDETAIL_DEMANDDETAIL?: ExpenseDemandDetail
  EXPENSEDETAIL_EXPENSE?: ExpensePlan
  EXPENSEDETAIL_MASTER?: ExpenseMaster
}
