import { Corporation } from '../db/Corporation'
import { CurrentAccountPlan } from '../db/CurrentAccountPlan'
import { ExpenseDetail } from '../db/ExpenseDetail'

export interface ExpenseMaster {
  ID: number
  EXPENSEMASTER_CORP_ID: number
  EXPENSEMASTER_SECTION_ID: number
  EXPENSEMASTER_YEAR: number
  EXPENSEMASTER_SERIAL_ID: number
  EXPENSEMASTER_NUMBER: number
  EXPENSEMASTER_DATE: Date
  EXPENSEMASTER_CURRENTACCOUNT_ID: number
  EXPENSEMASTER_TYPE_ID: number
  EXPENSEMASTER_PAYMENT_ID?: number
  EXPENSEMASTER_PAYDATE: Date
  EXPENSEMASTER_PAYDAY: number
  EXPENSEMASTER_DESCRIPTION?: string
  EXPENSEMASTER_ACCOUNTING: boolean
  EXPENSEMASTER_CONFIRM: boolean
  EXPENSEMASTER_SUBACCOUNT_ID?: number
  EXPENSEMASTER_DOCUMENTNUMBER: string
  EXPENSEMASTER_DOCUMENTDATE: Date
  EXPENSEMASTER_DOCUMENTSERIAL: string
  EXPENSEMASTER_RETURN: boolean
  EXPENSEMASTER_LINK?: string
  EXPENSEMASTER_REF_ID?: number
  EXPENSEMASTER_REGUSER_ID: number
  EXPENSEMASTER_REGDATE: Date
  EXPENSEMASTER_REGIP: string
  EXPENSEMASTER_CURRENTCONFIRM: boolean
  EXPENSEMASTER_MANAGERCONFIRM: number
  EXPENSEMASTER_CORP?: Corporation
  EXPENSEMASTER_CURRENTACCOUNT?: CurrentAccountPlan
  ExpenseDetail: ExpenseDetail[]
}
