import { Corporation } from '../db/Corporation'

export interface ExpenseParameter {
  ID: number
  EXPENSEPARAMETER_CORP_ID: number
  EXPENSEPARAMETER_LEDGERLENGTH: number
  EXPENSEPARAMETER_GROUP1LENGTH: number
  EXPENSEPARAMETER_GROUP2LENGTH: number
  EXPENSEPARAMETER_GROUP3LENGTH: number
  EXPENSEPARAMETER_GROUP4LENGTH: number
  EXPENSEPARAMETER_REGUSER_ID: number
  EXPENSEPARAMETER_REGDATE: Date
  EXPENSEPARAMETER_REGIP: string
  EXPENSEPARAMETER_CORP?: Corporation
}
