export interface ExpenseDetailParameter {
  ID: number
  EXPENSEDETAILPARAMETER_SQL: string
  EXPENSEDETAILPARAMETER_NAME: string
  EXPENSEDETAILPARAMETER_REGUSER_ID: number
  EXPENSEDETAILPARAMETER_REGDATE: Date
  EXPENSEDETAILPARAMETER_REGIP: string
  EXPENSEDETAILPARAMETER_SEQUENCE: number
}
