export interface ExportExpensePlan {
  ID: number
  EXPORTEXPENSEPLAN_CORP_ID: number
  EXPORTEXPENSEPLAN_NUMBER: number
  EXPORTEXPENSEPLAN_NAME?: string
  EXPORTEXPENSEPLAN_TAXRATE?: number
  EXPORTEXPENSEPLAN_FIXED?: boolean
  EXPORTEXPENSEPLAN_REGUSER_ID?: number
  EXPORTEXPENSEPLAN_REGDATE?: Date
  EXPORTEXPENSEPLAN_REGIP?: string
}
