export interface ExportExpense {
  ID: number
  EXPORTEXPENSE_MASTER_ID?: number
  EXPORTEXPENSE_EXPORTEXPENSEPLAN_ID?: number
  EXPORTEXPENSE_DOCUMENTNUMBER?: string
  EXPORTEXPENSE_DOCUMENTSERIAL?: string
  EXPORTEXPENSE_DOCUMENTDATE?: Date
  EXPORTEXPENSE_CONFIRM?: boolean
  EXPORTEXPENSE_COMPANY_ID?: number
  EXPORTEXPENSE_QUANTITY?: number
  EXPORTEXPENSE_CURRENCY_ID?: number
  EXPORTEXPENSE_CURRENCYRATE?: number
  EXPORTEXPENSE_PRICE?: number
  EXPORTEXPENSE_AMOUNT?: number
  EXPORTEXPENSE_TAXRATE?: number
  EXPORTEXPENSE_TAXAMOUNT?: number
  EXPORTEXPENSE_REGUSER_ID?: number
  EXPORTEXPENSE_REGDATE?: Date
  EXPORTEXPENSE_REGIP?: string
}
