export interface ExportDescription {
  ID: number
  EXPORTDESCRIPTION_MASTER_ID?: number
  EXPORTDESCRIPTION_DESCRIPTION?: string
  EXPORTDESCRIPTION_REGUSER_ID?: number
  EXPORTDESCRIPTION_REGDATE?: Date
  EXPORTDESCRIPTION_REGIP?: string
}
