export interface GroupDefinition {
  ID: number
  GROUPDEFINITION_MASTER_ID?: number
  GROUPDEFINITION_DETAIL_ID?: number
  GROUPDEFINITION_CODE?: string
  GROUPDEFINITION_NAME?: string
  GROUPDEFINITION_TURKCE?: string
  GROUPDEFINITION_ENGLISH?: string
  GROUPDEFINITION_GERMANY?: string
  GROUPDEFINITION_FRENCH?: string
  GROUPDEFINITION_RUSSIAN?: string
  GROUPDEFINITION_ARABIC?: string
  GROUPDEFINITION_GTIP?: string
  GROUPDEFINITION_SUBMASTER_ID?: number
  GROUPDEFINITION_REGUSER_ID?: number
  GROUPDEFINITION_REGDATE?: Date
  GROUPDEFINITION_REGIP?: string
  GROUPDEFINITION_GENERALEXPENSE?: number
}
