export interface ImportExpenseMaster {
  ID: number
  IMPORTEXPENSEMASTER_IMPORTMASTER_ID?: number
  IMPORTEXPENSEMASTER_EXPENSEMASTER_ID?: number
  IMPORTEXPENSEMASTER_TYPE_ID?: number
  IMPORTEXPENSEMASTER_COMPANY_ID?: number
  IMPORTEXPENSEMASTER_DOCUMENTSERIAL?: string
  IMPORTEXPENSEMASTER_DOCUMENTNUMBER?: string
  IMPORTEXPENSEMASTER_DOCUMENTDATE?: Date
  IMPORTEXPENSEMASTER_CURRENCY_ID?: number
  IMPORTEXPENSEMASTER_CURRENCYRATE?: number
  IMPORTEXPENSEMASTER_CURRENCYAMOUNT?: number
  IMPORTEXPENSEMASTER_TAXRATE?: number
  IMPORTEXPENSEMASTER_TAXAMOUNT?: number
  IMPORTEXPENSEMASTER_AMOUNT?: number
  IMPORTEXPENSEMASTER_OPERATIONAMOUNT?: number
  IMPORTEXPENSEMASTER_DESCRIPTION?: string
  IMPORTEXPENSEMASTER_REGUSER_ID?: number
  IMPORTEXPENSEMASTER_REGDATE?: Date
  IMPORTEXPENSEMASTER_REGIP?: string
  IMPORTEXPENSEMASTER_REF_ID?: number
  IMPORTEXPENSEMASTER_LINK?: string
}
