export interface ImportDocument {
  IMPORTDOCUMENT_REGUSER_ID?: number
  IMPORTDOCUMENT_REGDATE?: Date
  IMPORTDOCUMENT_REGIP?: string
  ID: number
  IMPORTDOCUMENT_MASTER_ID?: number
  IMPORTDOCUMENT_DOCUMENT_ID?: number
  IMPORTDOCUMENT_QUANTITY?: number
  IMPORTDOCUMENT_TYPE_ID?: number
  IMPORTDOCUMENT_DESCRIPTION?: string
}
