export interface ImportDetail {
  ID: number
  IMPORTDETAIL_MASTER_ID: number
  IMPORTDETAIL_PURCHASEINVOICEMASTER_ID?: number
  IMPORTDETAIL_DESCRIPTION?: string
  IMPORTDETAIL_REGUSER_ID: number
  IMPORTDETAIL_REGDATE: Date
  IMPORTDETAIL_REGIP: string
}
