export interface ImportDetailSub {
  ID: number
  IMPORTDETAILSUB_CORP_ID: number
  IMPORTDETAILSUB_MASTER_ID: number
  IMPORTDETAILSUB_DETAIL_ID: number
  IMPORTDETAILSUB_PURCHASEMASTER_ID?: number
  IMPORTDETAILSUB_PURCHASEDETAIL_ID?: number
  IMPORTDETAILSUB_ITEM_ID?: number
  IMPORTDETAILSUB_UNIT_ID?: number
  IMPORTDETAILSUB_QUANTITY: number
  IMPORTDETAILSUB_CUSTOMQUANTITY?: number
  IMPORTDETAILSUB_CURRENCY_ID?: number
  IMPORTDETAILSUB_CURRENCYRATE?: number
  IMPORTDETAILSUB_PRICE: number
  IMPORTDETAILSUB_AMOUNT: number
  IMPORTDETAILSUB_COSTPRICE?: number
  IMPORTDETAILSUB_COSTAMOUNT?: number
  IMPORTDETAILSUB_COSTCURRENCYPRICE?: number
  IMPORTDETAILSUB_COSTCURRENCYAMOUNT?: number
  IMPORTDETAILSUB_TLPRICE: number
  IMPORTDETAILSUB_TLAMOUNT: number
  IMPORTDETAILSUB_EXPENSEAMOUNT1?: number
  IMPORTDETAILSUB_EXPENSEAMOUNT2?: number
  IMPORTDETAILSUB_REGUSER_ID: number
  IMPORTDETAILSUB_REGDATE: Date
  IMPORTDETAILSUB_REGIP: string
}
