export interface ItemCost {
  ID: number
  ITEMCOST_CORP_ID?: number
  ITEMCOST_YEAR?: number
  ITEMCOST_MONTH?: number
  ITEMCOST_ITEM_ID?: number
  ITEMCOST_REALPRICE?: number
  ITEMCOST_REALCURPRICE?: number
  ITEMCOST_STDPRICE?: number
  ITEMCOST_STDCURPRICE?: number
  ITEMCOST_EXPPRICE?: number
  ITEMCOST_EXPCURPRICE?: number
  ITEMCOST_EREALPRICE?: number
  ITEMCOST_EREALCURPRICE?: number
  ITEMCOST_ESTDPRICE?: number
  ITEMCOST_ESTDCURPRICE?: number
  ITEMCOST_EEXPPRICE?: number
  ITEMCOST_EEXPCURPRICE?: number
  ITEMCOST_REGUSER_ID?: number
  ITEMCOST_REGDATE?: Date
  ITEMCOST_REGIP?: string
  ITEMCOST_CURRENCY_ID?: number
}
