export interface ItemDemandApprove {
  ID: number
  ITEMDEMANDAPPROVE_ITEMDEMAND_ID?: number
  ITEMDEMANDAPPROVE_GROUPMASTER_ID?: number
  ITEMDEMANDAPPROVE_GROUPDETAIL_ID?: number
  ITEMDEMANDAPPROVE_REGUSER_ID?: number
  ITEMDEMANDAPPROVE_REGDATE?: Date
  ITEMDEMANDAPPROVE_REGIP?: string
}
