export interface ItemDimension {
  ID: number
  ITEMDIMENSION_REGUSER_ID?: number
  ITEMDIMENSION_REGDATE?: Date
  ITEMDIMENSION_REGIP?: string
  ITEMDIMENSION_CORP_ID?: number
  ITEMDIMENSION_ITEM_ID?: number
  ITEMDIMENSION_DIMENSIONMASTER_ID?: number
  ITEMDIMENSION_DIMENSIONDETAIL_ID?: number
  ITEMDIMENSION_OTHERCODE?: string
}
