import { Item } from '../db/Item'

export interface ItemStockControl {
  ID: number
  ITEMSTOCKCONTROL_ITEM_ID: number
  ITEMSTOCKCONTROL_STORE_ID: number
  ITEMSTOCKCONTROL_MINQUANTITY: number
  ITEMSTOCKCONTROL_MAXQUANTITY: number
  ITEMSTOCKCONTROL_CRITICALQUANTITY: number
  ITEMSTOCKCONTROL_REGUSER_ID: number
  ITEMSTOCKCONTROL_REGDATE: Date
  ITEMSTOCKCONTROL_REGIP: string
  ITEMSTOCKCONTROL_ITEM?: Item
}
