export interface MaintenanceDescMachine {
  ID: number
  MAINTENANCEDESCMACHINE_MASTER_ID?: number
  MAINTENANCEDESCMACHINE_PLANTMACHINE_ID?: number
  MAINTENANCEDESCMACHINE_TYPE_ID?: number
  MAINTENANCEDESCMACHINE_REGUSER_ID?: number
  MAINTENANCEDESCMACHINE_REGDATE?: Date
  MAINTENANCEDESCMACHINE_REGIP?: string
}
