export interface MaintenanceDescMaster {
  ID: number
  MAINTENANCEDESCMASTER_CORP_ID?: number
  MAINTENANCEDESCMASTER_SECTION_ID?: number
  MAINTENANCEDESCMASTER_NUMBER?: number
  MAINTENANCEDESCMASTER_NAME?: string
  MAINTENANCEDESCMASTER_FACTORY_ID?: number
  MAINTENANCEDESCMASTER_PERIOD?: number
  MAINTENANCEDESCMASTER_CLOSED?: boolean
  MAINTENANCEDESCMASTER_REGUSER_ID?: number
  MAINTENANCEDESCMASTER_REGDATE?: Date
  MAINTENANCEDESCMASTER_REGIP?: string
}
