export interface MaintenanceWorkSafe {
  ID: number
  MAINTENANCEWORKSAFE_MAINTENANCEMASTER_ID?: number
  MAINTENANCEWORKSAFE_MAINTENANCEORDERMASTER_ID?: number
  MAINTENANCEWORKSAFE_MAINTENANCEORDERWORKSAFE_ID?: number
  MAINTENANCEWORKSAFE_RESULT?: boolean
  MAINTENANCEWORKSAFE_DESCRIPTION?: string
  MAINTENANCEWORKSAFE_REGUSER_ID?: number
  MAINTENANCEWORKSAFE_REGDATE?: Date
  MAINTENANCEWORKSAFE_REGIP?: string
}
