export interface MaintenanceOrderWorkSafe {
  ID: number
  MAINTENANCEORDERWORKSAFE_MAINTENANCEORDERMASTER_ID?: number
  MAINTENANCEORDERWORKSAFE_WORKSAFEMASTER_ID?: number
  MAINTENANCEORDERWORKSAFE_WORKSAFEDETAIL_ID?: number
  MAINTENANCEORDERWORKSAFE_NECESSARY?: boolean
  MAINTENANCEORDERWORKSAFE_DESCRIPTION?: string
  MAINTENANCEORDERWORKSAFE_REGUSER_ID?: number
  MAINTENANCEORDERWORKSAFE_REGDATE?: Date
  MAINTENANCEORDERWORKSAFE_REGIP?: string
}
