export interface MaintenancePerson {
  ID: number
  MAINTENANCEPERSON_MASTER_ID?: number
  MAINTENANCEPERSON_TITLE_ID?: number
  MAINTENANCEPERSON_PERSON_ID?: number
  MAINTENANCEPERSON_REGUSER_ID?: number
  MAINTENANCEPERSON_REGDATE?: Date
  MAINTENANCEPERSON_REGIP?: string
}
