export interface MaintenanceQuality {
  ID: number
  MAINTENANCEQUALITY_MAINTENANCEMASTER_ID?: number
  MAINTENANCEQUALITY_DUSTY?: boolean
  MAINTENANCEQUALITY_DIRTY?: boolean
  MAINTENANCEQUALITY_MACHINEOIL?: boolean
  MAINTENANCEQUALITY_MACHINEPART?: boolean
  MAINTENANCEQUALITY_MAINTENANCEDEVICE?: boolean
  MAINTENANCEQUALITY_GIB?: boolean
  MAINTENANCEQUALITY_METALDUST?: boolean
  MAINTENANCEQUALITY_MACHINEMETALDUST?: boolean
  MAINTENANCEQUALITY_OILCLOTH?: boolean
  MAINTENANCEQUALITY_DESCRIPTION?: string
  MAINTENANCEQUALITY_CONTROLLER_ID?: number
  MAINTENANCEQUALITY_TYPE?: number
  MAINTENANCEQUALITY_REGUSER_ID?: number
  MAINTENANCEQUALITY_REGDATE?: Date
  MAINTENANCEQUALITY_REGIP?: string
}
