export interface MaintenanceOrderMaster {
  ID: number
  MAINTENANCEORDERMASTER_CORP_ID?: number
  MAINTENANCEORDERMASTER_SECTION_ID?: number
  MAINTENANCEORDERMASTER_NUMBER?: number
  MAINTENANCEORDERMASTER_YEAR?: number
  MAINTENANCEORDERMASTER_TYPE_ID?: number
  MAINTENANCEORDERMASTER_DATE?: Date
  MAINTENANCEORDERMASTER_PLANTMACHINETYPE_ID?: number
  MAINTENANCEORDERMASTER_PLANTMACHINE_ID?: number
  MAINTENANCEORDERMASTER_MAINTENANCEDESCMASTER_ID?: number
  MAINTENANCEORDERMASTER_CALLTIME?: string
  MAINTENANCEORDERMASTER_STATUS_ID?: number
  MAINTENANCEORDERMASTER_WORKSAFE?: boolean
  MAINTENANCEORDERMASTER_WORKSAFEDESC1?: string
  MAINTENANCEORDERMASTER_WORKSAFEDESC2?: string
  MAINTENANCEORDERMASTER_DESCRIPTION?: string
  MAINTENANCEORDERMASTER_REGUSER_ID?: number
  MAINTENANCEORDERMASTER_REGDATE?: Date
  MAINTENANCEORDERMASTER_REGIP?: string
  MAINTENANCEORDERMASTER_PRIORITY_ID?: number
  MAINTENANCEORDERMASTER_DEADLINEDATE?: Date
  MAINTENANCEORDERMASTER_STATUSDATE?: Date
}
