export interface MaintenanceDetail {
  ID: number
  MAINTENANCEDETAIL_MAINTENANCEMASTER_ID?: number
  MAINTENANCEDETAIL_COMPANY_ID?: number
  MAINTENANCEDETAIL_TYPE_ID?: number
  MAINTENANCEDETAIL_PIECE_ID?: number
  MAINTENANCEDETAIL_PIECEDESCRIPTION?: string
  MAINTENANCEDETAIL_QUANTITY?: number
  MAINTENANCEDETAIL_PRICE?: number
  MAINTENANCEDETAIL_AMOUNT?: number
  MAINTENANCEDETAIL_DESCRIPTION?: string
  MAINTENANCEDETAIL_RESULT?: string
  MAINTENANCEDETAIL_FINISHED?: boolean
  MAINTENANCEDETAIL_MAINTENANCEORDERDETAIL_ID?: number
  MAINTENANCEDETAIL_MAINTENANCEDESCDETAIL_ID?: number
  MAINTENANCEDETAIL_REGUSER_ID?: number
  MAINTENANCEDETAIL_REGDATE?: Date
  MAINTENANCEDETAIL_REGIP?: string
}
