import { Item } from '../db/Item'

export interface MaterialAnalysis {
  ID: number
  MATERIALANALYSIS_NO: string
  MATERIALANALYSIS_SUPPLIERNO?: string
  MATERIALANALYSIS_DATE: Date
  MATERIALANALYSIS_MG?: number
  MATERIALANALYSIS_SI?: number
  MATERIALANALYSIS_FE?: number
  MATERIALANALYSIS_CU?: number
  MATERIALANALYSIS_ZN?: number
  MATERIALANALYSIS_MN?: number
  MATERIALANALYSIS_TI?: number
  MATERIALANALYSIS_CR?: number
  MATERIALANALYSIS_AL?: number
  MATERIALANALYSIS_OTHER?: number
  MATERIALANALYSIS_ITEM_ID: number
  MATERIALANALYSIS_REGDATE: Date
  MATERIALANALYSIS_REGIP: string
  MATERIALANALYSIS_REGUSER_ID: number
  MATERIALANALYSIS_ITEM?: Item
}
