export interface MaterialDemandMaster {
  ID: number
  MATERIALDEMANDMASTER_CORP_ID?: number
  MATERIALDEMANDMASTER_SECTION_ID?: number
  MATERIALDEMANDMASTER_YEAR: number
  MATERIALDEMANDMASTER_NUMBER?: number
  MATERIALDEMANDMASTER_DATE: Date
  MATERIALDEMANDMASTER_DEPARTMENT_ID?: number
  MATERIALDEMANDMASTER_CONFIRM?: boolean
  MATERIALDEMANDMASTER_REGUSER_ID?: number
  MATERIALDEMANDMASTER_REGDATE?: Date
  MATERIALDEMANDMASTER_REGIP?: string
}
