export interface MaterialDemandDetail {
  ID: number
  MATERIALDEMANDDETAIL_MASTER_ID?: number
  MATERIALDEMANDDETAIL_ITEM_ID?: number
  MATERIALDEMANDDETAIL_QUANTITY?: number
  MATERIALDEMANDDETAIL_UNIT_ID?: number
  MATERIALDEMANDDETAIL_EXPENSEPLAN_ID?: number
  MATERIALDEMANDDETAIL_DESCRIPTION?: string
  MATERIALDEMANDDETAIL_REGUSER_ID?: number
  MATERIALDEMANDDETAIL_REGDATE?: Date
  MATERIALDEMANDDETAIL_REGIP?: string
}
