export interface MaterialDemandDetailSub {
  ID: number
  MATERIALDEMANDDETAILSUB_MASTER_ID?: number
  MATERIALDEMANDDETAILSUB_DETAIL_ID?: number
  MATERIALDEMANDDETAILSUB_TYPE_ID?: number
  MATERIALDEMANDDETAILSUB_DEFINITION_ID?: number
  MATERIALDEMANDDETAILSUB_REGUSER_ID?: number
  MATERIALDEMANDDETAILSUB_REGDATE?: Date
  MATERIALDEMANDDETAILSUB_REGIP?: string
}
