export interface ModuleControl {
  ID: number
  MODULECONTROL_CORP_ID: number
  MODULECONTROL_SECTION_ID: number
  MODULECONTROL_DATE: Date
  MODULECONTROL_SALES: boolean
  MODULECONTROL_PURCHASE: boolean
  MODULECONTROL_STOCK: boolean
  MODULECONTROL_CASH: boolean
  MODULECONTROL_BANK: boolean
  MODULECONTROL_EXPENSE: boolean
  MODULECONTROL_CHECK: boolean
  MODULECONTROL_SALESRETURN: boolean
  MODULECONTROL_PURCHASERETURN: boolean
  MODULECONTROL_CURRENTACCOUNT: boolean
  MODULECONTROL_PRODUCTION: boolean
  MODULECONTROL_ACCOUNT: boolean
  MODULECONTROL_ACCCOST: boolean
  MODULECONTROL_REGUSER_ID: number
  MODULECONTROL_REGDATE: Date
  MODULECONTROL_REGIP: string
}
