export interface ModuleDescription {
  ID: number
  MODULEDESCRIPTION_TEXT?: string
  MODULEDESCRIPTION_TYPE_ID?: number
  MODULEDESCRIPTION_LANGUAGE_ID?: number
  MODULEDESCRIPTION_REGUSER_ID?: number
  MODULEDESCRIPTION_REGDATE?: Date
  MODULEDESCRIPTION_REGIP?: string
}
