import { Mold } from '../db/Mold'
import { PlantMaster } from '../db/PlantMaster'

export interface MoldPress {
  ID: number
  MOLDPRESS_ORDER: number
  MOLDPRESS_OVENTEMP?: number
  MOLDPRESS_OVENTEMPTOP?: number
  MOLDPRESS_OVENTEMPBOTTOM?: number
  MOLDPRESS_HOURQUANTITY?: number
  MOLDPRESS_QUITTEMP?: number
  MOLDPRESS_QUITTEMPTOP?: number
  MOLDPRESS_QUITTEMPBOTTOM?: number
  MOLDPRESS_SIZE?: number
  MOLDPRESS_SIZETOP?: number
  MOLDPRESS_SIZEBOTTOM?: number
  MOLDPRESS_WEDGEHEAD?: number
  MOLDPRESS_WEDGEHEADTOP?: number
  MOLDPRESS_WEDGEHEADBOTTOM?: number
  MOLDPRESS_SAWDIST?: number
  MOLDPRESS_SAWDISTTOP?: number
  MOLDPRESS_SAWDISTBOTTOM?: number
  MOLDPRESS_BEGINSCRAP?: number
  MOLDPRESS_ENDSCRAP?: number
  MOLDPRESS_TUNNELFANSPEED?: number
  MOLDPRESS_TUNNELFANSPEEDTOP?: number
  MOLDPRESS_TUNNELFANSPEEDBOTTOM?: number
  MOLDPRESS_CONVEYORFANSPEED?: number
  MOLDPRESS_CONVEYORFANSPEEDTOP?: number
  MOLDPRESS_CONVEYORFANSPEEDBOTTOM?: number
  MOLDPRESS_STAPLESPEED?: number
  MOLDPRESS_STAPLESPEEDTOP?: number
  MOLDPRESS_STAPLESPEEDBOTTOM?: number
  MOLDPRESS_MOLD_ID: number
  MOLDPRESS_REGUSER_ID: number
  MOLDPRESS_REGDATE: Date
  MOLDPRESS_REGIP: string
  MOLDPRESS_PLANTMASTER_ID: number
  MOLDPRESS_MOLDTEMP?: number
  MOLDPRESS_MOLDTEMPTOP?: number
  MOLDPRESS_MOLDTEMPBOTTOM?: number
  MOLDPRESS_HIVETEMP?: number
  MOLDPRESS_HIVETEMPTOP?: number
  MOLDPRESS_HIVETEMPBOTTOM?: number
  MOLDPRESS_EXTRUSIONRATE?: number
  MOLDPRESS_AREA?: number
  MOLDPRESS_DIAMETER?: number
  MOLDPRESS_BARREL?: string
  MOLDPRESS_MOLD?: Mold
  MOLDPRESS_PLANTMASTER?: PlantMaster
}
