import { PlantMaster } from '../db/PlantMaster'
import { MoldDemandDetail } from '../db/MoldDemandDetail'

export interface MoldDemandMaster {
  ID: number
  MOLDDEMANDMASTER_CORP_ID: number
  MOLDDEMANDMASTER_DATE: Date
  MOLDDEMANDMASTER_NUMBER: number
  MOLDDEMANDMASTER_COMPANY_ID?: number
  MOLDDEMANDMASTER_RETAILCOMPANYNAME?: string
  MOLDDEMANDMASTER_USER_ID: number
  MOLDDEMANDMASTER_DESC?: string
  MOLDDEMANDMASTER_CONFIRM: boolean
  MOLDDEMANDMASTER_REGDATE: Date
  MOLDDEMANDMASTER_REGIP: string
  MOLDDEMANDMASTER_REGUSER_ID: number
  MOLDDEMANDMASTER_IMAGENO?: string
  MOLDDEMANDMASTER_AREA?: number
  MOLDDEMANDMASTER_PERIMETER?: number
  MOLDDEMANDMASTER_WEIGTH?: number
  MOLDDEMANDMASTER_PLANTMASTER_ID?: number
  MOLDDEMANDMASTER_FIGURECOUNT?: number
  MOLDDEMANDMASTER_EXTRUSIONRATE?: number
  MOLDDEMANDMASTER_DUVALUE?: number
  MOLDDEMANDMASTER_FORMFACTOR?: number
  MOLDDEMANDMASTER_SHAPEFACTOR?: number
  MOLDDEMANDMASTER_EXTRUSIONSPEED?: number
  MOLDDEMANDMASTER_WASTAGE?: number
  MOLDDEMANDMASTER_QUANTITY?: number
  MOLDDEMANDMASTER_EFFICIENCY?: number
  MOLDDEMANDMASTER_DIMENSIONS?: string
  MOLDDEMANDMASTER_PRICE: number
  MOLDDEMANDMASTER_CURRENCY_ID?: number
  MOLDDEMANDMASTER_VAT: boolean
  MOLDDEMANDMASTER_DELIVERYDATE?: Date
  MOLDDEMANDMASTER_SAMPLEDATE?: Date
  MOLDDEMANDMASTER_PLANCONFIRM?: number
  MOLDDEMANDMASTER_MANAGERCONFIRM?: number
  MOLDDEMANDMASTER_PROFILEGROUP_ID?: number
  MOLDDEMANDMASTER_PROFILELENGTH?: string
  MOLDDEMANDMASTER_REFNO?: string
  MOLDDEMANDMASTER_FUNCDESC?: string
  MOLDDEMANDMASTER_SALESQUANTITY?: number
  MOLDDEMANDMASTER_YEARQUANTITY?: number
  MOLDDEMANDMASTER_BOLSTERDIMENSIONS?: string
  MOLDDEMANDMASTER_BOLSTERPRICE: number
  MOLDDEMANDMASTER_BOLSTERVAT: boolean
  MOLDDEMANDMASTER_BOLSTERCURRENCY_ID?: number
  MOLDDEMANDMASTER_PLANTMASTER?: PlantMaster
  MoldDemandDetail: MoldDemandDetail[]
}
