export interface PalletMaster {
  ID: number
  PALLETMASTER_CORP_ID: number
  PALLETMASTER_SECTION_ID: number
  PALLETMASTER_YEAR: number
  PALLETMASTER_SERIAL_ID: number
  PALLETMASTER_NUMBER: number
  PALLETMASTER_COMPANY_ID?: number
  PALLETMASTER_DATE: Date
  PALLETMASTER_REGUSER_ID: number
  PALLETMASTER_REGDATE: Date
  PALLETMASTER_REGIP: string
  PALLETMASTER_INSTRUCTIONMASTER_ID?: number
  PALLETMASTER_PLANTMASTER_ID?: number
  PALLETMASTER_DESCRIPTION?: string
  PALLETMASTER_TYPE_ID: number
  PALLETMASTER_PLANT_ID?: number
  PALLETMASTER_DOCUMENTDATE?: Date
  PALLETMASTER_DOCUMENTNUMBER?: string
  PALLETMASTER_KIND?: number
  PALLETMASTER_LINK?: string
  PALLETMASTER_REF_ID?: number
  PALLETMASTER_PURCHASEMASTER_ID?: number
  PALLETMASTER_SALESMASTER_ID?: number
  PALLETMASTER_STOCKMASTER_ID?: number
}
