export interface PalletDetail {
  ID: number
  PALLETDETAIL_MASTER_ID: number
  PALLETDETAIL_NUMBER?: string
  PALLETDETAIL_WIDTH?: number
  PALLETDETAIL_LENGTH?: number
  PALLETDETAIL_HEIGHT?: number
  PALLETDETAIL_WEIGHT?: number
  PALLETDETAIL_REGUSER_ID: number
  PALLETDETAIL_REGDATE: Date
  PALLETDETAIL_REGIP: string
  PALLETDETAIL_GROSSWEIGHT?: number
  PALLETDETAIL_QUANTITY?: number
  PALLETDETAIL_LOTNUMBER?: string
  PALLETDETAIL_ITEM_ID?: number
  PALLETDETAIL_PIECE?: number
  PALLETDETAIL_UNIT_ID?: number
  PALLETDETAIL_PLANT_ID?: number
  PALLETDETAIL_LINK?: string
  PALLETDETAIL_REF_ID?: number
  PALLETDETAIL_BARCODE_ID: number
}
