export interface PalletDetailSub {
  ID: number
  PALLETDETAILSUB_MASTER_ID: number
  PALLETDETAILSUB_DETAIL_ID: number
  PALLETDETAILSUB_WIDTH: number
  PALLETDETAILSUB_HEIGHT: number
  PALLETDETAILSUB_LENGTH: number
  PALLETDETAILSUB_QUANTITY: number
  PALLETDETAILSUB_BARCODE_ID: number
  PALLETDETAILSUB_REGDATE: Date
  PALLETDETAILSUB_REGUSER_ID: number
  PALLETDETAILSUB_REGIP: string
  PALLETDETAILSUB_LINK?: string
  PALLETDETAILSUB_REF_ID?: number
}
