export interface PaymentDetail {
  ID: number
  PAYMENTDETAIL_MASTER_ID?: number
  PAYMENTDETAIL_CURRENTACCOUNT_ID?: number
  PAYMENTDETAIL_SUBACCOUNT_ID?: number
  PAYMENTDETAIL_TYPE_ID?: number
  PAYMENTDETAIL_DESCRIPTION?: string
  PAYMENTDETAIL_AMOUNT?: number
  PAYMENTDETAIL_CURRENCY_ID?: number
  PAYMENTDETAIL_CURRECYAMOUNT?: number
  PAYMENTDETAIL_CURRENCYRATE?: number
  PAYMENTDETAIL_CREDITAMOUNT?: number
  PAYMENTDETAIL_DOCUMENTDATE?: Date
  PAYMENTDETAIL_PAYMENTDATE?: Date
  PAYMENTDETAIL_CONFIRM?: boolean
  PAYMENTDETAIL_LINK?: string
  PAYMENTDETAIL_REF_ID?: number
  PAYMENTDETAIL_REGUSER_ID?: number
  PAYMENTDETAIL_REGDATE?: Date
  PAYMENTDETAIL_REGIP?: string
}
