export interface PaymentMaster {
  ID: number
  PAYMENTMASTER_CORP_ID?: number
  PAYMENTMASTER_SECTION_ID?: number
  PAYMENTMASTER_YEAR: number
  PAYMENTMASTER_SERIAL_ID?: number
  PAYMENTMASTER_NUMBER: number
  PAYMENTMASTER_DATE: Date
  PAYMENTMASTER_CLOSED?: boolean
  PAYMENTMASTER_REGUSER_ID?: number
  PAYMENTMASTER_REGDATE?: Date
  PAYMENTMASTER_REGIP?: string
  PAYMENTMASTER_BANKACCOUNT_ID?: number
  PAYMENTMASTER_CURRENTCONFIRM?: boolean
  PAYMENTMASTER_FORCASHFLOW?: boolean
}
