export interface PlantCapacityDetail {
  ID: number
  PLANTCAPACITYDETAIL_MASTER_ID?: number
  PLANTCAPACITYDETAIL_PLANTMACHINE_ID?: number
  PLANTCAPACITYDETAIL_ORDER?: number
  PLANTCAPACITYDETAIL_REGUSER_ID?: number
  PLANTCAPACITYDETAIL_REGDATE?: Date
  PLANTCAPACITYDETAIL_REGIP?: string
}
