export interface PlantCapacity {
  ID: number
  PLANTCAPACITY_PLANTMASTER_ID?: number
  PLANTCAPACITY_CORP_ID?: number
  PLANTCAPACITY_SECTION_ID?: number
  PLANTCAPACITY_ITEM_ID?: number
  PLANTCAPACITY_CAPACITY?: number
  PLANTCAPACITY_ALTERNATIVE?: boolean
  PLANTCAPACITY_PERSONCOUNT?: number
  PLANTCAPACITY_WORKGROUP_ID?: number
  PLANTCAPACITY_BARCODEPRINTTIME?: number
  PLANTCAPACITY_REGUSER_ID?: number
  PLANTCAPACITY_REGDATE?: Date
  PLANTCAPACITY_REGIP?: string
  PLANTCAPACITY_NUMBER?: string
  PLANTCAPACITY_DESCRIPTION?: string
  PLANTCAPACITY_SETTINGTIME?: number
  PLANTCAPACITY_UNIT_ID?: number
}
