export interface ProcessAnalysisDetail {
  ID: number
  PROCESSANALYSISDETAIL_MASTER_ID?: number
  PROCESSANALYSISDETAIL_NUMBER?: number
  PROCESSANALYSISDETAIL_GROUP_ID?: number
  PROCESSANALYSISDETAIL_PH?: number
  PROCESSANALYSISDETAIL_FAT?: number
  PROCESSANALYSISDETAIL_PROTEIN?: number
  PROCESSANALYSISDETAIL_LAKTOZ?: number
  PROCESSANALYSISDETAIL_YKM?: number
  PROCESSANALYSISDETAIL_TKM?: number
  PROCESSANALYSISDETAIL_FATTKM?: number
  PROCESSANALYSISDETAIL_BRIX?: number
  PROCESSANALYSISDETAIL_SALT?: number
  PROCESSANALYSISDETAIL_ASH?: number
  PROCESSANALYSISDETAIL_REGUSER_ID?: number
  PROCESSANALYSISDETAIL_REGDATE?: Date
  PROCESSANALYSISDETAIL_REGIP?: string
}
