export interface ProcessAnalysisMaster {
  ID: number
  PROCESSANALYSISMASTER_CORP_ID?: number
  PROCESSANALYSISMASTER_SECTION_ID?: number
  PROCESSANALYSISMASTER_YEAR?: number
  PROCESSANALYSISMASTER_SERIAL_ID?: number
  PROCESSANALYSISMASTER_NUMBER?: number
  PROCESSANALYSISMASTER_DATE?: Date
  PROCESSANALYSISMASTER_TYPE_ID?: number
  PROCESSANALYSISMASTER_DESCRIPTION?: string
  PROCESSANALYSISMASTER_REGUSER_ID?: number
  PROCESSANALYSISMASTER_REGDATE?: Date
  PROCESSANALYSISMASTER_REGIP?: string
}
