import { ProductionOrderDetail } from '../db/ProductionOrderDetail'
import { ProductionProgDetail } from '../db/ProductionProgDetail'

export interface ProductionOrderDetailSub {
  ID: number
  PRODUCTIONORDERDETAILSUB_DETAIL_ID: number
  PRODUCTIONORDERDETAILSUB_REGDATE: Date
  PRODUCTIONORDERDETAILSUB_REGIP: string
  PRODUCTIONORDERDETAILSUB_REGUSER_ID: number
  PRODUCTIONORDERDETAILSUB_SEQUENCE: number
  PRODUCTIONORDERDETAILSUB_PLANT_ID: number
  PRODUCTIONORDERDETAILSUB_DELIVERYDATE?: Date
  PRODUCTIONORDERDETAILSUB_MARGIN: number
  PRODUCTIONORDERDETAILSUB_PIECE: number
  PRODUCTIONORDERDETAILSUB_QUANTITY: number
  PRODUCTIONORDERDETAILSUB_CLOSED: boolean
  PRODUCTIONORDERDETAILSUB_SHORTPIECE: number
  PRODUCTIONORDERDETAILSUB_LENGTH: number
  PRODUCTIONORDERDETAILSUB_DETAIL?: ProductionOrderDetail
  ProductionProgDetail: ProductionProgDetail[]
}
