export interface ProductionPerson {
  ID: number
  PRODUCTIONPERSON_MASTER_ID?: number
  PRODUCTIONPERSON_SHIFTCHIEF_ID?: number
  PRODUCTIONPERSON_MACHINEOPERATOR_ID?: number
  PRODUCTIONPERSON_PACKINGOPERATOR_ID?: number
  PRODUCTIONPERSON_SHIFTENGINEER_ID?: number
  PRODUCTIONPERSON_PERSONTITLE_ID?: number
  PRODUCTIONPERSON_PERSON_ID?: number
  PRODUCTIONPERSON_REGUSER_ID?: number
  PRODUCTIONPERSON_REGDATE?: Date
  PRODUCTIONPERSON_REGIP?: string
}
