export interface ProductionProgPlanMaster {
  ID: number
  PRODUCTIONPROGPLANMASTER_CORP_ID?: number
  PRODUCTIONPROGPLANMASTER_SECTION_ID?: number
  PRODUCTIONPROGPLANMASTER_YEAR?: number
  PRODUCTIONPROGPLANMASTER_NUMBER?: number
  PRODUCTIONPROGPLANMASTER_TYPE_ID?: number
  PRODUCTIONPROGPLANMASTER_KIND_ID?: number
  PRODUCTIONPROGPLANMASTER_FACTORY_ID?: number
  PRODUCTIONPROGPLANMASTER_SHIFT_ID?: number
  PRODUCTIONPROGPLANMASTER_DATE?: Date
  PRODUCTIONPROGPLANMASTER_CONFIRM?: boolean
  PRODUCTIONPROGPLANMASTER_CONFIRMUSER_ID?: number
  PRODUCTIONPROGPLANMASTER_REGUSER_ID?: number
  PRODUCTIONPROGPLANMASTER_REGDATE?: Date
  PRODUCTIONPROGPLANMASTER_REGIP?: string
  PRODUCTIONPROGPLANMASTER_PLANTMASTER_ID?: number
  PRODUCTIONPROGPLANMASTER_PLANTMACHINE_ID?: number
  PRODUCTIONPROGPLANMASTER_DESCRIPTION?: string
}
