export interface ProductionProgDetailSub {
  ID: number
  PRODUCTIONPROGDETAILSUB_MASTER_ID?: number
  PRODUCTIONPROGDETAILSUB_DETAIL_ID?: number
  PRODUCTIONPROGDETAILSUB_BOMMASTER_ID?: number
  PRODUCTIONPROGDETAILSUB_ITEM_ID?: number
  PRODUCTIONPROGDETAILSUB_UNIT_ID?: number
  PRODUCTIONPROGDETAILSUB_QUANTITY?: number
  PRODUCTIONPROGDETAILSUB_MASTERQUANTITY?: number
  PRODUCTIONPROGDETAILSUB_REGUSER_ID?: number
  PRODUCTIONPROGDETAILSUB_REGDATE?: Date
  PRODUCTIONPROGDETAILSUB_REGIP?: string
}
