export interface ProductionAutoInfo {
  ID: number
  PRODUCTIONAUTOINFO_NUMBER?: number
  PRODUCTIONAUTOINFO_DATE?: Date
  PRODUCTIONAUTOINFO_DETAIL?: string
  PRODUCTIONAUTOINFO_REGUSER_ID?: number
  PRODUCTIONAUTOINFO_REGDATE?: Date
  PRODUCTIONAUTOINFO_REGIP?: string
}
