export interface ProductionBonusDetail {
  ID: number
  PRODUCTIONBONUSDETAIL_MASTER_ID?: number
  PRODUCTIONBONUSDETAIL_PRODUCTIONORDERDETAIL_ID?: number
  PRODUCTIONBONUSDETAIL_PRODUCTIONQUANTITY?: number
  PRODUCTIONBONUSDETAIL_PIECE?: number
  PRODUCTIONBONUSDETAIL_QUANTITY?: number
  PRODUCTIONBONUSDETAIL_TOTALQUANTITY?: number
  PRODUCTIONBONUSDETAIL_PRICE?: number
  PRODUCTIONBONUSDETAIL_AMOUNT?: number
  PRODUCTIONBONUSDETAIL_PLANTMASTER_ID?: number
  PRODUCTIONBONUSDETAIL_DESCRIPTION?: string
  PRODUCTIONBONUSDETAIL_REGUSER_ID?: number
  PRODUCTIONBONUSDETAIL_REGDATE?: Date
  PRODUCTIONBONUSDETAIL_REGIP?: string
}
