export interface ProductionPlant {
  ID: number
  PRODUCTIONPLANT_MASTER_ID?: number
  PRODUCTIONPLANT_PLANTMASTER_ID?: number
  PRODUCTIONPLANT_PLANTMACHINE_ID?: number
  PRODUCTIONPLANT_REGUSER_ID?: number
  PRODUCTIONPLANT_REGDATE?: Date
  PRODUCTIONPLANT_REGIP?: string
}
