export interface ProductionBonusMaster {
  ID: number
  PRODUCTIONBONUSMASTER_CORP_ID?: number
  PRODUCTIONBONUSMASTER_SECTION_ID?: number
  PRODUCTIONBONUSMASTER_SERIAL_ID?: number
  PRODUCTIONBONUSMASTER_YEAR?: number
  PRODUCTIONBONUSMASTER_NUMBER?: number
  PRODUCTIONBONUSMASTER_DATE?: Date
  PRODUCTIONBONUSMASTER_DESCRIPTION?: string
  PRODUCTIONBONUSMASTER_REGUSER_ID?: number
  PRODUCTIONBONUSMASTER_REGDATE?: Date
  PRODUCTIONBONUSMASTER_REGIP?: string
}
