export interface ProductionStopDetail {
  ID: number
  PRODUCTIONSTOPDETAIL_MASTER_ID?: number
  PRODUCTIONSTOPDETAIL_CODE?: string
  PRODUCTIONSTOPDETAIL_NAME?: string
  PRODUCTIONSTOPDETAIL_REGUSER_ID?: number
  PRODUCTIONSTOPDETAIL_REGDATE?: Date
  PRODUCTIONSTOPDETAIL_REGIP?: string
}
