export interface ProductionOrderChemDetailDough {
  ID: number
  PRODUCTIONORDERCHEMDETAILDOUGH_REGUSER_ID?: number
  PRODUCTIONORDERCHEMDETAILDOUGH_REGDATE?: Date
  PRODUCTIONORDERCHEMDETAILDOUGH_REGIP?: string
  PRODUCTIONORDERCHEMDETAILDOUGH_MASTER_ID?: number
  PRODUCTIONORDERCHEMDETAILDOUGH_DETAIL_ID?: number
  PRODUCTIONORDERCHEMDETAILDOUGH_TYPE?: number
  PRODUCTIONORDERCHEMDETAILDOUGH_ITEM_ID?: number
  PRODUCTIONORDERCHEMDETAILDOUGH_UNIT_ID?: number
  PRODUCTIONORDERCHEMDETAILDOUGH_QUANTITY?: number
  PRODUCTIONORDERCHEMDETAILDOUGH_SUBITEM_ID?: number
  PRODUCTIONORDERCHEMDETAILDOUGH_SUBUNIT_ID?: number
}
