export interface ProductionOrderStore {
  ID: number
  PRODUCTIONORDERSTORE_SECTION_ID?: number
  PRODUCTIONORDERSTORE_STORE_ID?: number
  PRODUCTIONORDERSTORE_DESCRIPTION?: string
  PRODUCTIONORDERSTORE_REGUSER_ID?: number
  PRODUCTIONORDERSTORE_REGDATE?: Date
  PRODUCTIONORDERSTORE_REGIP?: string
}
