export interface ProductionSetupStopDay {
  ID: number
  PRODUCTIONSETUPSTOPDAY_DATE?: Date
  PRODUCTIONSETUPSTOPDAY_INFO?: string
  PRODUCTIONSETUPSTOPDAY_REPEAT?: boolean
  PRODUCTIONSETUPSTOPDAY_PLANT_ID?: number
  PRODUCTIONSETUPSTOPDAY_SHIFT_ID?: number
  PRODUCTIONSETUPSTOPDAY_REGUSER_ID?: string
  PRODUCTIONSETUPSTOPDAY_REGDATE?: Date
  PRODUCTIONSETUPSTOPDAY_REGIP?: string
}
