import { ProductionDetail } from '../db/ProductionDetail'
import { ProductionMold } from '../db/ProductionMold'

export interface ProductionDetailSub {
  ID: number
  PRODUCTIONDETAILSUB_DETAIL_ID?: number
  PRODUCTIONDETAILSUB_ITEM_ID: number
  PRODUCTIONDETAILSUB_UNIT_ID: number
  PRODUCTIONDETAILSUB_QUANTITY: number
  PRODUCTIONDETAILSUB_REGUSER_ID: number
  PRODUCTIONDETAILSUB_REGDATE: Date
  PRODUCTIONDETAILSUB_REGIP: string
  PRODUCTIONDETAILSUB_PIECE: number
  PRODUCTIONDETAILSUB_LENGTH: number
  PRODUCTIONDETAILSUB_PRODUCTIONMOLD_ID?: number
  PRODUCTIONDETAILSUB_DIAMETER?: number
  PRODUCTIONDETAILSUB_LOTNUMBER?: string
  PRODUCTIONDETAILSUB_DETAIL?: ProductionDetail
  PRODUCTIONDETAILSUB_PRODUCTIONMOLD?: ProductionMold
}
