export interface ProductionEquipment {
  ID: number
  PRODUCTIONEQUIPMENT_EQUIPMENT_ID?: number
  PRODUCTIONEQUPMENT_MASTER_ID?: number
  PRODUCTIONEQUIPMENT_DETAIL_ID?: number
  PRODUCTIONEQUIPMENT_PASSQUANTITY?: number
  PRODUCTIONEQUIPMENT_ADDQUANTITY?: number
  PRODUCTIONEQUIPMENT_USEQUANTITY?: number
  PRODUCTIONEQUIPMENT_METRAJ?: number
  PRODUCTIONEQUIPMENT_REGUSER_ID?: number
  PRODUCTIONEQUIPMENT_REGDATE?: Date
  PRODUCTIONEQUIPMENT_REGIP?: string
  PRODUCTIONEQUPMENT_DESCRIPTION?: string
}
