export interface ProductionPlanDetailSub {
  ID: number
  PRODUCTIONPLANDETAILSUB_REGDATE?: Date
  PRODUCTIONPLANDETAILSUB_REGIP?: string
  PRODUCTIONPLANDETAILSUB_REGUSER_ID?: number
  PRODUCTIONPLANDETAILSUB_MASTER_ID?: number
  PRODUCTIONPLANDETAILSUB_DETAIL_ID?: number
  PRODUCTIONPLANDETAILSUB_STEPNUMBER?: number
  PRODUCTIONPLANDETAILSUB_SALESORDERDETAIL_ID?: number
  PRODUCTIONPLANDETAILSUB_PLANTMASTER_ID?: number
  PRODUCTIONPLANDETAILSUB_PLANTMACHINE_ID?: number
  PRODUCTIONPLANDETAILSUB_PLANNINGDATE?: Date
  PRODUCTIONPLANDETAILSUB_PLANNINGQUANTITY?: number
  PRODUCTIONPLANDETAILSUB_PLANNINGTIME?: number
}
