export interface ProductionPersonSection {
  ID: number
  PRODUCTIONPERSONSECTION_REGUSER_ID?: number
  PRODUCTIONPERSONSECTION_REGDATE?: Date
  PRODUCTIONPERSONSECTION_REGIP?: string
  PRODUCTIONPERSONSECTION_USER_ID?: number
  PRODUCTIONPERSONSECTION_SECTION_ID?: number
  PRODUCTIONPERSONSECTION_INFORMATION?: string
}
