export interface ProductionLimit {
  ID: number
  PRODUCTIONLIMIT_YEAR?: number
  PRODUCTIONLIMIT_TYPE?: number
  PRODUCTIONLIMIT_PLANT_ID?: number
  PRODUCTIONLIMIT_1ITEM_ID?: number
  PRODUCTIONLIMIT_2ITEM_ID?: number
  PRODUCTIONLIMIT_1GROUP_ID?: number
  PRODUCTIONLIMIT_2GROUP_ID?: number
  PRODUCTIONLIMIT_REGUSER_ID?: number
  PRODUCTIONLIMIT_REGDATE?: Date
  PRODUCTIONLIMIT_REGIP?: string
}
