export interface ProductionSetup {
  ID: number
  PRODUCTIONSETUP_YEAR?: number
  PRODUCTIONSETUP_CORP_ID?: number
  PRODUCTIONSETUP_SECTION_ID?: number
  PRODUCTIONSETUP_WEEKNUMBER?: number
  PRODUCTIONSETUP_WORKDAY?: Date
  PRODUCTIONSETUP_PLANTMASTER_ID?: number
  PRODUCTIONSETUP_SHIFT_ID?: number
  PRODUCTIONSETUP_PERSONCOUNT?: number
  PRODUCTIONSETUP_REGUSER_ID?: number
  PRODUCTIONSETUP_REGDATE?: Date
  PRODUCTIONSETUP_REGIP?: string
}
