export interface ProductionStopMaster {
  ID: number
  PRODUCTIONSTOPMASTER_CORP_ID?: number
  PRODUCTIONSTOPMASTER_CODE?: string
  PRODUCTIONSTOPMASTER_NAME?: string
  PRODUCTIONSTOPMASTER_REGUSER_ID?: number
  PRODUCTIONSTOPMASTER_REGDATE?: Date
  PRODUCTIONSTOPMASTER_REGIP?: string
}
