export interface ProductionOrderMrp {
  ID: number
  PRODUCTIONORDERMRP_REGUSER_ID?: number
  PRODUCTIONORDERMRP_REGDATE?: Date
  PRODUCTIONORDERMRP_REGIP?: string
  PRODUCTIONORDERMRP_SALESORDERDETAIL_ID?: number
  PRODUCTIONORDERMRP_ITEM_ID?: number
  PRODUCTIONORDERMRP_MATERIAL_ID?: number
  PRODUCTIONORDERMRP_UNIT_ID?: number
  PRODUCTIONORDERMRP_QUANTITY?: number
  PRODUCTIONORDERMRP_PROCESS?: number
  PRODUCTIONORDERMRP_PRICE?: number
  PRODUCTIONORDERMRP_AMOUNT?: number
  PRODUCTIONORDERMRP_CURRENCYPRICE?: number
  PRODUCTIONORDERMRP_CURRENCYAMOUNT?: number
  PRODUCTIONORDERMRP_EXPORTPRICE?: number
  PRODUCTIONORDERMRP_EXPORTAMOUNT?: number
  PRODUCTIONORDERMRP_NETRATE?: number
  PRODUCTIONORDERMRP_GROSSRATE?: number
  PRODUCTIONORDERMRP_BOMMASTER_ID?: number
  PRODUCTIONORDERMRP_SODQUANTITY?: number
  PRODUCTIONORDERMRP_PRODUCTIONORDERDETAIL_ID?: number
  PRODUCTIONORDERMRP_WORKDAY?: Date
}
