export interface ProductionCost {
  ID: number
  PRODUCTIONCOST_CORP_ID?: number
  PRODUCTIONCOST_YEAR?: number
  PRODUCTIONCOST_MONTH?: number
  PRODUCTIONCOST_KIND?: number
  PRODUCTIONCOST_FACTORY_ID?: number
  PRODUCTIONCOST_TYPE_ID?: number
  PRODUCTIONCOST_PLANT_ID?: number
  PRODUCTIONCOST_AMOUNT?: number
  PRODUCTIONCOST_REGUSER_ID?: number
  PRODUCTIONCOST_REGDATE?: Date
  PRODUCTIONCOST_REGIP?: string
}
