export interface ProductionPlanDetail {
  ID: number
  PRODUCTIONPLANDETAIL_REGUSER_ID?: number
  PRODUCTIONPLANDETAIL_REGDATE?: Date
  PRODUCTIONPLANDETAIL_REGIP?: string
  PRODUCTIONPLANDETAIL_MASTER_ID?: number
  PRODUCTIONPLANDETAIL_STEPNUMBER?: number
  PRODUCTIONPLANDETAIL_SALESORDERDETAIL_ID?: number
  PRODUCTIONPLANDETAIL_QUANTITY?: number
  PRODUCTIONPLANDETAIL_SEQUENCE?: number
  PRODUCTIONPLANDETAIL_CLOSE?: boolean
  PRODUCTIONPLANDETAIL_CLOSEDATE?: Date
  PRODUCTIONPLANDETAIL_DESCRIPTION?: string
  PRODUCTIONPLANDETAIL_DELIVERYDATE?: Date
  PRODUCTIONPLANDETAIL_PRODUCTDATE?: Date
  PRODUCTIONPLANDETAIL_YEARWEEK?: string
  PRODUCTIONPLANDETAIL_PLANTMASTER_ID?: number
  PRODUCTIONPLANDETAIL_PLANSTARTDATE?: Date
  PRODUCTIONPLANDETAIL_PLANENDDATE?: Date
  PRODUCTIONPLANDETAIL_CAPACITY?: number
  PRODUCTIONPLANDETAIL_RENEWTIME?: number
  PRODUCTIONPLANDETAIL_SETTINGTIME?: number
  PRODUCTIONPLANDETAIL_OPRNUMBER?: string
  PRODUCTIONPLANDETAIL_CAPACITY_ID?: number
  PRODUCTIONPLANDETAIL_ITEM_ID?: number
  PRODUCTIONPLANDETAIL_STOCKQUANTITY?: number
}
