export interface ProductionOrderPlan {
  ID: number
  PRODUCTIONORDERPLAN_ACTUALSTART?: number
  PRODUCTIONORDERPLAN_ACTUALFINISH?: number
  PRODUCTIONORDERPLAN_CAPTION?: string
  PRODUCTIONORDERPLAN_TYPE?: number
  PRODUCTIONORDERPLAN_FINISH?: Date
  PRODUCTIONORDERPLAN_IDS?: number
  PRODUCTIONORDERPLAN_LABELCOLOR?: number
  PRODUCTIONORDERPLAN_LOCATION?: string
  PRODUCTIONORDERPLAN_MESSAGE?: string
  PRODUCTIONORDERPLAN_OPTIONS?: number
  PRODUCTIONORDERPLAN_PARENTID?: number
  PRODUCTIONORDERPLAN_RECURRENCEINDEX?: number
  PRODUCTIONORDERPLAN_RECURRENCEINFO?: string
  PRODUCTIONORDERPLAN_REMINDERDATE?: Date
  PRODUCTIONORDERPLAN_REMINDERMINUTES?: number
  PRODUCTIONORDERPLAN_RESOURCEID?: number
  PRODUCTIONORDERPLAN_START?: Date
  PRODUCTIONORDERPLAN_STATE?: number
  PRODUCTIONORDERPLAN_REGUSER_ID?: number
  PRODUCTIONORDERPLAN_REGDATE?: Date
  PRODUCTIONORDERPLAN_REGIP?: string
}
