export interface ProductionQuality {
  ID: number
  PRODUCTIONQUALITY_MASTER_ID?: number
  PRODUCTIONQUALITY_DETAIL_ID?: number
  PRODUCTIONQUALITY_STANDART_ID?: number
  PRODUCTIONQUALITY_DATE?: Date
  PRODUCTIONQUALITY_TIME?: string
  PRODUCTIONQUALITY_RESULT?: number
  PRODUCTIONQUALITY_RESULT1?: boolean
  PRODUCTIONQUALITY_RESULT2?: Date
  PRODUCTIONQUALITY_DESCRIPTION?: string
  PRODUCTIONQUALITY_REGUSER_ID?: number
  PRODUCTIONQUALITY_REGDATE?: Date
  PRODUCTIONQUALITY_REGIP?: string
  PRODUCTIONQUALITY_DESCRIPTION2?: string
}
