export interface ProductionOrderChemDetailCaldron {
  ID: number
  PRODUCTIONORDERCHEMDETAILCALDRON_REGUSER_ID?: number
  PRODUCTIONORDERCHEMDETAILCALDRON_REGDATE?: Date
  PRODUCTIONORDERCHEMDETAILCALDRON_REGIP?: string
  PRODUCTIONORDERCHEMDETAILCALDRON_MASTER_ID?: number
  PRODUCTIONORDERCHEMDETAILCALDRON_TYPE?: number
  PRODUCTIONORDERCHEMDETAILCALDRON_CALDRON_ID?: number
  PRODUCTIONORDERCHEMDETAILCALDRON_ITEM_ID?: number
  PRODUCTIONORDERCHEMDETAILCALDRON_UNIT_ID?: number
  PRODUCTIONORDERCHEMDETAILCALDRON_SUBITEM_ID?: number
  PRODUCTIONORDERCHEMDETAILCALDRON_SUBUNIT_ID?: number
  PRODUCTIONORDERCHEMDETAILCALDRON_QUANTITY?: number
  PRODUCTIONORDERCHEMDETAILCALDRON_PIECE?: number
  PRODUCTIONORDERCHEMDETAILCALDRON_SEQUENCE?: number
  PRODUCTIONORDERCHEMDETAILCALDRON_QUANTITY2?: number
}
