export interface ProductionOrderChemMaster {
  ID: number
  PRODUCTIONORDERCHEMMASTER_REGUSER_ID?: number
  PRODUCTIONORDERCHEMMASTER_REGDATE?: Date
  PRODUCTIONORDERCHEMMASTER_REGIP?: string
  PRODUCTIONORDERCHEMMASTER_CORP_ID?: number
  PRODUCTIONORDERCHEMMASTER_SECTION_ID?: number
  PRODUCTIONORDERCHEMMASTER_YEAR?: number
  PRODUCTIONORDERCHEMMASTER_NUMBER?: number
  PRODUCTIONORDERCHEMMASTER_DATE?: Date
  PRODUCTIONORDERCHEMMASTER_PLANTMASTER_ID?: number
  PRODUCTIONORDERCHEMMASTER_SHIFT_ID?: number
}
