import { Profile } from '../db/Profile'

export interface ProfileInsulation {
  ID: number
  PROFILEINSULATION_TYPE: boolean
  PROFILEINSULATION_PROFILE_ID?: number
  PROFILEINSULATION_MASTER_ID: number
  PROFILEINSULATION_ORDER: number
  PROFILEINSULATION_PIECE: number
  PROFILEINSULATION_GRAMMAGE: number
  PROFILEINSULATION_REGDATE: Date
  PROFILEINSULATION_REGIP: string
  PROFILEINSULATION_REGUSER_ID: number
  PROFILEINSULATION_ITEM_ID?: number
  PROFILEINSULATION_MASTER?: Profile
  PROFILEINSULATION_PROFILE?: Profile
}
