export interface ProjectDetail {
  ID: number
  PROJECTDETAIL_MASTER_ID?: number
  PROJECTDETAIL_UNIT_ID?: number
  PROJECTDETAIL_ITEM_ID?: number
  PROJECTDETAIL_TYPE?: number
  PROJECTDETAIL_DESC?: string
  PROJECTDETAIL_NOTE?: string
  PROJECTDETAIL_QUANTITY?: number
  PROJECTDETAIL_REGIP?: string
  PROJECTDETAIL_REGDATE?: Date
  PROJECTDETAIL_REGUSER_ID?: number
}
