export interface ProjectMaster {
  ID: number
  PROJECTMASTER_CORP_ID?: number
  PROJECTMASTER_SECTION_ID?: number
  PROJECTMASTER_REFCODE?: string
  PROJECTMASTER_NAME?: string
  PROJECTMASTER_REGUSER_ID?: number
  PROJECTMASTER_REGDATE?: Date
  PROJECTMASTER_REGIP?: string
  PROJECTMASTER_DATE?: Date
  PROJECTMASTER_TYPE_ID?: number
  PROJECTMASTER_NUMBER?: number
  PROJECTMASTER_SOURCECOMPANY?: string
  PROJECTMASTER_ADDRESS?: string
  PROJECTMASTER_DISTRICT?: string
  PROJECTMASTER_PHONE?: string
  PROJECTMASTER_COUNTRY_ID?: number
  PROJECTMASTER_CITY?: string
  PROJECTMASTER_YEAR?: number
  PROJECTMASTER_CLOSED?: boolean
}
