import { PurchaseReturnInvoiceDescription } from '../db/PurchaseReturnInvoiceDescription'
import { PurchaseReturnInvoiceDetail } from '../db/PurchaseReturnInvoiceDetail'
import { PurchaseReturnMaster } from '../db/PurchaseReturnMaster'

export interface PurchaseReturnInvoiceMaster {
  ID: number
  PURCHASERETURNINVOICEMASTER_CORP_ID: number
  PURCHASERETURNINVOICEMASTER_SECTION_ID: number
  PURCHASERETURNINVOICEMASTER_YEAR: number
  PURCHASERETURNINVOICEMASTER_SERIAL_ID: number
  PURCHASERETURNINVOICEMASTER_NUMBER: number
  PURCHASERETURNINVOICEMASTER_DATE: Date
  PURCHASERETURNINVOICEMASTER_COMPANY_ID: number
  PURCHASERETURNINVOICEMASTER_SUBACCOUNT_ID: number
  PURCHASERETURNINVOICEMASTER_PURCHASETYPE_ID: number
  PURCHASERETURNINVOICEMASTER_PAYMENT_ID?: number
  PURCHASERETURNINVOICEMASTER_PAYMENTDATE: Date
  PURCHASERETURNINVOICEMASTER_PAYMENTDAY: number
  PURCHASERETURNINVOICEMASTER_DOCUMENTSERIAL: string
  PURCHASERETURNINVOICEMASTER_DOCUMENTNUMBER: string
  PURCHASERETURNINVOICEMASTER_DOCUMENTDATE: Date
  PURCHASERETURNINVOICEMASTER_DESCRIPTION?: string
  PURCHASERETURNINVOICEMASTER_ACCOUNTING: boolean
  PURCHASERETURNINVOICEMASTER_WITHHOLDING: boolean
  PURCHASERETURNINVOICEMASTER_CONFIRM: boolean
  PURCHASERETURNINVOICEMASTER_XMLDATE?: Date
  PURCHASERETURNINVOICEMASTER_XMLGUID?: string
  PURCHASERETURNINVOICEMASTER_VATEXCEPTION_ID?: number
  PURCHASERETURNINVOICEMASTER_REGUSER_ID: number
  PURCHASERETURNINVOICEMASTER_REGDATE: Date
  PURCHASERETURNINVOICEMASTER_REGIP: string
  PURCHASERETURNINVOICEMASTER_CURRENCY_ID?: number
  PURCHASERETURNINVOICEMASTER_CASTINGTYPE?: string
  PURCHASERETURNINVOICEMASTER_SCTEXCEPTION_ID?: number
  PurchaseReturnInvoiceDescription: PurchaseReturnInvoiceDescription[]
  PurchaseReturnInvoiceDetail: PurchaseReturnInvoiceDetail[]
  PurchaseReturnMaster: PurchaseReturnMaster[]
}
