import { PurchaseInvoiceMaster } from '../db/PurchaseInvoiceMaster'
import { PurchaseDetail } from '../db/PurchaseDetail'

export interface PurchaseInvoiceDetail {
  ID: number
  PURCHASEINVOICEDETAIL_MASTER_ID: number
  PURCHASEINVOICEDETAIL_PURCHASEDETAIL_ID?: number
  PURCHASEINVOICEDETAIL_ITEM_ID: number
  PURCHASEINVOICEDETAIL_QUANTITY: number
  PURCHASEINVOICEDETAIL_UNIT_ID: number
  PURCHASEINVOICEDETAIL_CURRENCY_ID?: number
  PURCHASEINVOICEDETAIL_CURRENCYPRICE: number
  PURCHASEINVOICEDETAIL_CURRENCYRATE: number
  PURCHASEINVOICEDETAIL_CURRENCYAMOUNT: number
  PURCHASEINVOICEDETAIL_PRICE: number
  PURCHASEINVOICEDETAIL_AMOUNT: number
  PURCHASEINVOICEDETAIL_DISCOUNTAMOUNT: number
  PURCHASEINVOICEDETAIL_VATRATE: number
  PURCHASEINVOICEDETAIL_VATAMOUNT: number
  PURCHASEINVOICEDETAIL_WITHHOLDINGAMOUNT: number
  PURCHASEINVOICEDETAIL_WITHHOLDINGRATE: number
  PURCHASEINVOICEDETAIL_DESCRIPTION?: string
  PURCHASEINVOICEDETAIL_LINK?: string
  PURCHASEINVOICEDETAIL_REF_ID?: number
  PURCHASEINVOICEDETAIL_REGUSER_ID: number
  PURCHASEINVOICEDETAIL_REGDATE: Date
  PURCHASEINVOICEDETAIL_REGIP: string
  PURCHASEINVOICEDETAIL_SCTRATE: number
  PURCHASEINVOICEDETAIL_SCTAMOUNT: number
  PURCHASEINVOICEDETAIL_PIECE: number
  PURCHASEINVOICEDETAIL_MASTER?: PurchaseInvoiceMaster
  PURCHASEINVOICEDETAIL_PURCHASEDETAIL?: PurchaseDetail
}
