import { PurchaseReturnInvoiceMaster } from '../db/PurchaseReturnInvoiceMaster'

export interface PurchaseReturnInvoiceDescription {
  ID: number
  PURCHASERETURNINVOICEDESCRIPTION_MASTER_ID: number
  PURCHASERETURNINVOICEDESCRIPTION_DESCRIPTION: string
  PURCHASERETURNINVOICEDESCRIPTION_REGUSER_ID: number
  PURCHASERETURNINVOICEDESCRIPTION_REGDATE: Date
  PURCHASERETURNINVOICEDESCRIPTION_REGIP: string
  PURCHASERETURNINVOICEDESCRIPTION_MASTER?: PurchaseReturnInvoiceMaster
}
