import { Color } from '../db/Color'
import { PurchaseDemandDetail } from '../db/PurchaseDemandDetail'
import { PurchaseOrderMaster } from '../db/PurchaseOrderMaster'
import { PurchaseDetail } from '../db/PurchaseDetail'
import { PurchaseOrderDetailSub } from '../db/PurchaseOrderDetailSub'

export interface PurchaseOrderDetail {
  ID: number
  PURCHASEORDERDETAIL_MASTER_ID: number
  PURCHASEORDERDETAIL_DEMANDDETAIL_ID?: number
  PURCHASEORDERDETAIL_ITEM_ID: number
  PURCHASEORDERDETAIL_QUANTITY: number
  PURCHASEORDERDETAIL_UNIT_ID: number
  PURCHASEORDERDETAIL_CURRENCY_ID?: number
  PURCHASEORDERDETAIL_PRICE: number
  PURCHASEORDERDETAIL_AMOUNT: number
  PURCHASEORDERDETAIL_DISCOUNTAMOUNT: number
  PURCHASEORDERDETAIL_VATRATE: number
  PURCHASEORDERDETAIL_VATAMOUNT: number
  PURCHASEORDERDETAIL_DELIVERYDATE: Date
  PURCHASEORDERDETAIL_DESCRIPTION?: string
  PURCHASEORDERDETAIL_CLOSED: boolean
  PURCHASEORDERDETAIL_INCENTIVENO?: string
  PURCHASEORDERDETAIL_REGUSER_ID: number
  PURCHASEORDERDETAIL_REGDATE: Date
  PURCHASEORDERDETAIL_REGIP: string
  PURCHASEORDERDETAIL_CURRENCYRATE: number
  PURCHASEORDERDETAIL_SECTION_ID?: number
  PURCHASEORDERDETAIL_PROFILE_ID?: number
  PURCHASEORDERDETAIL_SURFACE_ID?: number
  PURCHASEORDERDETAIL_COLOR_ID?: number
  PURCHASEORDERDETAIL_ALLOY_ID?: number
  PURCHASEORDERDETAIL_HARDNESS_ID?: number
  PURCHASEORDERDETAIL_GRAMMAGE: number
  PURCHASEORDERDETAIL_LENGTH: number
  PURCHASEORDERDETAIL_PIECE: number
  PURCHASEORDERDETAIL_PRICEUNIT_ID: number
  PURCHASEORDERDETAIL_METER: number
  PURCHASEORDERDETAIL_LME: boolean
  PURCHASEORDERDETAIL_MICRON?: string
  PURCHASEORDERDETAIL_MECHANICALPROCESS_ID?: number
  PURCHASEORDERDETAIL_MECHANICALPROCESS: boolean
  PURCHASEORDERDETAIL_MECHANICALPROCESSDESC?: string
  PURCHASEORDERDETAIL_LENGTHTOLERANCE?: string
  PURCHASEORDERDETAIL_QUANTITYTOLERANCE?: string
  PURCHASEORDERDETAIL_ANODIZINGTRACE: boolean
  PURCHASEORDERDETAIL_CERTIFICATE: boolean
  PURCHASEORDERDETAIL_PACKINGPCS: number
  PURCHASEORDERDETAIL_PACKAGE_ID?: number
  PURCHASEORDERDETAIL_PALLET_ID?: number
  PURCHASEORDERDETAIL_FOIL_ID?: number
  PURCHASEORDERDETAIL_SEPERATOR_ID?: number
  PURCHASEORDERDETAIL_SPECIALPACKAGING: boolean
  PURCHASEORDERDETAIL_TYPE: number
  PURCHASEORDERDETAIL_SEQUENCE: number
  PURCHASEORDERDETAIL_LINK?: string
  PURCHASEORDERDETAIL_REF_ID?: number
  PURCHASEORDERDETAIL_COLOR?: Color
  PURCHASEORDERDETAIL_DEMANDDETAIL?: PurchaseDemandDetail
  PURCHASEORDERDETAIL_MASTER?: PurchaseOrderMaster
  PurchaseDetail: PurchaseDetail[]
  PurchaseOrderDetailSub: PurchaseOrderDetailSub[]
}
