import { Color } from '../db/Color'
import { PurchaseMaster } from '../db/PurchaseMaster'
import { PurchaseOrderDetail } from '../db/PurchaseOrderDetail'
import { PurchaseDetailSub } from '../db/PurchaseDetailSub'
import { PurchaseInvoiceDetail } from '../db/PurchaseInvoiceDetail'

export interface PurchaseDetail {
  ID: number
  PURCHASEDETAIL_MASTER_ID: number
  PURCHASEDETAIL_STORE_ID: number
  PURCHASEDETAIL_ORDERDETAIL_ID?: number
  PURCHASEDETAIL_ITEM_ID: number
  PURCHASEDETAIL_QUANTITY: number
  PURCHASEDETAIL_UNIT_ID: number
  PURCHASEDETAIL_LOTNUMBER?: string
  PURCHASEDETAIL_SUPPLOTNUMBER?: string
  PURCHASEDETAIL_CURRENCY_ID?: number
  PURCHASEDETAIL_CURRENCYPRICE: number
  PURCHASEDETAIL_CURRENCYRATE: number
  PURCHASEDETAIL_CURRENCYAMOUNT: number
  PURCHASEDETAIL_PRICE: number
  PURCHASEDETAIL_AMOUNT: number
  PURCHASEDETAIL_DISCOUNTAMOUNT: number
  PURCHASEDETAIL_VATRATE: number
  PURCHASEDETAIL_VATAMOUNT: number
  PURCHASEDETAIL_DESCRIPTION?: string
  PURCHASEDETAIL_PRODUCTIONDATE?: Date
  PURCHASEDETAIL_EXPIRATIONDATE?: Date
  PURCHASEDETAIL_PACKAGEPCS: number
  PURCHASEDETAIL_REGUSER_ID: number
  PURCHASEDETAIL_REGDATE: Date
  PURCHASEDETAIL_REGIP: string
  PURCHASEDETAIL_SCTRATE: number
  PURCHASEDETAIL_SCTAMOUNT: number
  PURCHASEDETAIL_WITHHOLDINGRATE: number
  PURCHASEDETAIL_WITHHOLDINGAMOUNT: number
  PURCHASEDETAIL_PROFILE_ID?: number
  PURCHASEDETAIL_ALLOY_ID?: number
  PURCHASEDETAIL_HARDNESS_ID?: number
  PURCHASEDETAIL_COLOR_ID?: number
  PURCHASEDETAIL_LENGTH: number
  PURCHASEDETAIL_PIECE: number
  PURCHASEDETAIL_SURFACE_ID?: number
  PURCHASEDETAIL_DIAMETER?: number
  PURCHASEDETAIL_TYPE: number
  PURCHASEDETAIL_COLOR?: Color
  PURCHASEDETAIL_MASTER?: PurchaseMaster
  PURCHASEDETAIL_ORDERDETAIL?: PurchaseOrderDetail
  PurchaseDetailSub: PurchaseDetailSub[]
  PurchaseInvoiceDetail: PurchaseInvoiceDetail[]
}
