export interface PurchaseOfferMaster {
  ID: number
  PURCHASEOFFERMASTER_CORP_ID?: number
  PURCHASEOFFERMASTER_SECTION_ID?: number
  PURCHASEOFFERMASTER_YEAR?: number
  PURCHASEOFFERMASTER_SERIAL_ID?: number
  PURCHASEOFFERMASTER_NUMBER?: number
  PURCHASEOFFERMASTER_DATE?: Date
  PURCHASEOFFERMASTER_DESCRIPTION?: string
  PURCHASEOFFERMASTER_CLOSED?: boolean
  PURCHASEOFFERMASTER_REGUSER_ID?: number
  PURCHASEOFFERMASTER_REGDATE?: Date
  PURCHASEOFFERMASTER_REGIP?: string
}
