import { PurchaseOrderDescription } from '../db/PurchaseOrderDescription'
import { PurchaseOrderDetail } from '../db/PurchaseOrderDetail'
import { PurchaseOrderDetailSub } from '../db/PurchaseOrderDetailSub'

export interface PurchaseOrderMaster {
  PURCHASEORDERMASTER_REGUSER_ID: number
  PURCHASEORDERMASTER_REGDATE: Date
  PURCHASEORDERMASTER_REGIP: string
  ID: number
  PURCHASEORDERMASTER_CORP_ID: number
  PURCHASEORDERMASTER_SECTION_ID: number
  PURCHASEORDERMASTER_YEAR: number
  PURCHASEORDERMASTER_SERIAL_ID: number
  PURCHASEORDERMASTER_NUMBER: number
  PURCHASEORDERMASTER_DATE: Date
  PURCHASEORDERMASTER_PURCHASETYPE_ID: number
  PURCHASEORDERMASTER_COMPANY_ID: number
  PURCHASEORDERMASTER_MEDIATOR_ID?: number
  PURCHASEORDERMASTER_SHIPPER_ID?: number
  PURCHASEORDERMASTER_AUTHORISED1?: string
  PURCHASEORDERMASTER_AUTHORISED2?: string
  PURCHASEORDERMASTER_COUNTRY_ID?: number
  PURCHASEORDERMASTER_REFNO?: string
  PURCHASEORDERMASTER_DELIVERY_ID?: number
  PURCHASEORDERMASTER_PAYMENT_ID?: number
  PURCHASEORDERMASTER_PAYMENTDATE?: Date
  PURCHASEORDERMASTER_CURRENCY_ID?: number
  PURCHASEORDERMASTER_VEHICLE_ID?: number
  PURCHASEORDERMASTER_SHIPPERDATE?: Date
  PURCHASEORDERMASTER_SHIPPERAUTHORIZED?: string
  PURCHASEORDERMASTER_INSURANCEDATE?: Date
  PURCHASEORDERMASTER_IMPORTDATE?: Date
  PURCHASEORDERMASTER_BILLOFLADINGNO?: string
  PURCHASEORDERMASTER_CUSTOMDATE?: Date
  PURCHASEORDERMASTER_CUSTOMNUMBER?: string
  PURCHASEORDERMASTER_DESCRIPTION?: string
  PURCHASEORDERMASTER_CLOSED: boolean
  PURCHASEORDERMASTER_CONTAINERNO?: string
  PURCHASEORDERMASTER_COMMISSIONRATE?: string
  PURCHASEORDERMASTER_PAYMENTDAY: number
  PURCHASEORDERMASTER_REFDATE?: Date
  PURCHASEORDERMASTER_INCENTIVE: boolean
  PURCHASEORDERMASTER_CONFIRM: boolean
  PURCHASEORDERMASTER_REF_ID?: number
  PURCHASEORDERMASTER_LINK?: string
  PURCHASEORDERMASTER_REPRESENTATIVE_ID?: number
  PURCHASEORDERMASTER_DELIVERYCOMPANY_ID?: number
  PURCHASEORDERMASTER_DELIVERYPLACE_ID?: number
  PURCHASEORDERMASTER_MANAGERCONFIRM: number
  PurchaseOrderDescription: PurchaseOrderDescription[]
  PurchaseOrderDetail: PurchaseOrderDetail[]
  PurchaseOrderDetailSub: PurchaseOrderDetailSub[]
}
