export interface PurchasePriceDetail {
  ID: number
  PURCHASEPRICEDETAIL_MASTER_ID?: number
  PURCHASEPRICEDETAIL_ITEM_ID?: number
  PURCHASEPRICEDETAIL_COMPANY_ID?: number
  PURCHASEPRICEDETAIL_PAYMENT_ID?: number
  PURCHASEPRICEDETAIL_VEHICLE_ID?: number
  PURCHASEPRICEDETAIL_CURRENCY_ID?: number
  PURCHASEPRICEDETAIL_PRICE: number
  PURCHASEPRICEDETAIL_QUANTITY?: number
  PURCHASEPRICEDETAIL_UNIT_ID?: number
  PURCHASEPRICEDETAIL_VALIDDATE?: Date
  PURCHASEPRICEDETAIL_CLOSED?: boolean
  PURCHASEPRICEDETAIL_REGUSER_ID: number
  PURCHASEPRICEDETAIL_REGDATE: Date
  PURCHASEPRICEDETAIL_REGIP: string
  PURCHASEPRICEDETAIL_PRICEDIFFERENCE?: number
  PURCHASEPRICEDETAIL_MTZ?: boolean
  PURCHASEPRICEDETAIL_CURRENCYRATE?: number
  PURCHASEPRICEDETAIL_CURRENCYPRICE?: number
  PURCHASEPRICEDETAIL_CURRENCYAMOUNT?: number
  PURCHASEPRICEDETAIL_PRICE2?: number
  PURCHASEPRICEDETAIL_PRICE3?: number
  PURCHASEPRICEDETAIL_PRICE4?: number
}
