export interface PurchasePriceMaster {
  ID: number
  PURCHASEPRICEMASTER_CORP_ID?: number
  PURCHASEPRICEMASTER_YEAR: number
  PURCHASEPRICEMASTER_SECTION_ID?: number
  PURCHASEPRICEMASTER_NUMBER: number
  PURCHASEPRICEMASTER_TYPE_ID?: number
  PURCHASEPRICEMASTER_COMPANY_ID?: number
  PURCHASEPRICEMASTER_DATE: Date
  PURCHASEPRICEMASTER_CLOSED?: boolean
  PURCHASEPRICEMASTER_CLOSEDDATE?: Date
  PURCHASEPRICEMASTER_DESCRIPTION?: string
  PURCHASEPRICEMASTER_REGUSER_ID?: number
  PURCHASEPRICEMASTER_REGDATE?: Date
  PURCHASEPRICEMASTER_REGIP?: string
  PURCHASEPRICEMASTER_COMPANYPRICETYPE_ID?: number
  PURCHASEPRICEMASTER_TRANSPORTTYPE_ID?: number
  PURCHASEPRICEMASTER_CURRENCY_ID?: number
  PURCHASEPRICEMASTER_TAXTYPE?: number
  PURCHASEPRICEMASTER_PRICETYPE_ID?: number
}
