import { PurchaseDemandDetail } from '../db/PurchaseDemandDetail'

export interface PurchaseDemandMaster {
  ID: number
  PURCHASEDEMANDMASTER_CORP_ID: number
  PURCHASEDEMANDMASTER_SECTION_ID: number
  PURCHASEDEMANDMASTER_YEAR: number
  PURCHASEDEMANDMASTER_NUMBER: number
  PURCHASEDEMANDMASTER_DATE: Date
  PURCHASEDEMANDMASTER_DEPARTMENT_ID: number
  PURCHASEDEMANDMASTER_REGUSER_ID: number
  PURCHASEDEMANDMASTER_REGDATE: Date
  PURCHASEDEMANDMASTER_REGIP: string
  PURCHASEDEMANDMASTER_CLOSED: boolean
  PURCHASEDEMANDMASTER_USER_ID: number
  PURCHASEDEMANDMASTER_DELIVERY_ID?: number
  PURCHASEDEMANDMASTER_CONFIRM: boolean
  PURCHASEDEMANDMASTER_DESCRIPTION?: string
  PURCHASEDEMANDMASTER_REASON_ID: number
  PURCHASEDEMANDMASTER_SALESCOMPANY_ID?: number
  PURCHASEDEMANDMASTER_DELIVERYPLACE_ID?: number
  PurchaseDemandDetail: PurchaseDemandDetail[]
}
