import { PurchaseInvoiceDetail } from '../db/PurchaseInvoiceDetail'
import { PurchaseMaster } from '../db/PurchaseMaster'

export interface PurchaseInvoiceMaster {
  ID: number
  PURCHASEINVOICEMASTER_CORP_ID: number
  PURCHASEINVOICEMASTER_SECTION_ID: number
  PURCHASEINVOICEMASTER_YEAR: number
  PURCHASEINVOICEMASTER_SERIAL_ID: number
  PURCHASEINVOICEMASTER_NUMBER: number
  PURCHASEINVOICEMASTER_DATE: Date
  PURCHASEINVOICEMASTER_COMPANY_ID: number
  PURCHASEINVOICEMASTER_PURCHASETYPE_ID: number
  PURCHASEINVOICEMASTER_PAYMENT_ID?: number
  PURCHASEINVOICEMASTER_PAYMENTDATE: Date
  PURCHASEINVOICEMASTER_PAYMENTDAY: number
  PURCHASEINVOICEMASTER_DOCUMENTSERIAL: string
  PURCHASEINVOICEMASTER_DOCUMENTNUMBER: string
  PURCHASEINVOICEMASTER_DOCUMENTDATE: Date
  PURCHASEINVOICEMASTER_DESCRIPTION?: string
  PURCHASEINVOICEMASTER_ACCOUNTING: boolean
  PURCHASEINVOICEMASTER_WITHHOLDING: boolean
  PURCHASEINVOICEMASTER_SUBACCOUNT_ID: number
  PURCHASEINVOICEMASTER_TAXFREE: boolean
  PURCHASEINVOICEMASTER_CONFIRM: boolean
  PURCHASEINVOICEMASTER_LINK?: string
  PURCHASEINVOICEMASTER_REF_ID?: number
  PURCHASEINVOICEMASTER_IMPORTMASTER_ID?: number
  PURCHASEINVOICEMASTER_REGUSER_ID: number
  PURCHASEINVOICEMASTER_REGDATE: Date
  PURCHASEINVOICEMASTER_REGIP: string
  PURCHASEINVOICEMASTER_CURRENCY_ID?: number
  PURCHASEINVOICEMASTER_MANAGERCONFIRM: number
  PURCHASEINVOICEMASTER_CURRENTCONFIRM: boolean
  PurchaseInvoiceDetail: PurchaseInvoiceDetail[]
  PurchaseMaster: PurchaseMaster[]
}
