import { PurchaseOrderDetail } from '../db/PurchaseOrderDetail'
import { PurchaseOrderMaster } from '../db/PurchaseOrderMaster'

export interface PurchaseOrderDetailSub {
  ID: number
  PURCHASEORDERDETAILSUB_MASTER_ID: number
  PURCHASEORDERDETAILSUB_DETAIL_ID: number
  PURCHASEORDERDETAILSUB_ITEM_ID: number
  PURCHASEORDERDETAILSUB_PRICE: number
  PURCHASEORDERDETAILSUB_CURRENCY_ID?: number
  PURCHASEORDERDETAILSUB_UNIT_ID: number
  PURCHASEORDERDETAILSUB_DESCRIPTION?: string
  PURCHASEORDERDETAILSUB_REGDATE: Date
  PURCHASEORDERDETAILSUB_REGIP: string
  PURCHASEORDERDETAILSUB_REGUSER_ID: number
  PURCHASEORDERDETAILSUB_NOINVOICE: boolean
  PURCHASEORDERDETAILSUB_DETAIL?: PurchaseOrderDetail
  PURCHASEORDERDETAILSUB_MASTER?: PurchaseOrderMaster
}
