export interface PurchaseOfferItems {
  ID: number
  PURCHASEOFFERITEMS_MASTER_ID?: number
  PURCHASEOFFERITEMS_OFFERDETAIL_ID?: number
  PURCHASEOFFERITEMS_OFFERCOMPANY_ID?: number
  PURCHASEOFFERITEMS_QUANTITY?: number
  PURCHASEOFFERITEMS_PRICE?: number
  PURCHASEOFFERITEMS_AMOUNT?: number
  PURCHASEOFFERITEMS_CURRENCY_ID?: number
  PURCHASEOFFERITEMS_CURRENCYRATE?: number
  PURCHASEOFFERITEMS_CURRENCYPRICE?: number
  PURCHASEOFFERITEMS_CURRENCYAMOUNT?: number
  PURCHASEOFFERITEMS_DESCRIPTION1?: string
  PURCHASEOFFERITEMS_DESCRIPTION2?: string
  PURCHASEOFFERITEMS_CONFIRM?: boolean
  PURCHASEOFFERITEMS_PURCHASEORDERDETAIL_ID?: number
  PURCHASEOFFERITEMS_REGUSER_ID?: number
  PURCHASEOFFERITEMS_REGDATE?: Date
  PURCHASEOFFERITEMS_REGIP?: string
}
