import { PurchaseReturnMaster } from '../db/PurchaseReturnMaster'
import { PurchaseReturnInvoiceDetail } from '../db/PurchaseReturnInvoiceDetail'

export interface PurchaseReturnDetail {
  ID: number
  PURCHASERETURNDETAIL_MASTER_ID: number
  PURCHASERETURNDETAIL_STORE_ID: number
  PURCHASERETURNDETAIL_ORDERDETAIL_ID?: number
  PURCHASERETURNDETAIL_ITEM_ID: number
  PURCHASERETURNDETAIL_QUANTITY: number
  PURCHASERETURNDETAIL_PIECE: number
  PURCHASERETURNDETAIL_PACKAGEPCS: number
  PURCHASERETURNDETAIL_UNIT_ID: number
  PURCHASERETURNDETAIL_LOTNUMBER?: string
  PURCHASERETURNDETAIL_CURRENCY_ID?: number
  PURCHASERETURNDETAIL_CURRENCYPRICE: number
  PURCHASERETURNDETAIL_CURRENCYRATE: number
  PURCHASERETURNDETAIL_CURRENCYAMOUNT: number
  PURCHASERETURNDETAIL_PRICE: number
  PURCHASERETURNDETAIL_AMOUNT: number
  PURCHASERETURNDETAIL_DISCOUNTAMOUNT: number
  PURCHASERETURNDETAIL_VATRATE: number
  PURCHASERETURNDETAIL_VATAMOUNT: number
  PURCHASERETURNDETAIL_WITHHOLDINGAMOUNT: number
  PURCHASERETURNDETAIL_WITHHOLDINGRATE: number
  PURCHASERETURNDETAIL_DESCRIPTION?: string
  PURCHASERETURNDETAIL_PRODUCTIONDATE?: Date
  PURCHASERETURNDETAIL_EXPIRATIONDATE?: Date
  PURCHASERETURNDETAIL_REGUSER_ID: number
  PURCHASERETURNDETAIL_REGDATE: Date
  PURCHASERETURNDETAIL_REGIP: string
  PURCHASERETURNDETAIL_SCTRATE: number
  PURCHASERETURNDETAIL_SCTAMOUNT: number
  PURCHASERETURNDETAIL_MASTER?: PurchaseReturnMaster
  PurchaseReturnInvoiceDetail: PurchaseReturnInvoiceDetail[]
}
