import { PurchaseDemandMaster } from '../db/PurchaseDemandMaster'
import { SalesOrderMaster } from '../db/SalesOrderMaster'
import { PurchaseOrderDetail } from '../db/PurchaseOrderDetail'

export interface PurchaseDemandDetail {
  ID: number
  PURCHASEDEMANDDETAIL_MASTER_ID: number
  PURCHASEDEMANDDETAIL_ITEM_ID: number
  PURCHASEDEMANDDETAIL_QUANTITY: number
  PURCHASEDEMANDDETAIL_UNIT_ID: number
  PURCHASEDEMANDDETAIL_DESCRIPTION?: string
  PURCHASEDEMANDDETAIL_COMPANY_ID?: number
  PURCHASEDEMANDDETAIL_CLOSED: boolean
  PURCHASEDEMANDDETAIL_CONFIRM: number
  PURCHASEDEMANDDETAIL_CONFIRMUSER_ID?: number
  PURCHASEDEMANDDETAIL_REGUSER_ID: number
  PURCHASEDEMANDDETAIL_REGDATE: Date
  PURCHASEDEMANDDETAIL_REGIP: string
  PURCHASEDEMANDDETAIL_SALESORDERMASTER_ID?: number
  PURCHASEDEMANDDETAIL_SECTION_ID: number
  PURCHASEDEMANDDETAIL_DELIVERYDATE: Date
  PURCHASEDEMANDDETAIL_MASTER?: PurchaseDemandMaster
  PURCHASEDEMANDDETAIL_SALESORDERMASTER?: SalesOrderMaster
  PurchaseOrderDetail: PurchaseOrderDetail[]
}
