export interface PurchaseContractDetail {
  ID: number
  PURCHASECONTRACTDETAIL_REGUSER_ID?: number
  PURCHASECONTRACTDETAIL_REGDATE?: Date
  PURCHASECONTRACTDETAIL_REGIP?: string
  PURCHASECONTRACTDETAIL_MASTER_ID?: number
  PURCHASECONTRACTDETAIL_ITEM_ID?: number
  PURCHASECONTRACTDETAIL_ITEMGROUP_ID?: number
  PURCHASECONTRACTDETAIL_QUANTITY: number
  PURCHASECONTRACTDETAIL_UNIT_ID?: number
  PURCHASECONTRACTDETAIL_PRICE?: number
  PURCHASECONTRACTDETAIL_CURRENCY_ID?: number
  PURCHASECONTRACTDETAIL_AMOUNT?: number
  PURCHASECONTRACTDETAIL_DISCOUNTRATE?: number
  PURCHASECONTRACTDETAIL_TAXRATE?: number
  PURCHASECONTRACTDETAIL_TAXAMOUNT?: number
  PURCHASECONTRACTDETAIL_TOLERANCEMIN?: number
  PURCHASECONTRACTDETAIL_TOLERANCEMAX?: number
  PURCHASECONTRACTDETAIL_DESCRIPTION?: string
  PURCHASECONTRACTDETAIL_PURCHASEDEMANDDETAIL_ID?: number
  PURCHASECONTRACTDETAIL_CURRENCYAMOUNT?: number
  PURCHASECONTRACTDETAIL_CURRENCYPRICE?: number
  PURCHASECONTRACTDETAIL_CURRENCYRATE?: number
}
