export interface PurchaseOfferCompanyFallow {
  ID: number
  PURCHASEOFFERCOMPANYFALLOW_MASTER_ID?: number
  PURCHASEOFFERCOMPANYFALLOW_COMPANY_ID?: number
  PURCHASEOFFERCOMPANYFALLOW_OTHERCOMPANYNAME?: string
  PURCHASEOFFERCOMPANYFALLOW_AUTHORISED?: string
  PURCHASEOFFERCOMPANYFALLOW_TERM?: number
  PURCHASEOFFERCOMPANYFALLOW_OPTIONDAY?: number
  PURCHASEOFFERCOMPANYFALLOW_ANSWERDATE?: Date
  PURCHASEOFFERCOMPANYFALLOW_DESCRIPTION?: string
  PURCHASEOFFERCOMPANYFALLOW_REGUSER_ID?: number
  PURCHASEOFFERCOMPANYFALLOW_REGDATE?: Date
  PURCHASEOFFERCOMPANYFALLOW_REGIP?: string
}
