import { PurchaseReturnInvoiceMaster } from '../db/PurchaseReturnInvoiceMaster'
import { PurchaseReturnDescription } from '../db/PurchaseReturnDescription'
import { PurchaseReturnDetail } from '../db/PurchaseReturnDetail'
import { StockMaster } from '../db/StockMaster'

export interface PurchaseReturnMaster {
  ID: number
  PURCHASERETURNMASTER_CORP_ID: number
  PURCHASERETURNMASTER_SECTION_ID: number
  PURCHASERETURNMASTER_YEAR: number
  PURCHASERETURNMASTER_SERIAL_ID: number
  PURCHASERETURNMASTER_NUMBER: number
  PURCHASERETURNMASTER_DATE: Date
  PURCHASERETURNMASTER_DOCUMENTNUMBER: string
  PURCHASERETURNMASTER_DOCUMENTSERIAL: string
  PURCHASERETURNMASTER_DOCUMENTDATE: Date
  PURCHASERETURNMASTER_PURCHASETYPE_ID: number
  PURCHASERETURNMASTER_COMPANY_ID: number
  PURCHASERETURNMASTER_PAYMENT_ID?: number
  PURCHASERETURNMASTER_PAYMENTDAY: number
  PURCHASERETURNMASTER_PAYMENTDATE: Date
  PURCHASERETURNMASTER_INVOICE_ID?: number
  PURCHASERETURNMASTER_LINK?: string
  PURCHASERETURNMASTER_REF_ID?: number
  PURCHASERETURNMASTER_REGUSER_ID: number
  PURCHASERETURNMASTER_REGDATE: Date
  PURCHASERETURNMASTER_REGIP: string
  PURCHASERETURNMASTER_DRIVERNAME?: string
  PURCHASERETURNMASTER_DRIVERIDENTITY?: string
  PURCHASERETURNMASTER_DRIVERPHONE?: string
  PURCHASERETURNMASTER_PLATE?: string
  PURCHASERETURNMASTER_TRANSPORTCOMPANY_ID?: number
  PURCHASERETURNMASTER_XMLDATE?: Date
  PURCHASERETURNMASTER_XMLGUID?: string
  PURCHASERETURNMASTER_CONFIRM: boolean
  PURCHASERETURNMASTER_DRIVERSURNAME?: string
  PURCHASERETURNMASTER_INVOICE?: PurchaseReturnInvoiceMaster
  PurchaseReturnDescription: PurchaseReturnDescription[]
  PurchaseReturnDetail: PurchaseReturnDetail[]
  StockMaster: StockMaster[]
}
