export interface PurchaseContractDescription {
  ID: number
  PURCHASECONTRACTDESCRIPTION_MASTER_ID?: number
  PURCHASECONTRACTDESCRIPTION_TYPE_ID?: number
  PURCHASECONTRACTDESCRIPTION_DESCRIPTION?: string
  PURCHASECONTRACTDESCRIPTION_REGUSER_ID?: number
  PURCHASECONTRACTDESCRIPTION_REGDATE?: Date
  PURCHASECONTRACTDESCRIPTION_REGIP?: string
}
