import { PurchaseInvoiceMaster } from '../db/PurchaseInvoiceMaster'
import { PurchaseDetail } from '../db/PurchaseDetail'

export interface PurchaseMaster {
  ID: number
  PURCHASEMASTER_CORP_ID: number
  PURCHASEMASTER_SECTION_ID: number
  PURCHASEMASTER_YEAR: number
  PURCHASEMASTER_SERIAL_ID: number
  PURCHASEMASTER_NUMBER: number
  PURCHASEMASTER_DATE: Date
  PURCHASEMASTER_DOCUMENTNUMBER: string
  PURCHASEMASTER_DOCUMENTDATE: Date
  PURCHASEMASTER_DOCUMENTSERIAL: string
  PURCHASEMASTER_PURCHASETYPE_ID: number
  PURCHASEMASTER_COMPANY_ID: number
  PURCHASEMASTER_PAYMENT_ID?: number
  PURCHASEMASTER_PAYMENTDAY: number
  PURCHASEMASTER_PAYMENTDATE: Date
  PURCHASEMASTER_INVOICE_ID?: number
  PURCHASEMASTER_REGUSER_ID: number
  PURCHASEMASTER_REGDATE: Date
  PURCHASEMASTER_REGIP: string
  PURCHASEMASTER_SUBACCOUNT_ID?: number
  PURCHASEMASTER_CONFIRM: boolean
  PURCHASEMASTER_INVOICE?: PurchaseInvoiceMaster
  PurchaseDetail: PurchaseDetail[]
}
