import { PurchaseReturnInvoiceMaster } from '../db/PurchaseReturnInvoiceMaster'
import { PurchaseReturnDetail } from '../db/PurchaseReturnDetail'

export interface PurchaseReturnInvoiceDetail {
  ID: number
  PURCHASERETURNINVOICEDETAIL_MASTER_ID: number
  PURCHASERETURNINVOICEDETAIL_PURCHASEDETAIL_ID?: number
  PURCHASERETURNINVOICEDETAIL_ITEM_ID: number
  PURCHASERETURNINVOICEDETAIL_QUANTITY: number
  PURCHASERETURNINVOICEDETAIL_UNIT_ID: number
  PURCHASERETURNINVOICEDETAIL_CURRENCY_ID?: number
  PURCHASERETURNINVOICEDETAIL_CURRENCYPRICE: number
  PURCHASERETURNINVOICEDETAIL_CURRENCYRATE: number
  PURCHASERETURNINVOICEDETAIL_CURRENCYAMOUNT: number
  PURCHASERETURNINVOICEDETAIL_PRICE: number
  PURCHASERETURNINVOICEDETAIL_AMOUNT: number
  PURCHASERETURNINVOICEDETAIL_DISCOUNTAMOUNT: number
  PURCHASERETURNINVOICEDETAIL_VATRATE: number
  PURCHASERETURNINVOICEDETAIL_VATAMOUNT: number
  PURCHASERETURNINVOICEDETAIL_WITHHOLDINGAMOUNT: number
  PURCHASERETURNINVOICEDETAIL_WITHHOLDINGRATE: number
  PURCHASERETURNINVOICEDETAIL_DESCRIPTION?: string
  PURCHASERETURNINVOICEDETAIL_REGUSER_ID: number
  PURCHASERETURNINVOICEDETAIL_REGDATE: Date
  PURCHASERETURNINVOICEDETAIL_REGIP: string
  PURCHASERETURNINVOICEDETAIL_SCTRATE: number
  PURCHASERETURNINVOICEDETAIL_SCTAMOUNT: number
  PURCHASERETURNINVOICEDETAIL_LINK?: string
  PURCHASERETURNINVOICEDETAIL_REF_ID?: number
  PURCHASERETURNINVOICEDETAIL_PIECE: number
  PURCHASERETURNINVOICEDETAIL_MASTER?: PurchaseReturnInvoiceMaster
  PURCHASERETURNINVOICEDETAIL_PURCHASEDETAIL?: PurchaseReturnDetail
}
