export interface PurchaseContractDocument {
  ID: number
  PURCHASECONTRACTDOCUMENT_MASTER_ID?: number
  PURCHASECONTRACTDOCUMENT_URL?: string
  PURCHASECONTRACTDOCUMENT_DESCRIPTION?: string
  PURCHASECONTRACTDOCUMENT_REGUSER_ID?: number
  PURCHASECONTRACTDOCUMENT_REGDATE?: Date
  PURCHASECONTRACTDOCUMENT_REGIP?: string
}
