import { ReportMaster } from '../db/ReportMaster'

export interface ReportParameter {
  ID: number
  REPORTPARAMETER_MASTER_ID: number
  REPORTPARAMETER_LABEL?: string
  REPORTPARAMETER_KEY: string
  REPORTPARAMETER_TYPE: string
  REPORTPARAMETER_DATAQUERY?: string
  REPORTPARAMETER_ORDER: number
  REPORTPARAMETER_OPERATOR?: string
  REPORTPARAMETER_DEFAULTVALUE?: string
  REPORTPARAMETER_CONDITION?: string
  REPORTPARAMETER_REQUIRED: boolean
  REPORTPARAMETER_REGUSER_ID: number
  REPORTPARAMETER_REGDATE: Date
  REPORTPARAMETER_REGIP: string
  REPORTPARAMETER_HIDDEN: boolean
  REPORTPARAMETER_MASTER?: ReportMaster
}
