import { ReportData } from '../db/ReportData'

export interface ReportDataColumn {
  ID: number
  REPORTDATACOLUMN_REPORTDATA_ID: number
  REPORTDATACOLUMN_DATAFIELD: string
  REPORTDATACOLUMN_TYPE: string
  REPORTDATACOLUMN_CAPTION?: string
  REPORTDATACOLUMN_WIDTH: number
  REPORTDATACOLUMN_ORDER: number
  REPORTDATACOLUMN_GROUP: boolean
  REPORTDATACOLUMN_SUMMARY?: string
  REPORTDATACOLUMN_VISIBLE: boolean
  REPORTDATACOLUMN_REGDATE: Date
  REPORTDATACOLUMN_REGIP: string
  REPORTDATACOLUMN_REGUSER_ID: number
  REPORTDATACOLUMN_GROUPSUMMARY?: string
  REPORTDATACOLUMN_COLOR?: string
  REPORTDATACOLUMN_FORMAT?: string
  REPORTDATACOLUMN_AREA?: string
  REPORTDATACOLUMN_PERMISSION_ID?: number
  REPORTDATACOLUMN_REPORTDATA?: ReportData
}
