export interface RetailCompany {
  ID: number
  RETAILCOMPANY_COMPANYNAME: string
  RETAILCOMPANY_ADDRESS?: string
  RETAILCOMPANY_TAXNO?: string
  RETAILCOMPANY_TAXOFFICE?: string
  RETAILCOMPANY_TELNUMBER?: string
  RETAILCOMPANY_FAXNUMBER?: string
  RETAILCOMPANY_EMAIL?: string
  RETAILCOMPANY_COUNTRY_ID?: number
  RETAILCOMPANY_CITY?: string
  RETAILCOMPANY_REGUSER_ID: number
  RETAILCOMPANY_REGIP: string
  RETAILCOMPANY_REGDATE: Date
}
