import { SalesInvoiceReturnMaster } from '../db/SalesInvoiceReturnMaster'
import { SalesWaybillReturnDetail } from '../db/SalesWaybillReturnDetail'

export interface SalesInvoiceReturnDetail {
  ID: number
  SALESINVOICERETURNDETAIL_MASTER_ID: number
  SALESINVOICERETURNDETAIL_WAYBILLDETAIL_ID?: number
  SALESINVOICERETURNDETAIL_ITEM_ID: number
  SALESINVOICERETURNDETAIL_QUANTITY: number
  SALESINVOICERETURNDETAIL_UNIT_ID: number
  SALESINVOICERETURNDETAIL_CURRENCYRATE: number
  SALESINVOICERETURNDETAIL_CURRENCYPRICE: number
  SALESINVOICERETURNDETAIL_CURRENCYAMOUNT: number
  SALESINVOICERETURNDETAIL_PRICE: number
  SALESINVOICERETURNDETAIL_AMOUNT: number
  SALESINVOICERETURNDETAIL_DISCOUNTAMOUNT: number
  SALESINVOICERETURNDETAIL_VATRATE: number
  SALESINVOICERETURNDETAIL_VATAMOUNT: number
  SALESINVOICERETURNDETAIL_WITHHOLDINGAMOUNT: number
  SALESINVOICERETURNDETAIL_WITHHOLDINGRATE: number
  SALESINVOICERETURNDETAIL_DESCRIPTION?: string
  SALESINVOICERETURNDETAIL_LINK?: string
  SALESINVOICERETURNDETAIL_REF_ID?: number
  SALESINVOICERETURNDETAIL_REGUSER_ID: number
  SALESINVOICERETURNDETAIL_REGDATE: Date
  SALESINVOICERETURNDETAIL_REGIP: string
  SALESINVOICERETURNDETAIL_SCTRATE: number
  SALESINVOICERETURNDETAIL_SCTAMOUNT: number
  SALESINVOICERETURNDETAIL_CURRENCY_ID?: number
  SALESINVOICERETURNDETAIL_PIECE: number
  SALESINVOICERETURNDETAIL_MASTER?: SalesInvoiceReturnMaster
  SALESINVOICERETURNDETAIL_WAYBILLDETAIL?: SalesWaybillReturnDetail
}
