import { SalesOrderDetail } from '../db/SalesOrderDetail'

export interface SalesOrderDetailRevise {
  ID: number
  SALESORDERDETAILREVISE_DETAIL_ID: number
  SALESORDERDETAILREVISE_ALLOY_ID?: number
  SALESORDERDETAILREVISE_HARDNESS_ID?: number
  SALESORDERDETAILREVISE_SURFACE_ID?: number
  SALESORDERDETAILREVISE_COLOR_ID?: number
  SALESORDERDETAILREVISE_LENGTH?: number
  SALESORDERDETAILREVISE_LENGTHTOLERANCE?: string
  SALESORDERDETAILREVISE_PIECE?: number
  SALESORDERDETAILREVISE_QUANTITY?: number
  SALESORDERDETAILREVISE_FOIL_ID?: number
  SALESORDERDETAILREVISE_DEMANDUSER_ID: number
  SALESORDERDETAILREVISE_DEMANDDATE: Date
  SALESORDERDETAILREVISE_DELIVERYDATE?: Date
  SALESORDERDETAILREVISE_DESCRIPTION?: string
  SALESORDERDETAILREVISE_REGDATE: Date
  SALESORDERDETAILREVISE_REGIP: string
  SALESORDERDETAILREVISE_REGUSER_ID: number
  SALESORDERDETAILREVISE_CONFIRM: number
  SALESORDERDETAILREVISE_ITEM_ID?: number
  SALESORDERDETAILREVISE_MECHANICALPROCESSDESC?: string
  SALESORDERDETAILREVISE_DETAIL?: SalesOrderDetail
}
