import { SalesWaybillMaster } from '../db/SalesWaybillMaster'
import { SalesOrderDetail } from '../db/SalesOrderDetail'
import { SalesInvoiceDetail } from '../db/SalesInvoiceDetail'

export interface SalesWaybillDetail {
  ID: number
  SALESWAYBILLDETAIL_MASTER_ID: number
  SALESWAYBILLDETAIL_ORDERDETAIL_ID?: number
  SALESWAYBILLDETAIL_ITEM_ID: number
  SALESWAYBILLDETAIL_QUANTITY: number
  SALESWAYBILLDETAIL_UNIT_ID: number
  SALESWAYBILLDETAIL_CURRENCY_ID?: number
  SALESWAYBILLDETAIL_CURRENCYPRICE: number
  SALESWAYBILLDETAIL_CURRENCYAMOUNT: number
  SALESWAYBILLDETAIL_CURRENCYRATE: number
  SALESWAYBILLDETAIL_PRICE: number
  SALESWAYBILLDETAIL_AMOUNT: number
  SALESWAYBILLDETAIL_DISCOUNTAMOUNT: number
  SALESWAYBILLDETAIL_VATRATE: number
  SALESWAYBILLDETAIL_VATAMOUNT: number
  SALESWAYBILLDETAIL_WITHHOLDINGAMOUNT: number
  SALESWAYBILLDETAIL_WITHHOLDINGRATE: number
  SALESWAYBILLDETAIL_DESCRIPTION?: string
  SALESWAYBILLDETAIL_LINK?: string
  SALESWAYBILLDETAIL_REF_ID?: number
  SALESWAYBILLDETAIL_REGUSER_ID: number
  SALESWAYBILLDETAIL_REGDATE: Date
  SALESWAYBILLDETAIL_REGIP: string
  SALESWAYBILLDETAIL_STORE_ID: number
  SALESWAYBILLDETAIL_SCTRATE: number
  SALESWAYBILLDETAIL_SCTAMOUNT: number
  SALESWAYBILLDETAIL_PRICEDETAIL_ID?: number
  SALESWAYBILLDETAIL_PIECE: number
  SALESWAYBILLDETAIL_MASTER?: SalesWaybillMaster
  SALESWAYBILLDETAIL_ORDERDETAIL?: SalesOrderDetail
  SalesInvoiceDetail: SalesInvoiceDetail[]
}
