import { SalesInstructionMaster } from '../db/SalesInstructionMaster'
import { SalesOrderDetail } from '../db/SalesOrderDetail'

export interface SalesInstructionDetail {
  ID: number
  SALESINSTRUCTIONDETAIL_MASTER_ID: number
  SALESINSTRUCTIONDETAIL_ORDERDETAIL_ID: number
  SALESINSTRUCTIONDETAIL_QUANTITY: number
  SALESINSTRUCTIONDETAIL_DESCRIPTION?: string
  SALESINSTRUCTIONDETAIL_CONTAINER?: string
  SALESINSTRUCTIONDETAIL_CLOSED: boolean
  SALESINSTRUCTIONDETAIL_REGUSER_ID: number
  SALESINSTRUCTIONDETAIL_REGDATE: Date
  SALESINSTRUCTIONDETAIL_REGIP: string
  SALESINSTRUCTIONDETAIL_PIECE: number
  SALESINSTRUCTIONDETAIL_MASTER?: SalesInstructionMaster
  SALESINSTRUCTIONDETAIL_ORDERDETAIL?: SalesOrderDetail
}
