import { SalesInstructionMaster } from '../db/SalesInstructionMaster'
import { SalesInvoiceMaster } from '../db/SalesInvoiceMaster'
import { SalesWaybillDescription } from '../db/SalesWaybillDescription'
import { SalesWaybillDetail } from '../db/SalesWaybillDetail'
import { StockMaster } from '../db/StockMaster'

export interface SalesWaybillMaster {
  ID: number
  SALESWAYBILLMASTER_CORP_ID: number
  SALESWAYBILLMASTER_SECTION_ID: number
  SALESWAYBILLMASTER_YEAR: number
  SALESWAYBILLMASTER_SERIAL_ID: number
  SALESWAYBILLMASTER_NUMBER: number
  SALESWAYBILLMASTER_DATE: Date
  SALESWAYBILLMASTER_SALESTYPE_ID: number
  SALESWAYBILLMASTER_INSTRUCTIONMASTER_ID?: number
  SALESWAYBILLMASTER_COMPANY_ID: number
  SALESWAYBILLMASTER_SUBACCOUNT_ID?: number
  SALESWAYBILLMASTER_REPRESENTATIVE_ID?: number
  SALESWAYBILLMASTER_DELIVERY_ID?: number
  SALESWAYBILLMASTER_DELIVERYPLACE_ID?: number
  SALESWAYBILLMASTER_TRANSPORT_ID: number
  SALESWAYBILLMASTER_PAYMENT_ID?: number
  SALESWAYBILLMASTER_PAYMENTDAY: number
  SALESWAYBILLMASTER_SUBCOMPANY_ID?: number
  SALESWAYBILLMASTER_TRANSPORTCOMPANY_ID?: number
  SALESWAYBILLMASTER_INVOICE_ID?: number
  SALESWAYBILLMASTER_CONTAINERNUMBER?: string
  SALESWAYBILLMASTER_DELIVERYDATE?: Date
  SALESWAYBILLMASTER_DRIVERNAME?: string
  SALESWAYBILLMASTER_DRIVERPHONE?: string
  SALESWAYBILLMASTER_PLATE?: string
  SALESWAYBILLMASTER_SEALNUMBER?: string
  SALESWAYBILLMASTER_LINK?: string
  SALESWAYBILLMASTER_REF_ID?: number
  SALESWAYBILLMASTER_REGUSER_ID: number
  SALESWAYBILLMASTER_REGDATE: Date
  SALESWAYBILLMASTER_REGIP: string
  SALESWAYBILLMASTER_DRIVERIDENTITY?: string
  SALESWAYBILLMASTER_XMLDATE?: Date
  SALESWAYBILLMASTER_XMLGUID?: string
  SALESWAYBILLMASTER_CONFIRM: boolean
  SALESWAYBILLMASTER_DOCUMENTNUMBER: string
  SALESWAYBILLMASTER_DOCUMENTDATE: Date
  SALESWAYBILLMASTER_DOCUMENTSERIAL: string
  SALESWAYBILLMASTER_TRANSPORT: boolean
  SALESWAYBILLMASTER_DRIVERSURNAME?: string
  SALESWAYBILLMASTER_INSTRUCTIONMASTER?: SalesInstructionMaster
  SALESWAYBILLMASTER_INVOICE?: SalesInvoiceMaster
  SalesWaybillDescription: SalesWaybillDescription[]
  SalesWaybillDetail: SalesWaybillDetail[]
  StockMaster: StockMaster[]
}
