import { PurchaseDemandDetail } from '../db/PurchaseDemandDetail'
import { SalesOrderDescription } from '../db/SalesOrderDescription'
import { SalesOrderDetail } from '../db/SalesOrderDetail'
import { SalesOrderDetailSub } from '../db/SalesOrderDetailSub'

export interface SalesOrderMaster {
  ID: number
  SALESORDERMASTER_CORP_ID: number
  SALESORDERMASTER_SECTION_ID: number
  SALESORDERMASTER_YEAR: number
  SALESORDERMASTER_SERIAL_ID: number
  SALESORDERMASTER_NUMBER: number
  SALESORDERMASTER_DATE: Date
  SALESORDERMASTER_SALESTYPE_ID: number
  SALESORDERMASTER_COMPANY_ID?: number
  SALESORDERMASTER_SUBCOMPANY_ID?: number
  SALESORDERMASTER_AUTHORISED?: string
  SALESORDERMASTER_REPRESENTATIVE_ID?: number
  SALESORDERMASTER_CURRENCY_ID?: number
  SALESORDERMASTER_PAYMENT_ID?: number
  SALESORDERMASTER_PAYMENTDAY: number
  SALESORDERMASTER_DELIVERY_ID?: number
  SALESORDERMASTER_DELIVERYPLACE_ID?: number
  SALESORDERMASTER_TRANSPORT_ID?: number
  SALESORDERMASTER_DEMANDDATE?: Date
  SALESORDERMASTER_COMPANYREFNO?: string
  SALESORDERMASTER_COMPANYREFDATE?: Date
  SALESORDERMASTER_CLOSED: boolean
  SALESORDERMASTER_CLOSEDDATE?: Date
  SALESORDERMASTER_CONFIRM: boolean
  SALESORDERMASTER_REGUSER_ID: number
  SALESORDERMASTER_REGDATE: Date
  SALESORDERMASTER_REGIP: string
  SALESORDERMASTER_REF_ID?: number
  SALESORDERMASTER_LINK?: string
  SALESORDERMASTER_CLOSEDREASON_ID?: number
  SALESORDERMASTER_VALIDITYDATE?: Date
  SALESORDERMASTER_FIXEDLME?: number
  SALESORDERMASTER_FIXEDCURRENCY?: number
  SALESORDERMASTER_MANAGERCONFIRM: number
  SALESORDERMASTER_KIND: number
  SALESORDERMASTER_PLANCONFIRM: number
  PurchaseDemandDetail: PurchaseDemandDetail[]
  SalesOrderDescription: SalesOrderDescription[]
  SalesOrderDetail: SalesOrderDetail[]
  SalesOrderDetailSub: SalesOrderDetailSub[]
}
