import { Color } from '../db/Color'
import { SalesOrderMaster } from '../db/SalesOrderMaster'
import { ProductionOrderDetail } from '../db/ProductionOrderDetail'
import { SalesInstructionDetail } from '../db/SalesInstructionDetail'
import { SalesOrderDetailRevise } from '../db/SalesOrderDetailRevise'
import { SalesOrderDetailSub } from '../db/SalesOrderDetailSub'
import { SalesWaybillDetail } from '../db/SalesWaybillDetail'

export interface SalesOrderDetail {
  ID: number
  SALESORDERDETAIL_MASTER_ID: number
  SALESORDERDETAIL_ITEM_ID: number
  SALESORDERDETAIL_UNIT_ID: number
  SALESORDERDETAIL_QUANTITY: number
  SALESORDERDETAIL_PRICE: number
  SALESORDERDETAIL_AMOUNT: number
  SALESORDERDETAIL_DISCOUNTAMOUNT: number
  SALESORDERDETAIL_CURRENCYRATE: number
  SALESORDERDETAIL_VATRATE: number
  SALESORDERDETAIL_VATAMOUNT: number
  SALESORDERDETAIL_WITHHOLDINGAMOUNT: number
  SALESORDERDETAIL_WITHHOLDINGRATE: number
  SALESORDERDETAIL_DELIVERYDATE?: Date
  SALESORDERDETAIL_DESCRIPTION?: string
  SALESORDERDETAIL_CLOSED: boolean
  SALESORDERDETAIL_REGUSER_ID: number
  SALESORDERDETAIL_REGDATE: Date
  SALESORDERDETAIL_REGIP: string
  SALESORDERDETAIL_SCTRATE: number
  SALESORDERDETAIL_SCTAMOUNT: number
  SALESORDERDETAIL_PRICEDETAIL_ID?: number
  SALESORDERDETAIL_STORE_ID?: number
  SALESORDERDETAIL_PROFILE_ID?: number
  SALESORDERDETAIL_LENGTH: number
  SALESORDERDETAIL_PIECE: number
  SALESORDERDETAIL_COLOR_ID?: number
  SALESORDERDETAIL_ALLOY_ID?: number
  SALESORDERDETAIL_SURFACE_ID?: number
  SALESORDERDETAIL_HARDNESS_ID?: number
  SALESORDERDETAIL_MICRON?: string
  SALESORDERDETAIL_SEQUENCE: number
  SALESORDERDETAIL_COMPANYITEMNUMBER?: string
  SALESORDERDETAIL_GRAMMAGE: number
  SALESORDERDETAIL_LENGTHTOLERANCE?: string
  SALESORDERDETAIL_PRICEUNIT_ID?: number
  SALESORDERDETAIL_LME: boolean
  SALESORDERDETAIL_NOPRODUCTION: boolean
  SALESORDERDETAIL_ANODIZINGTRACE: boolean
  SALESORDERDETAIL_MECHANICALPROCESS: boolean
  SALESORDERDETAIL_MECHANICALPROCESSDESC?: string
  SALESORDERDETAIL_DEMANDDATE?: Date
  SALESORDERDETAIL_PLANNINGNOTE?: string
  SALESORDERDETAIL_CONTRACTDESC?: string
  SALESORDERDETAIL_PARENT_ID?: number
  SALESORDERDETAIL_PACKINGPCS: number
  SALESORDERDETAIL_FOIL_ID?: number
  SALESORDERDETAIL_PACKAGE_ID?: number
  SALESORDERDETAIL_PALLET_ID?: number
  SALESORDERDETAIL_SEPERATOR_ID?: number
  SALESORDERDETAIL_SPECIALPACKAGING: boolean
  SALESORDERDETAIL_COMPANYPROFILENUMBER?: string
  SALESORDERDETAIL_QUANTITYTOLERANCE?: string
  SALESORDERDETAIL_MECHANICALPROCESS_ID?: number
  SALESORDERDETAIL_CERTIFICATE: boolean
  SALESORDERDETAIL_CURRENCY_ID?: number
  SALESORDERDETAIL_TYPE: number
  SALESORDERDETAIL_LINK?: string
  SALESORDERDETAIL_REF_ID?: number
  SALESORDERDETAIL_COLORDETAIL_ID?: number
  SALESORDERDETAIL_ROUTEMASTER_ID?: number
  SALESORDERDETAIL_COLOR?: Color
  SALESORDERDETAIL_MASTER?: SalesOrderMaster
  ProductionOrderDetail: ProductionOrderDetail[]
  SalesInstructionDetail: SalesInstructionDetail[]
  SalesOrderDetailRevise: SalesOrderDetailRevise[]
  SalesOrderDetailSub: SalesOrderDetailSub[]
  SalesWaybillDetail: SalesWaybillDetail[]
}
