import { SalesInvoiceReturnMaster } from '../db/SalesInvoiceReturnMaster'
import { SalesWaybillReturnDetail } from '../db/SalesWaybillReturnDetail'

export interface SalesWaybillReturnMaster {
  ID: number
  SALESWAYBILLRETURNMASTER_CORP_ID: number
  SALESWAYBILLRETURNMASTER_SECTION_ID: number
  SALESWAYBILLRETURNMASTER_YEAR: number
  SALESWAYBILLRETURNMASTER_SERIAL_ID: number
  SALESWAYBILLRETURNMASTER_NUMBER: number
  SALESWAYBILLRETURNMASTER_DATE: Date
  SALESWAYBILLRETURNMASTER_DOCUMENTNUMBER: string
  SALESWAYBILLRETURNMASTER_DOCUMENTDATE: Date
  SALESWAYBILLRETURNMASTER_DOCUMENTSERIAL: string
  SALESWAYBILLRETURNMASTER_SALESTYPE_ID: number
  SALESWAYBILLRETURNMASTER_INSTRUCTIONMASTER_ID?: number
  SALESWAYBILLRETURNMASTER_COMPANY_ID: number
  SALESWAYBILLRETURNMASTER_PAYMENT_ID?: number
  SALESWAYBILLRETURNMASTER_PAYMENTDAY: number
  SALESWAYBILLRETURNMASTER_INVOICE_ID?: number
  SALESWAYBILLRETURNMASTER_LINK?: string
  SALESWAYBILLRETURNMASTER_REF_ID?: number
  SALESWAYBILLRETURNMASTER_REGUSER_ID: number
  SALESWAYBILLRETURNMASTER_REGDATE: Date
  SALESWAYBILLRETURNMASTER_REGIP: string
  SALESWAYBILLRETURNMASTER_CONFIRM: boolean
  SALESWAYBILLRETURNMASTER_INVOICE?: SalesInvoiceReturnMaster
  SalesWaybillReturnDetail: SalesWaybillReturnDetail[]
}
