import { SalesOrderMaster } from '../db/SalesOrderMaster'

export interface SalesOrderDescription {
  ID: number
  SALESORDERDESCRIPTION_MASTER_ID: number
  SALESORDERDESCRIPTION_TYPE: number
  SALESORDERDESCRIPTION_DESCRIPTION: string
  SALESORDERDESCRIPTION_REGUSER_ID: number
  SALESORDERDESCRIPTION_REGDATE: Date
  SALESORDERDESCRIPTION_REGIP: string
  SALESORDERDESCRIPTION_PLANT_ID?: number
  SALESORDERDESCRIPTION_MASTER?: SalesOrderMaster
}
