import { SalesInstructionDetail } from '../db/SalesInstructionDetail'
import { SalesWaybillMaster } from '../db/SalesWaybillMaster'

export interface SalesInstructionMaster {
  ID: number
  SALESINSTRUCTIONMASTER_CORP_ID: number
  SALESINSTRUCTIONMASTER_SECTION_ID: number
  SALESINSTRUCTIONMASTER_YEAR: number
  SALESINSTRUCTIONMASTER_SERIAL_ID: number
  SALESINSTRUCTIONMASTER_NUMBER: number
  SALESINSTRUCTIONMASTER_DATE: Date
  SALESINSTRUCTIONMASTER_SALESTYPE_ID: number
  SALESINSTRUCTIONMASTER_COMPANY_ID: number
  SALESINSTRUCTIONMASTER_LOADINGDATE?: Date
  SALESINSTRUCTIONMASTER_CLOSED: boolean
  SALESINSTRUCTIONMASTER_DESCRIPTION?: string
  SALESINSTRUCTIONMASTER_CONTAINER?: string
  SALESINSTRUCTIONMASTER_DELIVERYPLACE_ID?: number
  SALESINSTRUCTIONMASTER_FRONTPLATE?: string
  SALESINSTRUCTIONMASTER_BACKPLATE?: string
  SALESINSTRUCTIONMASTER_CONFIRM: boolean
  SALESINSTRUCTIONMASTER_REGUSER_ID: number
  SALESINSTRUCTIONMASTER_REGDATE: Date
  SALESINSTRUCTIONMASTER_REGIP: string
  SALESINSTRUCTIONMASTER_STORECONFIRM: boolean
  SalesInstructionDetail: SalesInstructionDetail[]
  SalesWaybillMaster: SalesWaybillMaster[]
}
