import { SalesWaybillReturnMaster } from '../db/SalesWaybillReturnMaster'
import { SalesInvoiceReturnDetail } from '../db/SalesInvoiceReturnDetail'
import { SalesWaybillReturnDetailSub } from '../db/SalesWaybillReturnDetailSub'

export interface SalesWaybillReturnDetail {
  ID: number
  SALESWAYBILLRETURNDETAIL_MASTER_ID: number
  SALESWAYBILLRETURNDETAIL_STORE_ID: number
  SALESWAYBILLRETURNDETAIL_PRODUCTIONDATE?: Date
  SALESWAYBILLRETURNDETAIL_EXPIRATIONDATE?: Date
  SALESWAYBILLRETURNDETAIL_ITEM_ID: number
  SALESWAYBILLRETURNDETAIL_QUANTITY: number
  SALESWAYBILLRETURNDETAIL_UNIT_ID: number
  SALESWAYBILLRETURNDETAIL_LOTNUMBER?: string
  SALESWAYBILLRETURNDETAIL_CURRENCYPRICE: number
  SALESWAYBILLRETURNDETAIL_CURRENCYAMOUNT: number
  SALESWAYBILLRETURNDETAIL_CURRENCYRATE: number
  SALESWAYBILLRETURNDETAIL_PRICE: number
  SALESWAYBILLRETURNDETAIL_AMOUNT: number
  SALESWAYBILLRETURNDETAIL_DISCOUNTAMOUNT: number
  SALESWAYBILLRETURNDETAIL_VATRATE: number
  SALESWAYBILLRETURNDETAIL_VATAMOUNT: number
  SALESWAYBILLRETURNDETAIL_WITHHOLDINGAMOUNT: number
  SALESWAYBILLRETURNDETAIL_WITHHOLDINGRATE: number
  SALESWAYBILLRETURNDETAIL_DESCRIPTION?: string
  SALESWAYBILLRETURNDETAIL_LINK?: string
  SALESWAYBILLRETURNDETAIL_REF_ID?: number
  SALESWAYBILLRETURNDETAIL_REGUSER_ID: number
  SALESWAYBILLRETURNDETAIL_REGDATE: Date
  SALESWAYBILLRETURNDETAIL_REGIP: string
  SALESWAYBILLRETURNDETAIL_SCTRATE: number
  SALESWAYBILLRETURNDETAIL_SCTAMOUNT: number
  SALESWAYBILLRETURNDETAIL_CURRENCY_ID?: number
  SALESWAYBILLRETURNDETAIL_PACKAGEPCS: number
  SALESWAYBILLRETURNDETAIL_PROFILE_ID?: number
  SALESWAYBILLRETURNDETAIL_SURFACE_ID?: number
  SALESWAYBILLRETURNDETAIL_COLOR_ID?: number
  SALESWAYBILLRETURNDETAIL_ALLOY_ID?: number
  SALESWAYBILLRETURNDETAIL_HARDNESS_ID?: number
  SALESWAYBILLRETURNDETAIL_LENGTH: number
  SALESWAYBILLRETURNDETAIL_PIECE: number
  SALESWAYBILLRETURNDETAIL_MASTER?: SalesWaybillReturnMaster
  SalesInvoiceReturnDetail: SalesInvoiceReturnDetail[]
  SalesWaybillReturnDetailSub: SalesWaybillReturnDetailSub[]
}
