import { SalesInvoiceMaster } from '../db/SalesInvoiceMaster'
import { SalesWaybillDetail } from '../db/SalesWaybillDetail'

export interface SalesInvoiceDetail {
  ID: number
  SALESINVOICEDETAIL_MASTER_ID: number
  SALESINVOICEDETAIL_ITEM_ID: number
  SALESINVOICEDETAIL_QUANTITY: number
  SALESINVOICEDETAIL_UNIT_ID: number
  SALESINVOICEDETAIL_CURRENCY_ID?: number
  SALESINVOICEDETAIL_CURRENCYPRICE: number
  SALESINVOICEDETAIL_CURRENCYAMOUNT: number
  SALESINVOICEDETAIL_CURRENCYRATE: number
  SALESINVOICEDETAIL_PRICE: number
  SALESINVOICEDETAIL_AMOUNT: number
  SALESINVOICEDETAIL_DISCOUNTAMOUNT: number
  SALESINVOICEDETAIL_VATRATE: number
  SALESINVOICEDETAIL_VATAMOUNT: number
  SALESINVOICEDETAIL_WITHHOLDINGAMOUNT: number
  SALESINVOICEDETAIL_WITHHOLDINGRATE: number
  SALESINVOICEDETAIL_DESCRIPTION?: string
  SALESINVOICEDETAIL_LINK?: string
  SALESINVOICEDETAIL_REF_ID?: number
  SALESINVOICEDETAIL_REGUSER_ID: number
  SALESINVOICEDETAIL_REGDATE: Date
  SALESINVOICEDETAIL_REGIP: string
  SALESINVOICEDETAIL_SCTAMOUNT: number
  SALESINVOICEDETAIL_SCTRATE: number
  SALESINVOICEDETAIL_WAYBILLDETAIL_ID?: number
  SALESINVOICEDETAIL_PIECE: number
  SALESINVOICEDETAIL_MASTER?: SalesInvoiceMaster
  SALESINVOICEDETAIL_WAYBILLDETAIL?: SalesWaybillDetail
}
