import { SalesWaybillReturnDetail } from '../db/SalesWaybillReturnDetail'

export interface SalesWaybillReturnDetailSub {
  ID: number
  SALESWAYBILLRETURNDETAILSUB_DETAIL_ID: number
  SALESWAYBILLRETURNDETAILSUB_PACKINGPCS: number
  SALESWAYBILLRETURNDETAILSUB_PACKINGQUANTITY: number
  SALESWAYBILLRETURNDETAILSUB_BARCODE_ID: number
  SALESWAYBILLRETURNDETAILSUB_REGDATE: Date
  SALESWAYBILLRETURNDETAILSUB_REGIP: string
  SALESWAYBILLRETURNDETAILSUB_REGUSER_ID: number
  SALESWAYBILLRETURNDETAILSUB_DETAIL?: SalesWaybillReturnDetail
}
