import { SalesInvoiceReturnDetail } from '../db/SalesInvoiceReturnDetail'
import { SalesWaybillReturnMaster } from '../db/SalesWaybillReturnMaster'

export interface SalesInvoiceReturnMaster {
  ID: number
  SALESINVOICERETURNMASTER_CORP_ID: number
  SALESINVOICERETURNMASTER_SECTION_ID: number
  SALESINVOICERETURNMASTER_YEAR: number
  SALESINVOICERETURNMASTER_SERIAL_ID: number
  SALESINVOICERETURNMASTER_NUMBER: number
  SALESINVOICERETURNMASTER_DATE: Date
  SALESINVOICERETURNMASTER_SALESTYPE_ID: number
  SALESINVOICERETURNMASTER_COMPANY_ID: number
  SALESINVOICERETURNMASTER_SUBACCOUNT_ID: number
  SALESINVOICERETURNMASTER_PAYMENT_ID?: number
  SALESINVOICERETURNMASTER_PAYMENTDAY: number
  SALESINVOICERETURNMASTER_PAYMENTDATE: Date
  SALESINVOICERETURNMASTER_DOCUMENTSERIAL: string
  SALESINVOICERETURNMASTER_DOCUMENTNUMBER: string
  SALESINVOICERETURNMASTER_DOCUMENTDATE: Date
  SALESINVOICERETURNMASTER_CONFIRM: boolean
  SALESINVOICERETURNMASTER_ACCOUNTING: boolean
  SALESINVOICERETURNMASTER_LINK?: string
  SALESINVOICERETURNMASTER_REF_ID?: number
  SALESINVOICERETURNMASTER_REGUSER_ID: number
  SALESINVOICERETURNMASTER_REGDATE: Date
  SALESINVOICERETURNMASTER_REGIP: string
  SALESINVOICERETURNMASTER_CURRENCY_ID?: number
  SALESINVOICERETURNMASTER_MANAGERCONFIRM: number
  SALESINVOICERETURNMASTER_CURRENTCONFIRM: boolean
  SalesInvoiceReturnDetail: SalesInvoiceReturnDetail[]
  SalesWaybillReturnMaster: SalesWaybillReturnMaster[]
}
