import { SalesOrderDetail } from '../db/SalesOrderDetail'
import { SalesOrderMaster } from '../db/SalesOrderMaster'

export interface SalesOrderDetailSub {
  ID: number
  SALESORDERDETAILSUB_MASTER_ID: number
  SALESORDERDETAILSUB_DETAIL_ID: number
  SALESORDERDETAILSUB_ITEM_ID: number
  SALESORDERDETAILSUB_PRICE: number
  SALESORDERDETAILSUB_CURRENCY_ID?: number
  SALESORDERDETAILSUB_UNIT_ID: number
  SALESORDERDETAILSUB_NOINVOICE: boolean
  SALESORDERDETAILSUB_DESCRIPTION?: string
  SALESORDERDETAILSUB_COMPANYITEMNUMBER?: string
  SALESORDERDETAILSUB_ORDER: number
  SALESORDERDETAILSUB_REGDATE: Date
  SALESORDERDETAILSUB_REGIP: string
  SALESORDERDETAILSUB_REGUSER_ID: number
  SALESORDERDETAILSUB_DETAIL?: SalesOrderDetail
  SALESORDERDETAILSUB_MASTER?: SalesOrderMaster
}
