import { SalesInvoiceDescription } from '../db/SalesInvoiceDescription'
import { SalesInvoiceDetail } from '../db/SalesInvoiceDetail'
import { SalesWaybillMaster } from '../db/SalesWaybillMaster'

export interface SalesInvoiceMaster {
  ID: number
  SALESINVOICEMASTER_CORP_ID: number
  SALESINVOICEMASTER_SECTION_ID: number
  SALESINVOICEMASTER_YEAR: number
  SALESINVOICEMASTER_SERIAL_ID: number
  SALESINVOICEMASTER_NUMBER: number
  SALESINVOICEMASTER_DATE: Date
  SALESINVOICEMASTER_SALESTYPE_ID: number
  SALESINVOICEMASTER_COMPANY_ID: number
  SALESINVOICEMASTER_SUBACCOUNT_ID: number
  SALESINVOICEMASTER_REPRESENTATIVE_ID?: number
  SALESINVOICEMASTER_CURRENCY_ID?: number
  SALESINVOICEMASTER_DELIVERY_ID?: number
  SALESINVOICEMASTER_DELIVERYPLACE_ID?: number
  SALESINVOICEMASTER_PAYMENT_ID?: number
  SALESINVOICEMASTER_PAYMENTDAY: number
  SALESINVOICEMASTER_PAYMENTDATE: Date
  SALESINVOICEMASTER_ACCOUNTING: boolean
  SALESINVOICEMASTER_DOCUMENTSERIAL: string
  SALESINVOICEMASTER_DOCUMENTNUMBER: string
  SALESINVOICEMASTER_DOCUMENTDATE: Date
  SALESINVOICEMASTER_TRANSPORT_ID?: number
  SALESINVOICEMASTER_LINK?: string
  SALESINVOICEMASTER_REF_ID?: number
  SALESINVOICEMASTER_XMLDATE?: Date
  SALESINVOICEMASTER_XMLGUID?: string
  SALESINVOICEMASTER_VATEXCEPTION_ID?: number
  SALESINVOICEMASTER_REGUSER_ID: number
  SALESINVOICEMASTER_REGDATE: Date
  SALESINVOICEMASTER_REGIP: string
  SALESINVOICEMASTER_WITHHOLDING: boolean
  SALESINVOICEMASTER_CASTINGTYPE?: string
  SALESINVOICEMASTER_CONFIRM: boolean
  SALESINVOICEMASTER_CUSTOMSDATE?: Date
  SALESINVOICEMASTER_CUSTOMSCURRENCYRATE: number
  SALESINVOICEMASTER_VATEXCEPTIONDOCUMENTDATE?: Date
  SALESINVOICEMASTER_VATEXCEPTIONDOCUMENTNUMBER?: string
  SALESINVOICEMASTER_SCTEXCEPTION_ID?: number
  SalesInvoiceDescription: SalesInvoiceDescription[]
  SalesInvoiceDetail: SalesInvoiceDetail[]
  SalesWaybillMaster: SalesWaybillMaster[]
}
