export interface SetStoreControl {
  ID: number
  SETSTORECONTROL_CORP_ID: number
  SETSTORECONTROL_SOURCESTORE_ID: number
  SETSTORECONTROL_TARGETSTORE_ID: number
  SETSTORECONTROL_DEMAND?: boolean
  SETSTORECONTROL_QUANTITY?: boolean
  SETSTORECONTROL_REGUSER_ID?: number
  SETSTORECONTROL_REGDATE?: Date
  SETSTORECONTROL_REGIP?: string
  SETSTORECONTROL_TYPE_ID?: number
}
