export interface SetUserGroupDefiniton {
  ID: number
  SETUSERGROUPDEFINITION_CODE: string
  SETUSERGROUPDEFINITION_NAME?: string
  SETUSERGROUPDEFINITION_INFO?: string
  SETUSERGROUPDEFINITON_REGDATE?: Date
  SETUSERGROUPDEFINITON_REGUSER_ID?: number
  SETUSERGROUPDEFINITON_REGIP?: string
}
