import { Color } from '../db/Color'
import { StockMaster } from '../db/StockMaster'
import { PlantMaster } from '../db/PlantMaster'

export interface StockDetail {
  ID: number
  STOCKDETAIL_MASTER_ID: number
  STOCKDETAIL_STORE_ID: number
  STOCKDETAIL_ITEM_ID: number
  STOCKDETAIL_QUANTITY: number
  STOCKDETAIL_UNIT_ID: number
  STOCKDETAIL_PRICE: number
  STOCKDETAIL_AMOUNT: number
  STOCKDETAIL_LOTNUMBER?: string
  STOCKDETAIL_PRODUCTIONDATE?: Date
  STOCKDETAIL_EXPIRATIONDATE?: Date
  STOCKDETAIL_BARCODE_ID: number
  STOCKDETAIL_RACK_ID: number
  STOCKDETAIL_STATE_ID: number
  STOCKDETAIL_DESCRIPTION?: string
  STOCKDETAIL_LINK?: string
  STOCKDETAIL_REF_ID?: number
  STOCKDETAIL_REGUSER_ID: number
  STOCKDETAIL_REGDATE: Date
  STOCKDETAIL_REGIP: string
  STOCKDETAIL_PROFILE_ID?: number
  STOCKDETAIL_COLOR_ID?: number
  STOCKDETAIL_HARDNESS_ID?: number
  STOCKDETAIL_SURFACE_ID?: number
  STOCKDETAIL_ALLOY_ID?: number
  STOCKDETAIL_PIECE: number
  STOCKDETAIL_LENGTH: number
  STOCKDETAIL_ORDERDETAIL_ID?: number
  STOCKDETAIL_REALORDERDETAIL_ID?: number
  STOCKDETAIL_DIAMETER?: number
  STOCKDETAIL_PLANTMASTER_ID?: number
  STOCKDETAIL_COLOR?: Color
  STOCKDETAIL_MASTER?: StockMaster
  STOCKDETAIL_PLANTMASTER?: PlantMaster
}
