export interface V_AccountJournal {
  ID: number
  ACCOUNTJOURNAL_CORP_ID?: number
  ACCOUNTJOURNAL_YEAR?: number
  ACCOUNTJOURNAL_FIRSTDATE?: Date
  ACCOUNTJOURNAL_LASTDATE?: Date
  ACCOUNTJOURNAL_LASTNUMBER?: number
  ACCOUNTJOURNAL_REGUSER_ID?: number
  ACCOUNTJOURNAL_REGDATE?: Date
  ACCOUNTJOURNAL_REGIP?: string
  ACCOUNTJOURNAL_XML?: boolean
}
