export interface V_BalanceAccTerm {
  ID: number
  BALANCEACCTERM_CORP_ID?: number
  BALANCEACCTERM_TYPE_ID?: number
  BALANCEACCTERM_TERM?: number
  BALANCEACCTERM_BALANCE_ID?: number
  BALANCEACCTERM_AMOUNT?: number
  BALANCEACCTERM_REGUSER_ID?: number
  BALANCEACCTERM_REGDATE?: Date
  BALANCEACCTERM_REGIP?: string
  CORPORATION_NAME?: string
  BALANCEACCTERM_BALANCENUMBER?: string
  BALANCEACCTERM_BALANCENAME?: string
  BALANCEACCTERM_BALANCESIGN?: number
  BALANCEACCTERM_BALANCESUMMARY?: string
  BALANCEACCTERM_TYPECODE?: string
  BALANCEACCTERM_TYPENAME?: string
}
