export interface V_BalanceCurDetail {
  ID: number
  BALANCECURDETAIL_MASTER_ID?: number
  BALANCECURDETAIL_CURRENTACCOUNTPLAN_ID?: number
  BALANCECURDETAIL_DEBITCREDIT?: string
  BALANCECURDETAIL_AMOUNT?: number
  BALANCECURDETAIL_DESCRIPTION?: string
  BALANCECURDETAIL_REGUSER_ID?: number
  BALANCECURDETAIL_REGDATE?: Date
  BALANCECURDETAIL_REGIP?: string
  BALANCECURDETAIL_CURRENTACCOUNTNUMBER?: string
  BALANCECURDETAIL_CURRENTACCOUNTNAME?: string
  BALANCECURDETAIL_CURRENTACCOUNTNMASKACCNUMBER?: string
  BALANCECURDETAIL_DEBITAMOUNT: number
  BALANCECURDETAIL_CREDITAMOUNT: number
}
