export interface V_BankProjectDetail {
  ID: number
  BANKPROJECTDETAIL_MASTER_ID?: number
  BANKPROJECTDETAIL_ROWNUMBER?: number
  BANKPROJECTDETAIL_PAYMENTDATE?: Date
  BANKPROJECTDETAIL_CURRENCY_ID?: number
  BANKPROJECTDETAIL_TOTALAMOUNT?: number
  BANKPROJECTDETAIL_INTERESTAMOUNT?: number
  BANKPROJECTDETAIL_RENTAMOUNT?: number
  BANKPROJECTDETAIL_TAXRATE?: number
  BANKPROJECTDETAIL_TAXAMOUNT?: number
  BANKPROJECTDETAIL_AMOUNT?: number
  BANKPROJECTDETAIL_DESCRIPTION?: string
  BANKPROJECTDETAIL_PAYMENTCONFIRM?: boolean
  BANKPROJECTDETAIL_REGUSER_ID?: number
  BANKPROJECTDETAIL_REGDATE?: Date
  BANKPROJECTDETAIL_REGIP?: string
  BANKPROJECTDETAIL_BSMV?: number
  BANKPROJECTDETAIL_CURRENCYCODE?: string
  BANKPROJECTDETAIL_CURRENCYNAME?: string
  BANKPROJECTDETAIL_CASHBANKMASTERDATE?: Date
  BANKPROJECTDETAIL_CASHBANKMASTERNUMBER?: number
  CASHBANKDETAIL_BANKPROJECTMASTERPROJECTNUMBER?: string
  CASHBANKDETAIL_BANKPROJECTMASTERDATE?: Date
  CASHBANKDETAIL_BANKPROJECTDETAILROWNUMBER?: number
  CASHBANKDETAIL_IMPORTMASTERSERIALNUMBER?: string
}
