export interface V_BalanceCurTerm {
  ID: number
  BALANCECURTERM_CORP_ID?: number
  BALANCECURTERM_TYPE_ID?: number
  BALANCECURTERM_TERM?: number
  BALANCECURTERM_BALANCE_ID?: number
  BALANCECURTERM_AMOUNT?: number
  BALANCECURTERM_REGUSER_ID?: number
  BALANCECURTERM_REGDATE?: Date
  BALANCECURTERM_REGIP?: string
  CORPORATION_NAME?: string
  BALANCECURTERM_BALANCENUMBER?: string
  BALANCECURTERM_BALANCENAME?: string
  BALANCECURTERM_BALANCESIGN?: number
  BALANCECURTERM_BALANCESUMMARY?: string
  BALANCECURTERM_TYPECODE?: string
  BALANCECURTERM_TYPENAME?: string
}
