export interface V_BalanceCur {
  ID: number
  BALANCECUR_CORP_ID?: number
  BALANCECUR_TYPE_ID?: number
  BALANCECUR_BALANCE_ID?: number
  BALANCECUR_ACCOUNTPLAN_ID?: number
  BALANCECUR_AMOUNT?: number
  BALANCECUR_REGUSER_ID?: number
  BALANCECUR_REGDATE?: Date
  BALANCECUR_REGIP?: string
  CORPORATION_NAME?: string
  BALANCECUR_BALANCENUMBER?: string
  BALANCECUR_BALANCENAME?: string
  BALANCECUR_BALANCESIGN?: number
  BALANCECUR_BALANCESUMMARY?: string
  BALANCECUR_TYPECODE?: string
  BALANCECUR_TYPENAME?: string
  BALANCECUR_ACCOUNTNUMBER?: string
  BALANCECUR_ACCOUNTNAME?: string
}
