export interface V_BalanceAcc {
  ID: number
  BALANCEACC_CORP_ID?: number
  BALANCEACC_TYPE_ID?: number
  BALANCEACC_BALANCE_ID?: number
  BALANCEACC_ACCOUNTPLAN_ID?: number
  BALANCEACC_AMOUNT?: number
  BALANCEACC_REGUSER_ID?: number
  BALANCEACC_REGDATE?: Date
  BALANCEACC_REGIP?: string
  CORPORATION_NAME?: string
  BALANCEACC_BALANCENUMBER?: string
  BALANCEACC_BALANCENAME?: string
  BALANCEACC_BALANCESIGN?: number
  BALANCEACC_BALANCESUMMARY?: string
  BALANCEACC_TYPECODE?: string
  BALANCEACC_TYPENAME?: string
  BALANCEACC_ACCOUNTNUMBER?: string
  BALANCEACC_ACCOUNTNAME?: string
}
