export interface V_BomProcess {
  ID: number
  BOMPROCESS_MASTER_ID: number
  BOMPROCESS_NUMBER?: number
  BOMPROCESS_NAME?: string
  BOMPROCESS_TIME?: number
  BOMPROCESS_DESCRIPTION?: string
  BOMPROCESS_REGUSER_ID?: number
  BOMPROCESS_REGDATE?: Date
  BOMPROCESS_REGIP?: string
  BOMPROCESS_MACHINE_ID?: number
  BOMPROCESS_PROCESS_ID?: number
  BOMPROCESS_PROCESSPARAMETER_ID?: number
  BOMPROCESS_MINIMUMVALUE?: number
  BOMPROCESS_MAXIMUMVALUE?: number
  BOMPROCESS_STANDARTVALUE?: number
  BOMPROCESS_TYPE?: number
  BOMPROCESS_MACHINECODE?: string
  BOMPROCESS_MACHINENAME?: string
  BOMPROCESS_PROCESSCODE?: string
  BOMPROCESS_PROCESSNAME?: string
  BOMPROCESS_PROCESSPARAMETERCODE?: string
  BOMPROCESS_PROCESSPARAMETERNAME?: string
}
