export interface V_BomDemandMaster {
  ID: number
  BOMDEMANDMASTER_CORP_ID?: number
  BOMDEMANDMASTER_SECTION_ID?: number
  BOMDEMANDMASTER_SERIAL_ID?: number
  BOMDEMANDMASTER_YEAR?: number
  BOMDEMANDMASTER_NUMBER?: number
  BOMDEMANDMASTER_DATE?: Date
  BOMDEMANDMASTER_COMPANY_ID?: number
  BOMDEMANDMASTER_DEMANDUSER_ID?: number
  BOMDEMANDMASTER_DESCRIPTION?: string
  BOMDEMANDMASTER_CONFIRM?: boolean
  BOMDEMANDMASTER_SALESCONFIRM?: boolean
  BOMDEMANDMASTER_REGUSER_ID?: number
  BOMDEMANDMASTER_REGDATE?: Date
  BOMDEMANDMASTER_REGIP?: string
  BOMDEMANDMASTER_COMPANYINFO?: string
  BOMDEMANDMASTER_TYPE_ID?: number
  BOMDEMANDMASTER_SECTIONCODE?: string
  BOMDEMANDMASTER_SECTIONNAME?: string
  BOMDEMANDMASTER_SERIALCODE?: string
  BOMDEMANDMASTER_SERIALNAME?: string
  BOMDEMANDMASTER_TYPECODE?: string
  BOMDEMANDMASTER_TYPENAME?: string
  BOMDEMANDMASTER_COMPANYCODE?: string
  BOMDEMANDMASTER_COMPANYNAME?: string
  BOMDEMANDMASTER_DEMANDUSERCODE?: string
}
