export interface V_BomProcessDetail {
  ID: number
  BOMPROCESSDETAIL_MASTER_ID?: number
  BOMPROCESSDETAIL_PROCESS_ID?: number
  BOMPROCESSDETAIL_ITEM_ID?: number
  BOMPROCESSDETAIL_QUANTITY?: number
  BOMPROCESSDETAIL_MACHINE_ID?: number
  BOMPROCESSDETAIL_DESCRIPTION?: string
  BOMPROCESSDETAIL_SEQUENCE?: number
  BOMPROCESSDETAIL_REGUSER_ID?: number
  BOMPROCESSDETAIL_REGDATE?: Date
  BOMPROCESSDETAIL_REGIP?: string
  BOMPROCESSDETAIL_MACHINECODE?: string
  BOMPROCESSDETAIL_MACHINENAME?: string
  BOMPROCESSDETAIL_ITEMNUMBER?: string
  BOMPROCESSDETAIL_ITEMNAME?: string
  BOMPROCESSDETAIL_ITEMUNITCODE?: string
}
