export interface V_BudgetExpenseDetail {
  ID: number
  BUDGETEXPENSEDETAIL_MASTER_ID?: number
  BUDGETEXPENSEDETAIL_EXPENSEPLAN_ID?: number
  BUDGETEXPENSEDETAIL_CURRENCY_ID?: number
  BUDGETEXPENSEDETAIL_AMOUNT1?: number
  BUDGETEXPENSEDETAIL_AMOUNT2?: number
  BUDGETEXPENSEDETAIL_AMOUNT3?: number
  BUDGETEXPENSEDETAIL_AMOUNT4?: number
  BUDGETEXPENSEDETAIL_AMOUNT5?: number
  BUDGETEXPENSEDETAIL_AMOUNT6?: number
  BUDGETEXPENSEDETAIL_AMOUNT7?: number
  BUDGETEXPENSEDETAIL_AMOUNT8?: number
  BUDGETEXPENSEDETAIL_AMOUNT9?: number
  BUDGETEXPENSEDETAIL_AMOUNT10?: number
  BUDGETEXPENSEDETAIL_AMOUNT11?: number
  BUDGETEXPENSEDETAIL_AMOUNT12?: number
  BUDGETEXPENSEDETAIL_AMOUNTTOTAL?: number
  BUDGETEXPENSEDETAIL_REGUSER_ID?: number
  BUDGETEXPENSEDETAIL_REGDATE?: Date
  BUDGETEXPENSEDETAIL_REGIP?: string
  BUDGETEXPENSEDETAIL_EXPENSEPLANCODE?: string
  BUDGETEXPENSEDETAIL_EXPENSEPLANNAME?: string
  BUDGETEXPENSEDETAIL_CURRENCYCODE?: string
  BUDGETEXPENSEDETAIL_CURRENCYNAME?: string
}
