export interface V_BudgetPurchasePriceMaster {
  ID: number
  BUDGETPURCHASEPRICEMASTER_CORP_ID?: number
  BUDGETPURCHASEPRICEMASTER_YEAR?: number
  BUDGETPURCHASEPRICEMASTER_REGUSER_ID?: number
  BUDGETPURCHASEPRICEMASTER_REGDATE?: Date
  BUDGETPURCHASEPRICEMASTER_REGIP?: string
}
