export interface V_BudgetCapacityMaster {
  ID: number
  BUDGETCAPACITYMASTER_CORP_ID?: number
  BUDGETCAPACITYMASTER_SECTION_ID?: number
  BUDGETCAPACITYMASTER_YEAR: number
  BUDGETCAPACITYMASTER_REVISED?: number
  BUDGETCAPACITYMASTER_DESCRIPTION?: string
  BUDGETCAPACITYMASTER_REGUSER_ID?: number
  BUDGETCAPACITYMASTER_REGDATE?: Date
  BUDGETCAPACITYMASTER_REGIP?: string
  BUDGETCAPACITYMASTER_SECTIONCODE?: string
  BUDGETCAPACITYMASTER_SECTIONNAME?: string
}
