export interface V_BudgetMasterAlternative {
  ID: number
  BUDGETMASTERALTERNATIVE_CORP_ID?: number
  BUDGETMASTERALTERNATIVE_SECTION_ID?: number
  BUDGETMASTERALTERNATIVE_TYPE?: number
  BUDGETMASTERALTERNATIVE_YEAR: number
  BUDGETMASTERALTERNATIVE_REVISED?: number
  BUDGETMASTERALTERNATIVE_ALTERNATIVE?: number
  BUDGETMASTERALTERNATIVE_COMPANY_ID?: number
  BUDGETMASTERALTERNATIVE_CURRENCY_ID?: number
  BUDGETMASTERALTERNATIVE_DESCRIPTION?: string
  BUDGETMASTERALTERNATIVE_LIMIT?: number
  BUDGETMASTERALTERNATIVE_REGUSER_ID?: number
  BUDGETMASTERALTERNATIVE_REGDATE?: Date
  BUDGETMASTERALTERNATIVE_REGIP?: string
  BUDGETMASTERALTERNATIVE_COMPANYCODE?: string
  BUDGETMASTERALTERNATIVE_COMPANYNAME?: string
  BUDGETMASTER_SECTIONCODE?: string
  BUDGETMASTERALTERNATIVE_SECTIONNAME?: string
  BUDGETMASTERALTERNATIVE_COMPANYCOUNTRY_ID?: number
  BUDGETMASTERALTERNATIVE_COMPANYKIND_ID?: number
  BUDGETMASTERALTERNATIVE_COMPANYCOUNTRYNAME?: string
  BUDGETMASTERALTERNATIVE_COMPANYKINDNAME?: string
  BUDGETMASTERALTERNATIVE_COMPANYKINDCODE?: string
  BUDGETMASTERALTERNATIVE_REPRESENTATIVE_ID?: number
  BUDGETMASTERALTERNATIVE_CURRENCYCODE?: string
  BUDGETMASTERALTERNATIVE_CURRENCYNAME?: string
}
