export interface V_BudgetGroup {
  ID: number
  GROUPDEFINITION_MASTER_ID?: number
  GROUPDEFINITION_DETAIL_ID?: number
  GROUPDEFINITION_CODE?: string
  GROUPDEFINITION_NAME?: string
  GROUPDEFINITION_GTIP?: string
  GROUPDEFINITION_SUBMASTER_ID?: number
  GROUPDEFINITION_REGUSER_ID?: number
  GROUPDEFINITION_REGDATE?: Date
  GROUPDEFINITION_REGIP?: string
  GROUPDEFINITION_CORP_ID?: number
  BUDGETGROUP_CORP_ID: number
}
