export interface V_BudgetPurchasePriceDetail {
  ID: number
  BUDGETPURCHASEPRICEDETAIL_MASTER_ID?: number
  BUDGETPURCHASEPRICEDETAIL_TYPE?: number
  BUDGETPURCHASEPRICEDETAIL_ITEM_ID?: number
  BUDGETPURCHASEPRICEDETAIL_CURRENCY_ID?: number
  BUDGETPURCHASEPRICEDETAIL_PRICE1?: number
  BUDGETPURCHASEPRICEDETAIL_PRICE2?: number
  BUDGETPURCHASEPRICEDETAIL_PRICE3?: number
  BUDGETPURCHASEPRICEDETAIL_PRICE4?: number
  BUDGETPURCHASEPRICEDETAIL_PRICE5?: number
  BUDGETPURCHASEPRICEDETAIL_PRICE6?: number
  BUDGETPURCHASEPRICEDETAIL_PRICE7?: number
  BUDGETPURCHASEPRICEDETAIL_PRICE8?: number
  BUDGETPURCHASEPRICEDETAIL_PRICE9?: number
  BUDGETPURCHASEPRICEDETAIL_PRICE10?: number
  BUDGETPURCHASEPRICEDETAIL_PRICE11?: number
  BUDGETPURCHASEPRICEDETAIL_PRICE12?: number
  BUDGETPURCHASEPRICEDETAIL_REGUSER_ID?: number
  BUDGETPURCHASEPRICEDETAIL_REGDATE?: Date
  BUDGETPURCHASEPRICEDETAIL_REGIP?: string
  BUDGETPURCHASEPRICEDETAIL_ITEMNUMBER?: string
  BUDGETPURCHASEPRICEDETAIL_ITEMNAME?: string
  BUDGETPURCHASEPRICEDETAIL_CURRENCYCODE?: string
  BUDGETPURCHASEPRICEDETAIL_CURRENCYNAME?: string
}
