export interface V_BudgetMaster {
  ID: number
  BUDGETMASTER_CORP_ID?: number
  BUDGETMASTER_SECTION_ID?: number
  BUDGETMASTER_YEAR: number
  BUDGETMASTER_COMPANY_ID?: number
  BUDGETMASTER_CURRENCY_ID?: number
  BUDGETMASTER_REVISED?: number
  BUDGETMASTER_TYPE?: number
  BUDGETMASTER_DESCRIPTION?: string
  BUDGETMASTER_LIMIT?: number
  BUDGETMASTER_REGUSER_ID?: number
  BUDGETMASTER_REGDATE?: Date
  BUDGETMASTER_REGIP?: string
  BUDGETMASTER_COMPANYCODE?: string
  BUDGETMASTER_COMPANYNAME?: string
  BUDGETMASTER_SECTIONCODE?: string
  BUDGETMASTER_SECTIONNAME?: string
  BUDGETMASTER_COMPANYCOUNTRY_ID?: number
  BUDGETMASTER_COMPANYKIND_ID?: number
  BUDGETMASTER_COMPANYCOUNTRYNAME?: string
  BUDGETMASTER_COMPANYKINDNAME?: string
  BUDGETMASTER_COMPANYKINDCODE?: string
  BUDGETMASTER_REPRESENTATIVE_ID?: number
  BUDGETMASTER_CURRENCYCODE?: string
  BUDGETMASTER_CURRENCYNAME?: string
}
