export interface V_BudgetExpenseMaster {
  ID: number
  BUDGETEXPENSEMASTER_CORP_ID?: number
  BUDGETEXPENSEMASTER_SECTION_ID?: number
  BUDGETEXPENSEMASTER_YEAR: number
  BUDGETEXPENSEMASTER_DEPARTMENT_ID?: number
  BUDGETEXPENSEMASTER_REVISED?: number
  BUDGETEXPENSEMASTER_TYPE?: number
  BUDGETEXPENSEMASTER_REGUSER_ID?: number
  BUDGETEXPENSEMASTER_REGDATE?: Date
  BUDGETEXPENSEMASTER_REGIP?: string
  BUDGETEXPENSEMASTER_DEPARTMENTCODE?: string
  BUDGETEXPENSEMASTER_DEPARTMENTNAME?: string
  BUDGETEXPENSEMASTER_SECTIONCODE?: string
  BUDGETEXPENSEMASTER_SECTIONNAME?: string
}
