export interface V_CashBankMaster {
  ID: number
  CASHBANKMASTER_CORP_ID: number
  CASHBANKMASTER_SECTION_ID: number
  CASHBANKMASTER_YEAR: number
  CASHBANKMASTER_SERIAL_ID: number
  CASHBANKMASTER_NUMBER: number
  CASHBANKMASTER_DATE: Date
  CASHBANKMASTER_TYPE: number
  CASHBANKMASTER_OPERATION_ID: number
  CASHBANKMASTER_ACCOUNTING: boolean
  CASHBANKMASTER_LINK?: string
  CASHBANKMASTER_REF_ID?: number
  CASHBANKMASTER_CONFIRM: boolean
  CASHBANKMASTER_REGUSER_ID: number
  CASHBANKMASTER_REGDATE: Date
  CASHBANKMASTER_REGIP: string
  CASHBANKMASTER_SECTIONCODE?: string
  CASHBANKMASTER_SECTIONNAME?: string
  CASHBANKMASTER_SERIALCODE?: string
  CASHBANKMASTER_SERIALNAME?: string
  CASHBANKMASTER_OPERATIONCODE?: string
  CASHBANKMASTER_OPERATIONNAME?: string
}
