export interface V_CheckParameter {
  ID: number
  CHECKPARAMETER_CORP_ID: number
  CHECKPARAMETER_MOVE_ID: number
  CHECKPARAMETER_CURRENTACCOUNT_ID: number
  CHECKPARAMETER_CURRENCY_ID?: number
  CHECKPARAMETER_TYPE_ID: number
  CHECKPARAMETER_REGUSER_ID: number
  CHECKPARAMETER_REGDATE: Date
  CHECKPARAMETER_REGIP: string
  CHECKPARAMETER_MOVECODE?: string
  CHECKPARAMETER_MOVENAME?: string
  CHECKPARAMETER_TYPECODE?: string
  CHECKPARAMETER_TYPENAME?: string
  CHECKPARAMETER_CURRENCYCODE?: string
  CHECKPARAMETER_CURRENCYNAME?: string
  CHECKPARAMETER_CURRENTNAME?: string
  CHECKPARAMETER_CURRENTMASKNUMBER?: string
}
