export interface V_CompanyContractDetail {
  ID: number
  COMPANYCONTRACTDETAIL_MASTER_ID?: number
  COMPANYCONTRACTDETAIL_DESCRIPTION?: string
  COMPANYCONTRACTDETAIL_IMAGE?: string
  COMPANYCONTRACTDETAIL_REGUSER_ID?: number
  COMPANYCONTRACTDETAIL_REGDATE?: Date
  COMPANYCONTRACTDETAIL_REGIP?: string
}
