export interface V_CompanyNote {
  ID: number
  COMPANYNOTE_COMPANY_ID: number
  COMPANYNOTE_NOTE: string
  COMPANYNOTE_USER_ID: number
  COMPANYNOTE_REGDATE: Date
  COMPANYNOTE_REGUSER_ID: number
  COMPANYNOTE_REGIP: string
  COMPANYNOTE_COMPANYNAME?: string
  COMPANYNOTE_COMPANYCODE?: string
  COMPANYNOTE_USERNAME?: string
}
