export interface V_CompanyRepresentative {
  ID: number
  COMPANYREPRESENTATIVE_COMPANY_ID: number
  COMPANYREPRESENTATIVE_REPRESENTATIVE_ID: number
  COMPANYREPRESENTATIVE_REGDATE: Date
  COMPANYREPRESENTATIVE_REGIP: string
  COMPANYREPRESENTATIVE_REGUSER_ID: number
  COMPANYREPRESENTATIVE_CORP_ID: number
  COMPANYREPRESENTATIVE_COMPANYNAME?: string
  COMPANYREPRESENTATIVE_COMPANYCODE?: string
  COMPANYREPRESENTATIVE_REPRESENTATIVENAME?: string
  COMPANYREPRESENTATIVE_REPRESENTATIVESURNAME?: string
  COMPANYREPRESENTATIVE_REGPERSONNAME?: string
  COMPANYREPRESENTATIVE_REGPERSONSURNAME?: string
}
