export interface V_CompanyGuarantee {
  ID: number
  COMPANYGUARANTEE_CORP_ID: number
  COMPANYGUARANTEE_COMPANY_ID?: number
  COMPANYGUARANTEE_TYPE_ID: number
  COMPANYGUARANTEE_DESCRIPTION?: string
  COMPANYGUARANTEE_AMOUNT: number
  COMPANYGUARANTEE_CURRENCY_ID?: number
  COMPANYGUARANTEE_ENDDATE: Date
  COMPANYGUARANTEE_REGUSER_ID: number
  COMPANYGUARANTEE_REGDATE: Date
  COMPANYGUARANTEE_REGIP: string
  COMPANYGUARANTEE_STARTDATE: Date
  COMPANYGUARANTEE_BANKSECTION?: string
  COMPANYGUARANTEE_BANKDOCNUMBER?: string
  COMPANYGUARANTEE_ISRETURN: boolean
  COMPANYGUARANTEE_RETURNDATE?: Date
  COMPANYGUARANTEE_SUBACCOUNT_ID: number
  COMPANYGUARANTEE_CURRENTACCOUNT_ID?: number
  COMPANYGUARANTEE_COMPANYCODE?: string
  COMPANYGUARANTEE_COMPANYNAME?: string
  COMPANYGUARANTEE_CURRENCYCODE?: string
  COMPANYGUARANTEE_CURRENCYNAME?: string
  COMPANYGUARANTEE_TYPECODE?: string
  COMPANYGUARANTEE_TYPENAME?: string
  COMPANYGUARANTEE_SUBACCOUNTNAME?: string
}
