export interface V_CountAnalysis {
  ID: number
  COUNTANALYSIS_TYPE: number
  COUNTANALYSIS_MASTER_ID: number
  COUNTANALYSIS_QUANTITY: number
  COUNTANALYSIS_STOCKQUANTITY: number
  COUNTANALYSIS_BALANCEQUANTITY: number
  COUNTANALYSIS_BARCODE_ID: number
  COUNTANALYSIS_RACK_ID: number
  COUNTANALYSIS_REGUSER_ID: number
  COUNTANALYSIS_REGDATE: Date
  COUNTANALYSIS_REGIP: string
  COUNTANALYSIS_PIECE: number
  COUNTANALYSIS_STOCKPIECE: number
  COUNTANALYSIS_BALANCEPIECE: number
  COUNTANALYSIS_RACKCODE?: string
  COUNTANALYSIS_RACKNAME?: string
  COUNTANALYSIS_UNITCODE?: string
  COUNTANALYSIS_SURFACENAME?: string
  COUNTANALYSIS_STATENAME?: string
  COUNTANALYSIS_PROFILENUMBER?: string
  COUNTANALYSIS_ITEMNAME?: string
  COUNTANALYSIS_ITEMNUMBER?: string
  COUNTANALYSIS_HARDNESSNAME?: string
  COUNTANALYSIS_COLORNAME?: string
  COUNTANALYSIS_ALLOYNAME?: string
}
