export interface V_CompanyGroup {
  ID: number
  COMPANYGROUP_MASTER_ID?: number
  COMPANYGROUP_GROUPMASTER_ID?: number
  COMPANYGROUP_GROUPDETAIL_ID?: number
  COMPANYGROUP_GROUPDEFINITION_ID?: number
  COMPANYGROUP_REGUSER_ID?: number
  COMPANYGROUP_REGDATE?: Date
  COMPANYGROUP_REGIP?: string
  COMPANYGROUP_GROUPMASTERCODE?: string
  COMPANYGROUP_GROUPMASTERNAME?: string
  COMPANYGROUP_GROUPDETAILCODE?: string
  COMPANYGROUP_GROUPDETAILNAME?: string
  COMPANYGROUP_GROUPDEFINITIONCODE?: string
  COMPANYGROUP_GROUPDEFINITIONNAME?: string
}
