export interface V_CompanyItemDefinition {
  ID: number
  COMPANYITEMDEFINITION_ITEMNUMBER: string
  COMPANYITEMDEFINITION_ITEMNAME: string
  COMPANYITEMDEFINITION_UNIT_ID: number
  COMPANYITEMDEFINITION_REGDATE: Date
  COMPANYITEMDEFINITION_REGIP: string
  COMPANYITEMDEFINITION_REGUSER_ID: number
  COMPANYITEMDEFINITION_COMPANY_ID: number
  COMPANYITEMDEFINITION_UNITCODE?: string
  COMPANYITEMDEFINITION_UNITNAME?: string
}
