export interface V_CorporationParameter {
  ID: number
  CORPORATIONPARAMETER_CORP_ID: number
  CORPORATIONPARAMETER_TYPE_ID: number
  CORPORATIONPARAMETER_RATE_ID?: number
  CORPORATIONPARAMETER_CURRENTACCOUNT_ID?: number
  CORPORATIONPARAMETER_ACCOUNT_ID?: number
  CORPORATIONPARAMETER_REGUSER_ID: number
  CORPORATIONPARAMETER_REGDATE: Date
  CORPORATIONPARAMETER_REGIP: string
  CORPORATIONPARAMETER_TYPECODE?: string
  CORPORATIONPARAMETER_TYPENAME?: string
  CORPORATIONPARAMETER_RATEVALUE?: number
  CORPORATIONPARAMETER_CURRENTNUMBER?: string
  CORPORATIONPARAMETER_CURRENTNAME?: string
  CORPORATIONPARAMETER_CURRENTMASKNUMBER?: string
  CORPORATIONPARAMETER_ACCOUNTNNUMBER?: string
  CORPORATIONPARAMETER_ACCOUNTNAME?: string
  CORPORATIONPARAMETER_ACCOUNTMASKNUMBER?: string
}
