export interface V_CurrentAccountMaster {
  ID: number
  CURRENTACCOUNTMASTER_CORP_ID: number
  CURRENTACCOUNTMASTER_SECTION_ID: number
  CURRENTACCOUNTMASTER_YEAR: number
  CURRENTACCOUNTMASTER_SERIAL_ID: number
  CURRENTACCOUNTMASTER_NUMBER: number
  CURRENTACCOUNTMASTER_DATE: Date
  CURRENTACCOUNTMASTER_OPERATION_ID: number
  CURRENTACCOUNTMASTER_LINK?: string
  CURRENTACCOUNTMASTER_REF_ID?: number
  CURRENTACCOUNTMASTER_REGUSER_ID: number
  CURRENTACCOUNTMASTER_REGDATE: Date
  CURRENTACCOUNTMASTER_REGIP: string
  CURRENTACCOUNTMASTER_ACCOUNTING: boolean
  CURRENTACCOUNTMASTER_CONFIRM: boolean
  CURRENTACCOUNTMASTER_SECTIONCODE?: string
  CURRENTACCOUNTMASTER_SECTIONNAME?: string
  CURRENTACCOUNTMASTER_SERIALCODE?: string
  CURRENTACCOUNTMASTER_SERIALNAME?: string
  CURRENTACCOUNTMASTER_OPERATIONCODE?: string
  CURRENTACCOUNTMASTER_OPERATIONNAME?: string
}
