export interface V_CurrentAccountDetailSub {
  ID: number
  CURRENTACCOUNTDETAILSUB_REGUSER_ID?: number
  CURRENTACCOUNTDETAILSUB_REGDATE?: Date
  CURRENTACCOUNTDETAILSUB_REGIP?: string
  CURRENTACCOUNTDETAILSUB_MASTER_ID?: number
  CURRENTACCOUNTDETAILSUB_DETAIL_ID?: number
  CURRENTACCOUNTDETAILSUB_TYPE_ID?: number
  CURRENTACCOUNTDETAILSUB_DEFINITION_ID?: number
  CURRENTACCOUNTDETAILSUB_TYPECODE?: number
  CURRENTACCOUNTDETAILSUB_TYPENAME?: string
  CURRENTACCOUNTDETAILSUB_DEFINITIONCODE?: string
  CURRENTACCOUNTDETAILSUB_DEFINITIONNAME?: string
}
