export interface V_CurrentAccountPlanCorp {
  ID: number
  CURRENTACCOUNTPLANCORP_CURRENTACCOUNT_ID: number
  CURRENTACCOUNTPLANCORP_CORP_ID: number
  CURRENTACCOUNTPLANCORP_ACCOUNT_ID?: number
  CURRENTACCOUNTPLANCORP_REGUSER_ID: number
  CURRENTACCOUNTPLANCORP_REGDATE: Date
  CURRENTACCOUNTPLANCORP_REGIP: string
  CURRENTACCOUNTPLANCORP_ACCOUNTNAME?: string
  CURRENTACCOUNTPLANCORP_ACCOUNTMASKNUMBER?: string
}
