export interface V_Equipment {
  ID: number
  EQUIPMENT_ITEM_ID?: number
  EQUIPMENT_COMPANY_ID?: number
  EQUIPMENT_NUMBER?: number
  EQUIPMENT_NAME?: string
  EQUIPMENT_PURCHASEDATE?: Date
  EQUIPMENT_CLOSED?: boolean
  EQUIPMENT_CLOSEDATE?: Date
  EQUIPMENT_LIFE?: number
  EQUIPMENT_PASSQUANTITY?: number
  EQUIPMENT_ADDQUANTITY?: number
  EQUIPMENT_USEQUANTITY?: number
  EQUIPMENT_METRAJ?: number
  EQUIPMENT_REGUSER_ID?: number
  EQUIPMENT_REGDATE?: Date
  EQUIPMENT_REGIP?: string
  EQUIPMENT_WEIGHT?: number
  EQUIPMENT_CORP_ID: string
  EQUIPMENT_COMPANYCODE?: string
  EQUIPMENT_COMPANYNAME?: string
  EQUIPMENT_ITEMNUMBER?: string
  EQUIPMENT_ITEMNAME?: string
}
