export interface V_ExpensePlanCorp {
  ID: number
  EXPENSEPLANCORP_EXPENSE_ID: number
  EXPENSEPLANCORP_CORP_ID: number
  EXPENSEPLANCORP_REGUSER_ID: number
  EXPENSEPLANCORP_REGDATE: Date
  EXPENSEPLANCORP_REGIP: string
  EXPENSEPLANCORP_DEPARTMENT_ID?: number
  EXPENSEPLANCORP_ACCOUNT_ID?: number
  EXPENSEPLANCORP_CURRENTACCOUNT_ID?: number
  EXPENSEPLANCORP_CURRENTMASKNUMBER?: string
  EXPENSEPLANCORP_CURRENTNAME?: string
  EXPENSEPLANCORP_ACCOUNTMASKNUMBER?: string
  EXPENSEPLANCORP_ACCOUNTNAME?: string
}
