export interface V_ExpenseDetailSub {
  ID: number
  EXPENSEDETAILSUB_MASTER_ID?: number
  EXPENSEDETAILSUB_DETAIL_ID?: number
  EXPENSEDETAILSUB_TYPE_ID?: number
  EXPENSEDETAILSUB_DEFINITION_ID?: number
  EXPENSEDETAILSUB_REGUSER_ID?: number
  EXPENSEDETAILSUB_REGDATE?: Date
  EXPENSEDETAILSUB_REGIP?: string
  EXPENSEDETAILSUB_TYPECODE?: number
  EXPENSEDETAILSUB_TYPENAME?: string
  EXPENSEDETAILSUB_DEFINITIONCODE?: string
  EXPENSEDETAILSUB_DEFINITIONNAME?: string
}
