export interface V_ExpenseDemandDetailSub {
  ID: number
  EXPENSEDEMANDDETAILSUB_MASTER_ID?: string
  EXPENSEDEMANDDETAILSUB_DETAIL_ID?: number
  EXPENSEDEMANDDETAILSUB_TYPE_ID?: number
  EXPENSEDEMANDDETAILSUB_DEFINITION_ID?: number
  EXPENSEDEMANDDETAILSUB_REGUSER_ID?: number
  EXPENSEDEMANDDETAILSUB_REGDATE?: Date
  EXPENSEDEMANDDETAILSUB_REGIP?: string
  EXPENSEDEMANDDETAILSUB_TYPECODE?: number
  EXPENSEDEMANDDETAILSUB_TYPENAME?: string
  EXPENSEDEMANDDETAILSUB_DEFINITIONCODE?: string
  EXPENSEDEMANDDETAILSUB_DEFINITIONNAME?: string
}
