export interface V_ImportDocument {
  IMPORTDOCUMENT_REGUSER_ID?: number
  IMPORTDOCUMENT_REGDATE?: Date
  IMPORTDOCUMENT_REGIP?: string
  ID: number
  IMPORTDOCUMENT_MASTER_ID?: number
  IMPORTDOCUMENT_DOCUMENT_ID?: number
  IMPORTDOCUMENT_QUANTITY?: number
  IMPORTDOCUMENT_TYPE_ID?: number
  IMPORTDOCUMENT_DESCRIPTION?: string
  IMPORTDOCUMENT_DOCUMENTCODE?: string
  IMPORTDOCUMENT_DOCUMENTNAME?: string
  IMPORTDOCUMENT_TYPECODE?: string
  IMPORTDOCUMENT_TYPENAME?: string
}
