export interface V_ImportContainer {
  IMPORTCONTAINER_REGUSER_ID?: number
  IMPORTCONTAINER_REGDATE?: Date
  IMPORTCONTAINER_REGIP?: string
  ID: number
  IMPORTCONTAINER_MASTER_ID?: number
  IMPORTCONTAINER_NUMBER?: string
  IMPORTCONTAINER_DESCRIPTION?: string
}
