export interface V_ImportExpenseDetail {
  ID: number
  IMPORTEXPENSEDETAIL_MASTER_ID?: number
  IMPORTEXPENSEDETAIL_IMPORTMASTER_ID?: number
  IMPORTEXPENSEDETAIL_ITEM_ID?: number
  IMPORTEXPENSEDETAIL_UNIT_ID?: number
  IMPORTEXPENSEDETAIL_AMOUNT?: number
  IMPORTEXPENSEDETAIL_EXPENSEAMOUNT?: number
  IMPORTEXPENSEDETAIL_PASSIVE?: boolean
  IMPORTEXPENSEDETAIL_REGUSER_ID?: number
  IMPORTEXPENSEDETAIL_REGDATE?: Date
  IMPORTEXPENSEDETAIL_REGIP?: string
  IMPORTEXPENSEDETAIL_ITEMNUMBER: string
  IMPORTEXPENSEDETAIL_ITEMNAME: string
  IMPORTEXPENSEDETAIL_UNITCODE?: string
  IMPORTEXPENSEDETAIL_UNITNAME?: string
}
