export interface V_ImportContract {
  ID: number
  IMPORTCONTRACT_MASTER_ID: number
  IMPORTCONTRACT_PURCHASECONTRACTMASTER_ID?: number
  IMPORTCONTRACT_REGUSER_ID?: number
  IMPORTCONTRACT_REGDATE?: Date
  IMPORTCONTRACT_REGIP?: string
  IMPORTCONTRACT_PURCHASECONTRACTMASTERDATE?: Date
  IMPORTCONTRACT_PURCHASECONTRACTMASTERNUMBER?: number
  IMPORTCONTRACT_PURCHASECONTRACTMASTERSERIALNAME?: string
  IMPORTCONTRACT_PURCHASECONTRACTMASTERCOMPANYCONTRACTNUMBER?: string
}
