export interface V_ImportDetail {
  ID: number
  IMPORTDETAIL_MASTER_ID: number
  IMPORTDETAIL_PURCHASEINVOICEMASTER_ID?: number
  IMPORTDETAIL_DESCRIPTION?: string
  IMPORTDETAIL_REGUSER_ID: number
  IMPORTDETAIL_REGDATE: Date
  IMPORTDETAIL_REGIP: string
  IMPORTDETAIL_PURCHASEINVOICEMASTERNUMBER?: number
  IMPORTDETAIL_PURCHASEINVOICEMASTERCOMPANYNAME?: string
  IMPORTDETAIL_PURCHASEINVOICEMASTERDATE?: Date
  IMPORTDETAIL_PURCHASEINVOICEMASTERDOCUMENTNUMBER?: string
  IMPORTDETAIL_PURCHASEINVOICEMASTERDOCUMENTDATE?: Date
  IMPORTDETAIL_PURCHASEINVOICEMASTERSERIALNAME?: string
  IMPORTDETAIL_PURCHASEINVOICEMASTERPAYMENTNAME?: string
  IMPORTDETAIL_PURCHASEINVOICEMASTERPAYMENTDATE?: Date
}
