export interface V_ItemCompany {
  ID: number
  ITEMCOMPANY_ITEM_ID?: number
  ITEMCOMPANY_COMPANY_ID?: number
  ITEMCOMPANY_REGUSER_ID?: number
  ITEMCOMPANY_REGDATE?: Date
  ITEMCOMPANY_REGIP?: string
  ITEMCOMPANY_COMPANYITEMNUMBER?: string
  ITEMCOMPANY_WEIGHT?: number
  ITEMCOMPANY_HEIGHT?: number
  ITEMCOMPANY_DESCRIPTION?: string
  ITEMCOMPANY_HEIGHTMULTIPLIER?: number
  ITEMCOMPANY_SURFACE?: string
  ITEMCOMPANY_COMPANYCODE?: string
  ITEMCOMPANY_COMPANYNAME?: string
  ITEMCOMPANY_COUNTRYCODE?: string
  ITEMCOMPANY_COUNTRYNAME?: string
}
