export interface V_ItemWaste {
  ID: number
  ITEMWASTE_ITEM_ID?: number
  ITEMWASTE_WASTEITEM_ID?: number
  ITEMWASTE_REGUSER_ID?: number
  ITEMWASTE_REGDATE?: Date
  ITEMWASTE_REGIP?: string
  ITEMWASTE_ITEMNUMBER?: string
  ITEMWASTE_ITEMNAME?: string
  ITEMWASTE_ITEMNUMBERNAME?: string
  ITEMWASTE_WASTEITEMNUMBER?: string
  ITEMWASTE_WASTEITEMNAME?: string
  ITEMWASTE_WASTEITEMNUMBERNAME?: string
}
