export interface V_ItemCostDetail {
  ID: number
  ITEMCOSTDETAIL_MASTER_ID: number
  ITEMCOSTDETAIL_DESCRIPTION?: string
  ITEMCOSTDETAIL_ITEM_ID: number
  ITEMCOSTDETAIL_QUANTITY: number
  ITEMCOSTDETAIL_UNIT_ID: number
  ITEMCOSTDETAIL_PRICE_TYPE?: number
  ITEMCOSTDETAIL_PRICE?: number
  ITEMCOSTDETAIL_AMOUNT?: number
  ITEMCOSTDETAIL_REGUSER_ID: number
  ITEMCOSTDETAIL_REGDATE: Date
  ITEMCOSTDETAIL_REGIP: string
  ITEMCOSTDETAIL_ITEMNUMBER?: string
  ITEMCOSTDETAIL_ITEMNAME?: string
  ITEMCOSTDETAIL_UNITCODE?: string
  ITEMCOSTDETAIL_UNITNAME?: string
}
