export interface V_ItemRework {
  ID: number
  ITEMREWORK_ITEM_ID?: number
  ITEMREWORK_REWORKITEM_ID?: number
  ITEMREWORK_REGUSER_ID?: number
  ITEMREWORK_REGDATE?: Date
  ITEMREWORK_REGIP?: string
  ITEMREWORK_REWORKITEM_NUMBER?: string
  ITEMREWORK_REWORKITEM_NAME?: string
}
