export interface V_ItemEmpty {
  ID: number
  ITEMEMPTY_REGUSER_ID?: number
  ITEMEMPTY_REGDATE?: Date
  ITEMEMPTY_REGIP?: string
  ITEMEMPTY_MASTER_ID?: number
  ITEMEMPTY_ITEM_ID?: number
  ITEMEMPTY_UNIT_ID?: number
  ITEMEMPTY_QUANTITY?: number
  ITEMEMPTY_ITEMNUMBER?: string
  ITEMEMPTY_ITEMNAME?: string
  ITEMEMPTY_UNITCODE?: string
  ITEMEMPTY_UNITNAME?: string
}
