export interface V_ItemAccount {
  ID: number
  ITEMACCOUNT_ITEM_ID: number
  ITEMACCOUNT_CORP_ID: number
  ITEMACCOUNT_TYPE_ID: number
  ITEMACCOUNT_TYPEDETAIL_ID: number
  ITEMACCOUNT_ACCOUNT_ID?: number
  ITEMACCOUNT_CURRENTACCOUNT_ID: number
  ITEMACCOUNT_RATE_ID?: number
  ITEMACCOUNT_REGUSER_ID: number
  ITEMACCOUNT_REGDATE: Date
  ITEMACCOUNT_REGIP: string
  ITEMACCOUNT_TYPECODE?: string
  ITEMACCOUNT_TYPENAME?: string
  ITEMACCOUNT_TYPEDETAILCODE?: string
  ITEMACCOUNT_TYPEDETAILNAME?: string
  ITEMACCOUNT_ACCOUNTNUMBER?: string
  ITEMACCOUNT_ACCOUNTMASKNUMBER?: string
  ITEMACCOUNT_ACCOUNTNAME?: string
  ITEMACCOUNT_CURRENTNUMBER?: string
  ITEMACCOUNT_CURRENTMASKNUMBER?: string
  ITEMACCOUNT_CURRENTNAME?: string
}
