export interface V_ItemProperty {
  ID: number
  ITEMPROPERTY_REGUSER_ID?: number
  ITEMPROPERTY_REGDATE?: Date
  ITEMPROPERTY_REGIP?: string
  ITEMPROPERTY_ITEM_ID?: number
  ITEMPROPERTY_PROPERTY_ID?: number
  ITEMPROPERTY_DESCRIPTION?: string
  ITEMPROPERTY_ITEMNUMBER?: string
  ITEMPROPERTY_ITEMNAME?: string
  ITEMPROPERTY_PROPERTYCODE?: string
  ITEMPROPERTY_PROPERTYNAME?: string
}
