export interface V_ItemDocument {
  ID: number
  ITEMDOCUMENT_ITEM_ID?: number
  ITEMDOCUMENT_FILETYPE?: string
  ITEMDOCUMENT_TYPE_ID?: number
  ITEMDOCUMENT_URL?: string
  ITEMDOCUMENT_DESCRIPTOIN?: string
  ITEMDOCUMENT_ACTIVE?: boolean
  ITEMDOCUMENT_PURCHASEDOCUMENT?: boolean
  ITEMDOCUMENT_REGUSER_ID?: number
  ITEMDOCUMENT_REGDATE?: Date
  ITEMDOCUMENT_REGIP?: string
  ITEMDOCUMENT_TYPECODE?: string
  ITEMDOCUMENT_TYPENAME?: string
}
