export interface V_ItemDimension {
  ID: number
  ITEMDIMENSION_REGUSER_ID?: number
  ITEMDIMENSION_REGDATE?: Date
  ITEMDIMENSION_REGIP?: string
  ITEMDIMENSION_CORP_ID?: number
  ITEMDIMENSION_ITEM_ID?: number
  ITEMDIMENSION_DIMENSIONMASTER_ID?: number
  ITEMDIMENSION_DIMENSIONDETAIL_ID?: number
  ITEMDIMENSION_OTHERCODE?: string
  ITEMDIMENSION_SHOW?: boolean
  ITEMDIMENSION_DEFAULT?: boolean
  ITEMDIMENSION_TYPE_ID?: number
  ITEMDIMENSION_DIMENSIONMASTERCODE?: string
  ITEMDIMENSION_DIMENSIONDETAILCODE?: string
  ITEMDIMENSION_DIMENSIONDETAILNAME?: string
}
