export interface V_ItemEquivalent {
  ID: number
  ITEMEQUIVALENT_ITEM_ID?: number
  ITEMEQUIVALENT_EQUIVALENTITEM_ID?: number
  ITEMEQUIVALENT_REGUSER_ID?: number
  ITEMEQUIVALENT_REGDATE?: Date
  ITEMEQUIVALENT_REGIP?: string
  ITEMREWORK_EQUIVALENTITEM_NUMBER?: string
  ITEMEQUIVALENT_EQUIVALENTITEM_NAME?: string
}
