export interface V_ItemGroup {
  ID: number
  ITEMGROUP_MASTER_ID?: number
  ITEMGROUP_GROUPMASTER_ID?: number
  ITEMGROUP_GROUPDETAIL_ID?: number
  ITEMGROUP_GROUPDEFINITION_ID?: number
  ITEMGROUP_REGUSER_ID?: number
  ITEMGROUP_REGDATE?: Date
  ITEMGROUP_REGIP?: string
  ITEMGROUP_GROUPMASTERCODE?: string
  ITEMGROUP_GROUPMASTERNAME?: string
  ITEMGROUP_GROUPDETAILCODE?: string
  ITEMGROUP_GROUPDETAILNAME?: string
  ITEMGROUP_GROUPDEFINITIONCODE?: string
  ITEMGROUP_GROUPDEFINITIONNAME?: string
}
