export interface V_MaintenanceOrderPerson {
  ID: number
  MAINTENANCEORDERPERSON_MASTER_ID?: number
  MAINTENANCEORDERPERSON_TITLE_ID?: number
  MAINTENANCEORDERPERSON_PERSON_ID?: number
  MAINTENANCEORDERPERSON_REGUSER_ID?: number
  MAINTENANCEORDERPERSON_REGDATE?: Date
  MAINTENANCEORDERPERSON_REGIP?: string
  PARAMETERDETAIL_CODE?: string
  PARAMETERDETAIL_NAME?: string
  PERSON_NAME?: string
  PERSON_SURNAME?: string
}
