export interface V_MaterialDemandDetail {
  ID: number
  MATERIALDEMANDDETAIL_MASTER_ID?: number
  MATERIALDEMANDDETAIL_ITEM_ID?: number
  MATERIALDEMANDDETAIL_QUANTITY?: number
  MATERIALDEMANDDETAIL_UNIT_ID?: number
  MATERIALDEMANDDETAIL_EXPENSEPLAN_ID?: number
  MATERIALDEMANDDETAIL_DESCRIPTION?: string
  MATERIALDEMANDDETAIL_REGUSER_ID?: number
  MATERIALDEMANDDETAIL_REGDATE?: Date
  MATERIALDEMANDDETAIL_REGIP?: string
  MATERIALDEMANDDETAIL_ITEMNUMBER?: string
  MATERIALDEMANDDETAIL_ITEMNAME?: string
  MATERIALDEMANDDETAIL_UNITCODE?: string
  MATERIALDEMANDDETAIL_UNITNAME?: string
  MATERIALDEMANDDETAIL_PLANMASKACCNUMBER?: string
  MATERIALDEMANDDETAIL_PLANNAME?: string
}
