export interface V_MaintenanceDescPerson {
  ID: number
  MAINTENANCEDESCPERSON_MASTER_ID?: number
  MAINTENANCEDESCPERSON_TITLE_ID?: number
  MAINTENANCEDESCPERSON_REGUSER_ID?: number
  MAINTENANCEDESCPERSON_REGDATE?: Date
  MAINTENANCEDESCPERSON_REGIP?: string
  MAINTENANCEDESCPERSON_TITLE_CODE?: string
  MAINTENANCEDESCPERSON_TITLE_NAME?: string
}
