export interface V_MaintenanceDescDetail {
  ID: number
  MAINTENANCEDESCDETAIL_MASTER_ID?: number
  MAINTENANCEDESCDETAIL_TYPE_ID?: number
  MAINTENANCEDESCDETAIL_PIECE_ID?: number
  MAINTENANCEDESCDETAIL_PIECEDESCRIPTION?: string
  MAINTENANCEDESCDETAIL_QUANTITY?: number
  MAINTENANCEDESCDETAIL_DESCRIPTION?: string
  MAINTENANCEDESCDETAIL_REGUSER_ID?: number
  MAINTENANCEDESCDETAIL_REGDATE?: Date
  MAINTENANCEDESCDETAIL_REGIP?: string
  MAINTENANCEDESCDETAIL_TYPECODE?: string
  MAINTENANCEDESCDETAIL_TYPENAME?: string
  MAINTENANCEDESCDETAIL_PIECECODE?: string
  MAINTENANCEDESCDETAIL_PIECENAME?: string
}
