export interface V_MaintenanceOrderDetail {
  ID: number
  MAINTENANCEORDERDETAIL_MASTER_ID?: number
  MAINTENANCEORDERDETAIL_TYPE_ID?: number
  MAINTENANCEORDERDETAIL_PIECE_ID?: number
  MAINTENANCEORDERDETAIL_PIECEDESCRIPTION?: string
  MAINTENANCEORDERDETAIL_QUANTITY?: number
  MAINTENANCEORDERDETAIL_DESCRIPTION?: string
  MAINTENANCEORDERDETAIL_MAINTENANCEDESCDETAIL_ID?: number
  MAINTENANCEORDERDETAIL_REGUSER_ID?: number
  MAINTENANCEORDERDETAIL_REGDATE?: Date
  MAINTENANCEORDERDETAIL_REGIP?: string
  MAINTENANCEORDERDETAIL_TYPECODE?: string
  MAINTENANCEORDERDETAIL_TYPENAME?: string
  MAINTENANCEORDERDETAIL_PIECECODE?: string
  MAINTENANCEORDERDETAIL_PIECENAME?: string
  MAINTENANCEDESCMASTER_NUMBER?: number
  MAINTENANCEDESCMASTER_NAME?: string
}
