export interface V_ModuleNotification {
  ID: number
  MODULENOTIFICATION_MASTER_ID: number
  MODULENOTIFICATION_USER_ID: number
  MODULENOTIFICATION_REGDATE: Date
  MODULENOTIFICATION_REGIP: string
  MODULENOTIFICATION_REGUSER_ID: number
  MODULENOTIFICATION_USERNAME?: string
  MODULENOTIFICATION_USERSURNAME?: string
  MODULENOTIFICATION_USEREMAIL?: string
}
