export interface V_MoldMaster {
  ID: number
  MOLDMASTER_NUMBER: number
  MOLDMASTER_DATE: Date
  MOLDMASTER_TYPE_ID: number
  MOLDMASTER_REGDATE: Date
  MOLDMASTER_REGIP: string
  MOLDMASTER_REGUSER_ID: number
  MOLDMASTER_SECTION_ID: number
  MOLDMASTER_CORP_ID: number
  MOLDMASTER_COMPANY_ID?: number
  MOLDMASTER_SECTIONCODE?: string
  MOLDMASTER_SECTIONNAME?: string
  MOLDMASTER_TYPECODE?: string
  MOLDMASTER_TYPENAME?: string
  MOLMASTER_COMPANY_CODE?: string
  MOLDMASTER_COMPANYNAME?: string
}
