export interface V_PlantMaster {
  ID: number
  PLANTMASTER_CORP_ID: number
  PLANTMASTER_NUMBER: number
  PLANTMASTER_NAME: string
  PLANTMASTER_REFNO?: string
  PLANTMASTER_TARGETSTORE_ID: number
  PLANTMASTER_REGUSER_ID: number
  PLANTMASTER_REGDATE: Date
  PLANTMASTER_REGIP: string
  PLANTMASTER_SOURCESTORE_ID: number
  PLANTMASTER_SECTION_ID: number
  PLANTMASTER_GROUP_ID: number
  PLANTMASTER_GROUPCODE?: string
  PLANTMASTER_GROUPNAME?: string
}
