export interface V_PlantDetail {
  ID: number
  PLANTDETAIL_MASTER_ID: number
  PLANTDETAIL_PLANTMACHINE_ID: number
  PLANTDETAIL_REGUSER_ID: number
  PLANTDETAIL_REGDATE: Date
  PLANTDETAIL_REGIP: string
  PLANTDETAIL_PLANTMACHINENUMBER?: number
  PLANTDETAIL_PLANTMACHINENAME?: string
}
