export interface V_ProjectDescription {
  ID: number
  PROJECTDESCRIPTION_MASTER_ID?: number
  PROJECTDESCRIPTION_INFO?: string
  PROJECTDESCRIPTION_TYPE_ID?: number
  PROJECTDESCRIPTION_REGUSER_ID?: number
  PROJECTDESCRIPTION_REGDATE?: Date
  PROJECTDESCRIPTION_REGIP?: string
  PROJECTDESCRIPTION_DATE?: Date
  PROJECTDESCRIPTION_TYPECODE?: string
  PROJECTDESCRIPTION_TYPENAME?: string
}
