export interface V_ProductionReworkSub {
  ID: number
  PRODUCTIONREWORKSUB_MASTER_ID?: number
  PRODUCTIONREWORKSUB_DETAIL_ID?: number
  PRODUCTIONREWORKSUB_BOMMASTER_ID?: number
  PRODUCTIONREWORKSUB_ITEM_ID?: number
  PRODUCTIONREWORKSUB_UNIT_ID?: number
  PRODUCTIONREWORKSUB_BOMQUANTITY?: number
  PRODUCTIONREWORKSUB_REALQUANTITY?: number
  PRODUCTIONREWORKSUB_REGUSER_ID?: number
  PRODUCTIONREWORKSUB_REGDATE?: Date
  PRODUCTIONREWORKSUB_REGIP?: string
  PRODUCTIONREWORKSUB_ITEMNUMBER?: string
  PRODUCTIONREWORKSUB_ITEMNAME?: string
  PRODUCTIONREWORKSUB_UNITCODE?: string
  PRODUCTIONREWORKSUB_UNITNAME?: string
}
