export interface V_ProfileInsulation {
  ID: number
  PROFILEINSULATION_TYPE: boolean
  PROFILEINSULATION_PROFILE_ID?: number
  PROFILEINSULATION_MASTER_ID: number
  PROFILEINSULATION_ORDER: number
  PROFILEINSULATION_PIECE: number
  PROFILEINSULATION_GRAMMAGE: number
  PROFILEINSULATION_REGDATE: Date
  PROFILEINSULATION_REGIP: string
  PROFILEINSULATION_REGUSER_ID: number
  PROFILEINSULATION_ITEM_ID?: number
  PROFILEINSULATION_PROFILENUMBER?: string
  PROFILEINSULATION_PROFILENAME?: string
  PROFILEINSULATION_ITEMNUMBER?: string
  PROFILEINSULATION_ITEMNAME?: string
}
