export interface V_ProductionDetailSub {
  ID: number
  PRODUCTIONDETAILSUB_DETAIL_ID?: number
  PRODUCTIONDETAILSUB_ITEM_ID: number
  PRODUCTIONDETAILSUB_UNIT_ID: number
  PRODUCTIONDETAILSUB_QUANTITY: number
  PRODUCTIONDETAILSUB_REGUSER_ID: number
  PRODUCTIONDETAILSUB_REGDATE: Date
  PRODUCTIONDETAILSUB_REGIP: string
  PRODUCTIONDETAILSUB_PIECE: number
  PRODUCTIONDETAILSUB_LENGTH: number
  PRODUCTIONDETAILSUB_PRODUCTIONMOLD_ID?: number
  PRODUCTIONDETAILSUB_DIAMETER?: number
  PRODUCTIONDETAILSUB_LOTNUMBER?: string
  PRODUCTIONDETAILSUB_ITEMNUMBER?: string
  PRODUCTIONDETAILSUB_ITEMNAME?: string
  PRODUCTIONDETAILSUB_UNITCODE?: string
  PRODUCTIONDETAILSUB_UNITNAME?: string
}
