export interface V_ProductionProgMaster {
  ID: number
  PRODUCTIONPROGMASTER_CORP_ID: number
  PRODUCTIONPROGMASTER_SECTION_ID: number
  PRODUCTIONPROGMASTER_YEAR: number
  PRODUCTIONPROGMASTER_NUMBER: number
  PRODUCTIONPROGMASTER_DATE: Date
  PRODUCTIONPROGMASTER_CONFIRM: boolean
  PRODUCTIONPROGMASTER_REGUSER_ID: number
  PRODUCTIONPROGMASTER_REGDATE: Date
  PRODUCTIONPROGMASTER_REGIP: string
  PRODUCTIONPROGMASTER_PLANT_ID: number
  PRODUCTIONPROGMASTER_SERIAL_ID: number
  PRODUCTIONPROGMASTER_CLOSED: boolean
  PRODUCTIONPROGMASTER_SERIALCODE?: string
  PRODUCTIONPROGMASTER_SERIALNAME?: string
  PRODUCTIONPROGMASTER_SECTIONCODE?: string
  PRODUCTIONPROGMASTER_SECTIONNAME?: string
  PRODUCTIONPROGMASTER_PLANTCODE?: string
  PRODUCTIONPROGMASTER_PLANTNAME?: string
}
