export interface V_ProductionRework {
  ID: number
  PRODUCTIONREWORK_MASTER_ID?: number
  PRODUCTIONREWORK_ITEM_ID?: number
  PRODUCTIONREWORK_UNIT_ID?: number
  PRODUCTIONREWORK_QUANTITY?: number
  PRODUCTIONREWORK_LOTNUMBER?: string
  PRODUCTIONREWORK_PRODUCTIONDATE?: Date
  PRODUCTIONREWORK_EXPIRATIONDATE?: Date
  PRODUCTIONREWORK_DESCRIPTION?: string
  PRODUCTIONREWORK_BARCODEPRINT?: boolean
  PRODUCTIONREWORK_REGUSER_ID?: number
  PRODUCTIONREWORK_REGDATE?: Date
  PRODUCTIONREWORK_REGIP?: string
  PRODUCTIONREWORK_ITEMNUMBER?: string
  PRODUCTIONREWORK_ITEMNAME?: string
  PRODUCTIONREWORK_UNITCODE?: string
  PRODUCTIONREWORK_UNITNAME?: string
}
