export interface V_ProductionOrderMaster {
  ID: number
  PRODUCTIONORDERMASTER_CORP_ID: number
  PRODUCTIONORDERMASTER_SECTION_ID: number
  PRODUCTIONORDERMASTER_YEAR: number
  PRODUCTIONORDERMASTER_NUMBER: number
  PRODUCTIONORDERMASTER_DATE: Date
  PRODUCTIONORDERMASTER_REGUSER_ID: number
  PRODUCTIONORDERMASTER_REGDATE: Date
  PRODUCTIONORDERMASTER_REGIP: string
  PRODUCTIONORDERMASTER_CLOSED: boolean
  PRODUCTIONORDERMASTER_SERIAL_ID: number
  PRODUCTIONORDERMASTER_CONFIRM: boolean
  PRODUCTIONORDERMASTER_SECTIONNAME?: string
  PRODUCTIONORDERMASTER_SECTIONCODE?: string
  PRODUCTIONORDERMASTER_SERIALCODE?: string
  PRODUCTIONORDERMASTER_SERIALNAME?: string
}
