export interface V_ProductionPlanMaster {
  ID: number
  PRODUCTIONPLANMASTER_REGUSER_ID?: number
  PRODUCTIONPLANMASTER_REGDATE?: Date
  PRODUCTIONPLANMASTER_REGIP?: string
  PRODUCTIONPLANMASTER_CORP_ID?: number
  PRODUCTIONPLANMASTER_SECTION_ID?: number
  PRODUCTIONPLANMASTER_YEAR?: number
  PRODUCTIONPLANMASTER_NUMBER?: number
  PRODUCTIONPLANMASTER_FACTORY_ID?: number
  PRODUCTIONPLANMASTER_DATE?: Date
  PRODUCTIONPLANMASTER_CONFIRM?: boolean
  PRODUCTIONPLANMASTER_CLOSED?: number
  PRODUCTIONPLANMASTER_DESCRIPTION?: string
  PRODUCTIONPLANMASTER_SECTIONCODE?: string
  PRODUCTIONPLANMASTER_SECTIONNAME?: string
  PRODUCTIONPLANMASTER_FACTORYCODE?: string
  PRODUCTIONPLANMASTER_FACTORYNAME?: string
}
