export interface V_ProductionPersonCount {
  ID: number
  PRODUCTIONPERSONCOUNT_DATE?: Date
  PRODUCTIONPERSONCOUNT_COUNT?: number
  PRODUCTIONPERSONCOUNT_SECTION_ID?: number
  PRODUCTIONPERSONCOUNT_INFO?: string
  PRODUCTIONPERSONCOUNT_REGUSER_ID?: number
  PRODUCTIONPERSONCOUNT_REGDATE?: Date
  PRODUCTIONPERSONCOUNT_REGIP?: string
}
