export interface V_ProjectPerson {
  ID: number
  PROJECTPERSON_MASTER_ID?: number
  PROJECTPERSON_PERSON_ID?: number
  PROJECTPERSON_STARTDATE?: Date
  PROJECTPERSON_ENDDATE?: Date
  PROJECTPERSON_RATE?: number
  PROJECTPERSON_REGUSER_ID?: number
  PROJECTPERSON_REGDATE?: Date
  PROJECTPERSON_REGIP?: string
  PROJECTPERSON_PERSONNUMBER?: string
  PROJECTPERSON_PERSONNAME?: string
}
