export interface V_ProductionLimit {
  ID: number
  PRODUCTIONLIMIT_YEAR?: number
  PRODUCTIONLIMIT_TYPE?: number
  PRODUCTIONLIMIT_PLANT_ID?: number
  PRODUCTIONLIMIT_1ITEM_ID?: number
  PRODUCTIONLIMIT_2ITEM_ID?: number
  PRODUCTIONLIMIT_1GROUP_ID?: number
  PRODUCTIONLIMIT_2GROUP_ID?: number
  PRODUCTIONLIMIT_REGUSER_ID?: number
  PRODUCTIONLIMIT_REGDATE?: Date
  PRODUCTIONLIMIT_REGIP?: string
  PLANTMASTER_NUMBER?: string
  ITEM_NUMBER1?: string
  ITEM_NAME1?: string
  ITEM_NUMBER2?: string
  ITEM_NAME2?: string
  GRPUPDEFINITION_CODE1?: string
  GROUPDEFINITION_NAME1?: string
  GRPUPDEFINITION_CODE2?: string
  GROUPDEFINITION_NAME2?: string
}
