export interface V_ProductionShift {
  ID: number
  PRODUCTIONSHIFT_CORP_ID?: number
  PRODUCTIONSHIFT_SECTION_ID?: number
  PRODUCTIONSHIFT_CODE_ID?: number
  PRODUCTIONSHIFT_TYPE_ID?: number
  PRODUCTIONSHIFT_INFO?: string
  PRODUCTIONSHIFT_REGUSER_ID?: number
  PRODUCTIONSHIFT_REGDATE?: Date
  PRODUCTIONSHIFT_REGIP?: string
  PRODUCTIONSHIFT_RUNTIME?: string
}
