export interface V_ProductionMaster {
  ID: number
  PRODUCTIONMASTER_REGUSER_ID: number
  PRODUCTIONMASTER_REGDATE: Date
  PRODUCTIONMASTER_REGIP: string
  PRODUCTIONMASTER_CORP_ID: number
  PRODUCTIONMASTER_SECTION_ID: number
  PRODUCTIONMASTER_YEAR: number
  PRODUCTIONMASTER_SHIFT_ID: number
  PRODUCTIONMASTER_PLANTMASTER_ID: number
  PRODUCTIONMASTER_DATE: Date
  PRODUCTIONMASTER_NUMBER: number
  PRODUCTIONMASTER_USER_ID: number
  PRODUCTIONMASTER_CONFIRM: boolean
  PRODUCTIONMASTER_EMPLOYEES: number
  PRODUCTIONMASTER_HOURS: number
  PRODUCTIONMASTER_SECTIONCODE?: string
  PRODUCTIONMASTER_SECTIONNAME?: string
  PRODUCTIONMASTER_SHIFTCODE?: string
  PRODUCTIONMASTER_SHIFTNAME?: string
  PRODUCTIONMASTER_PLANTMASTERNUMBER?: number
  PRODUCTIONMASTER_PLANTMASTERNAME?: string
  PRODUCTIONMASTER_PLANTGROUPCODE?: string
  PRODUCTIONMASTER_PLANTGROUPNAME?: string
  PRODUCTIONMASTER_USERNAME?: string
}
