export interface V_ProductionStopHelp {
  ID: number
  PRODUCTIONSTOPDETAIL_CODE?: string
  PRODUCTIONSTOPDETAIL_NAME?: string
  PRODUCTIONSTOPMASTER_CODE?: string
  PRODUCTIONSTOPMASTER_NAME?: string
  PRODUCTIONSTOPMASTER_ID?: number
  PRODUCTIONSTOPMASTER_CORP_ID?: number
  PRODUCTIONSTOPHELP_CORP_ID?: number
}
