export interface V_ProductionWaste {
  ID: number
  PRODUCTIONWASTE_DESC?: string
  PRODUCTIONWASTE_QUANTITY: number
  PRODUCTIONWASTE_DETAIL_ID: number
  PRODUCTIONWASTE_REGUSER_ID: number
  PRODUCTIONWASTE_REGDATE: Date
  PRODUCTIONWASTE_REGIP: string
  PRODUCTIONWASTE_PIECE: number
  PRODUCTIONWASTE_REASON_ID?: number
  PRODUCTIONWASTE_PLANT_ID?: number
  PRODUCTIONMASTER_REASONCODE?: string
  PRODUCTIONMASTER_REASONNAME?: string
  PRODUCTIONMASTER_PLANTCODE?: string
  PRODUCTIONMASTER_PLANTNAME?: string
}
