export interface V_PurchaseDemandDetail {
  ID: number
  PURCHASEDEMANDDETAIL_MASTER_ID: number
  PURCHASEDEMANDDETAIL_ITEM_ID: number
  PURCHASEDEMANDDETAIL_QUANTITY: number
  PURCHASEDEMANDDETAIL_UNIT_ID: number
  PURCHASEDEMANDDETAIL_DESCRIPTION?: string
  PURCHASEDEMANDDETAIL_COMPANY_ID?: number
  PURCHASEDEMANDDETAIL_CLOSED: boolean
  PURCHASEDEMANDDETAIL_CONFIRM: number
  PURCHASEDEMANDDETAIL_CONFIRMUSER_ID?: number
  PURCHASEDEMANDDETAIL_REGUSER_ID: number
  PURCHASEDEMANDDETAIL_REGDATE: Date
  PURCHASEDEMANDDETAIL_REGIP: string
  PURCHASEDEMANDDETAIL_SALESORDERMASTER_ID?: number
  PURCHASEDEMANDDETAIL_SECTION_ID: number
  PURCHASEDEMANDDETAIL_DELIVERYDATE: Date
  PURCHASEDEMANDDETAIL_ITEMNUMBER?: string
  PURCHASEDEMANDDETAIL_ITEMNAME?: string
  PURCHASEDEMANDDETAIL_UNITCODE?: string
  PURCHASEDEMANDDETAIL_UNITNAME?: string
  PURCHASEDEMANDDETAIL_COMPANYCODE?: string
  PURCHASEDEMANDDETAIL_COMPANYNAME?: string
  PURCHASEDEMANDDETAIL_CONFIRMUSERNAME?: string
  PURCHASEDEMANDDETAIL_SECTIONCODE?: string
  PURCHASEDEMANDDETAIL_SECTIONNAME?: string
  PURCHASEDEMANDDETAIL_SALESORDERMASTERNUMBER?: number
}
