export interface V_PurchaseOrderDetailSub {
  ID: number
  PURCHASEORDERDETAILSUB_MASTER_ID: number
  PURCHASEORDERDETAILSUB_DETAIL_ID: number
  PURCHASEORDERDETAILSUB_ITEM_ID: number
  PURCHASEORDERDETAILSUB_PRICE: number
  PURCHASEORDERDETAILSUB_CURRENCY_ID?: number
  PURCHASEORDERDETAILSUB_UNIT_ID: number
  PURCHASEORDERDETAILSUB_DESCRIPTION?: string
  PURCHASEORDERDETAILSUB_REGDATE: Date
  PURCHASEORDERDETAILSUB_REGIP: string
  PURCHASEORDERDETAILSUB_REGUSER_ID: number
  PURCHASEORDERDETAILSUB_NOINVOICE?: boolean
  PURCHASEORDERDETAILSUB_ITEMNUMBER?: string
  PURCHASEORDERDETAILSUB_ITEMNAME?: string
}
