export interface V_PurchaseOfferCompany {
  ID: number
  PURCHASEOFFERCOMPANY_MASTER_ID?: number
  PURCHASEOFFERCOMPANY_OFFERCOMPANYFALLOW_ID?: number
  PURCHASEOFFERCOMPANY_COMPANY_ID?: number
  PURCHASEOFFERCOMPANY_DATE?: Date
  PURCHASEOFFERCOMPANY_ACTIVE?: boolean
  PURCHASEOFFERCOMPANY_REGUSER_ID?: number
  PURCHASEOFFERCOMPANY_REGDATE?: Date
  PURCHASEOFFERCOMPANY_REGIP?: string
  PURCHASEOFFERCOMPANY_COMPANYCODE?: string
  PURCHASEOFFERCOMPANY_COMPANYNAME?: string
}
