export interface V_PurchaseOfferDetail {
  ID: number
  PURCHASEOFFERDETAIL_MASTER_ID?: number
  PURCHASEOFFERDETAIL_PURCHASEDEMANDDETAIL_ID?: number
  PURCHASEOFFERDETAIL_ITEM_ID?: number
  PURCHASEOFFERDETAIL_QUANTITY?: number
  PURCHASEOFFERDETAIL_UNIT_ID?: number
  PURCHASEOFFERDETAIL_DESCRIPTION1?: string
  PURCHASEOFFERDETAIL_DESCRIPTION2?: string
  PURCHASEOFFERDETAIL_CLOSED?: boolean
  PURCHASEOFFERDETAIL_REGUSER_ID?: number
  PURCHASEOFFERDETAIL_REGDATE?: Date
  PURCHASEOFFERDETAIL_REGIP?: string
  PURCHASEOFFERDETAIL_ITEMNUMBER?: string
  PURCHASEOFFERDETAIL_ITEMNAME?: string
  PURCHASEOFFERDETAIL_UNITCODE?: string
  PURCHASEOFFERDETAIL_UNITNAME?: string
}
