export interface V_SalesPriceDetailSub {
  ID: number
  SALESPRICEDETAILSUB_DETAIL_ID?: number
  SALESPRICEDETAILSUB_ITEM_ID: number
  SALESPRICEDETAILSUB_PRICE: number
  SALESPRICEDETAILSUB_UNIT_ID: number
  SALESPRICEDETAILSUB_REGDATE: Date
  SALESPRICEDETAILSUB_REGIP: string
  SALESPRICEDETAILSUB_REGUSER_ID: number
  SALESPRICEDETAILSUB_CURRENCY_ID: number
  SALESPRICEDETAILSUB_MASTER_ID: number
  SALESPRICEDETAILSUB_ITEMNUMBER?: string
  SALESPRICEDETAILSUB_ITEMNAME?: string
  SALESPRICEDETAILSUB_UNITCODE?: string
  SALESPRICEDETAILSUB_UNITNAME?: string
  SALESPRICEDETAILSUB_CURRENCYCODE?: string
  SALESPRICEDETAILSUB_CURRENCYNAME?: string
}
