export interface V_SetUserDefinition {
  ID: number
  SETUSERDEFINITION_REGUSER_ID: number
  SETUSERDEFINITION_REGDATE: Date
  SETUSERDEFINITION_REGIP: string
  SETUSERDEFINITION_PERSON_ID?: number
  SETUSERDEFINITION_USERNAME: string
  SETUSERDEFINITION_USERPASS: string
  SETUSERDEFINITION_USERGROUP_ID: number
  SETUSERDEFINITION_ADMIN: boolean
  SETUSERDEFINITION_ENTERDATE?: Date
  SETUSERDEFINITION_EXITDATE?: Date
  SETUSERDEFINITION_NAME: string
  SETUSERDEFINITION_SURNAME: string
  SETUSERDEFINITION_REPRESENTATIVE: boolean
  SETUSERDEFINITION_DEPARTMENT_ID: number
  SETUSERDEFINITION_EMAIL?: string
  SETUSERDEFINITION_IMAGE?: string
  SETUSERDEFINITION_USERGROUPNAME?: string
  SETUSERDEFINITION_DEPARTMENTNAME?: string
  SETUSERDEFINITION_DEPARTMENTCODE?: string
}
