export interface V_SetUserDepartment {
  ID: number
  SETUSERDEPARTMENT_USER_ID: number
  SETUSERDEPARTMENT_DEPARTMENT_ID: number
  SETUSERDEPARTMENT_REGUSER_ID: number
  SETUSERDEPARTMENT_REGDATE: Date
  SETUSERDEPARTMENT_REGIP: string
  SETUSERDEPARTMENT_DEPARTMENTCODE?: string
  SETUSERDEPARTMENT_DEPARTMENTNAME?: string
}
