export interface V_SetPermissionMaster {
  ID: number
  SETPERMISSIONMASTER_REGUSER_ID: number
  SETPERMISSIONMASTER_REGDATE: Date
  SETPERMISSIONMASTER_REGIP: string
  SETPERMISSIONMASTER_USERGROUP_ID: number
  SETPERMISSIONMASTER_DETAIL_ID: number
  SETPERMISSIONMASTER_TYPE: number
  SETPERMISSIONMASTER_TITLE?: string
  SETPERMISSIONMASTER_GROUPNAME?: string
  SETPERMISSIONMASTER_MENUPATH?: string
}
