export interface V_SetUserStore {
  ID: number
  SETUSERSTORE_USER_ID: number
  SETUSERSTORE_STORE_ID: number
  SETUSERSTORE_REGUSER_ID: number
  SETUSERSTORE_REGDATE: Date
  SETUSERSTORE_REGIP: string
  SETUSERSTORE_SOURCESTORE: boolean
  SETUSERSTORE_TARGETSTORE: boolean
  SETUSERSTORE_STORECODE?: string
  SETUSERSTORE_STORENAME?: string
}
