export interface V_SetUserCorporation {
  ID: number
  SETUSERCORPORATION_USER_ID: number
  SETUSERCORPORATION_CORP_ID: number
  SETUSERCORPORATION_SECTION_ID: number
  SETUSERCORPORATION_REGUSER_ID: number
  SETUSERCORPORATION_REGDATE: Date
  SETUSERCORPORATION_REGIP: string
  SETUSERCORPORATION_CORPORATIONCODE: string
  SETUSERCORPORATION_CORPORATIONNAME: string
  SETUSERCORPORATION_SECTIONCODE: string
  SETUSERCORPORATION_SECTIONNAME: string
}
