export interface V_StockDemandMaster {
  ID: number
  STOCKDEMANDMASTER_CORP_ID?: number
  STOCKDEMANDMASTER_SECTION_ID?: number
  STOCKDEMANDMASTER_YEAR: number
  STOCKDEMANDMASTER_NUMBER?: number
  STOCKDEMANDMASTER_DATE: Date
  STOCKDEMANDMASTER_DEPARTMENT_ID?: number
  STOCKDEMANDMASTER_SHIFT_ID?: number
  STOCKDEMANDMASTER_FACTORY_ID?: number
  STOCKDEMANDMASTER_REGUSER_ID?: number
  STOCKDEMANDMASTER_REGDATE?: Date
  STOCKDEMANDMASTER_REGIP?: string
  STOCKDEMANDMASTER_CLOSED?: boolean
  STOCKDEMANDMASTER_STORE_ID?: number
  STOCKDEMANDMASTER_DESCRIPTION?: string
  STOCKDEMANDMASTER_SECTIONCODE?: string
  STOCKDEMANDMASTER_SECTIONNAME?: string
  STOCKDEMANDMASTER_DEPARTMENTCODE?: string
  STOCKDEMANDMASTER_DEPARTMENTNAME?: string
  STOCKDEMANDMASTER_SHIFTCODE?: string
  STOCKDEMANDMASTER_SHIFTNAME?: string
  STOCKDEMANDMASTER_FACTORYCODE?: string
  STOCKDEMANDMASTER_FACTORYNAME?: string
  STOCKDEMANDMASTER_STORECODE?: string
  STOCKDEMANDMASTER_STORENAME?: string
}
