export interface V_StockDemandDetail {
  ID: number
  STOCKDEMANDDETAIL_MASTER_ID?: number
  STOCKDEMANDDETAIL_ITEM_ID?: number
  STOCKDEMANDDETAIL_QUANTITY?: number
  STOCKDEMANDDETAIL_UNIT_ID?: number
  STOCKDEMANDDETAIL_DESCRIPTION?: string
  STOCKDEMANDDETAIL_REGUSER_ID?: number
  STOCKDEMANDDETAIL_REGDATE?: Date
  STOCKDEMANDDETAIL_REGIP?: string
  STOCKDEMANDDETAIL_CLOSED?: boolean
  STOCKDEMANDDETAIL_ITEMNUMBER?: string
  STOCKDEMANDDETAIL_ITEMNAME?: string
  STOCKDEMANDDETAIL_UNITCODE?: string
  STOCKDEMANDDETAIL_UNITNAME?: string
  STOCKDEMANDDETAIL_ITEMTYPECODE?: string
}
